/* TNT chat: shared identity, contextual rooms and private attachments. */
(() => {
'use strict';
const U=TNTUI,sb=TNT.sb,$=s=>document.querySelector(s);
if(!window.TNTEditor){window.TNTEditor={render:(plain)=>U.esc(plain||''),attach:(input)=>{const api={get:()=>({text:input.value||'',html:U.esc(input.value||'')}),set:(v)=>{input.value=v||''},focus:()=>input.focus(),lock:(v)=>{input.readOnly=!!v}};input.tntEditor=api;api.wrap={querySelector:()=>({hidden:true})};return api;}};}
const S={threads:[],people:[],accounts:[],members:[],events:[],efeGroups:[],efeMembers:[],groups:[],groupMembers:[],eventMembers:[],tasks:[],assignees:[],overview:[],messages:[],reactions:[],active:null,request:0,drafts:{},reply:null,audience:null,bubbleColor:'lime',pendingMessageId:null,files:[],uploaded:[],stars:[],recording:null,sending:false,oldest:null,hasOlder:false,readAt:{},timer:null};
const bubbleColors={lime:'Verde',lilac:'Lila',peach:'Durazno',sky:'Celeste',rose:'Rosa',neutral:'Gris'};
const bubbleClass=color=>Object.hasOwn(bubbleColors,color)?' bubble-'+color:'';
function updateBubbleButton(){const button=$('#chat-bubble-color');if(!button)return;button.innerHTML=`<i class="bubble-dot bubble-${S.bubbleColor}"></i><span>Burbuja: ${bubbleColors[S.bubbleColor]}</span>`;button.setAttribute('aria-label','Color de burbuja: '+bubbleColors[S.bubbleColor]+'. Cambiar antes de enviar');}
function chooseBubbleColor(){if(!S.active||S.sending||S.recording)return;const o=U.modal('Color de la burbuja',`<p>Elegí cómo se verá este mensaje para todos en el chat.</p><div class="chat-bubble-palette">${Object.entries(bubbleColors).map(([key,label])=>`<button type="button" data-bubble-color="${key}" class="bubble-${key}" aria-pressed="${S.bubbleColor===key}"><span>${U.esc(label)}</span>${S.bubbleColor===key?'✓':''}</button>`).join('')}</div>`);o.querySelectorAll('[data-bubble-color]').forEach(b=>b.onclick=()=>{S.bubbleColor=b.dataset.bubbleColor;updateBubbleButton();persistDraft();U.closeModal(o);});}
let editor;
const draftKey=()=>`tnt-chat-drafts-${me()}`;
const me=()=>TNT.person?.id,person=id=>S.people.find(p=>p.id===id)||{},account=id=>S.accounts.find(a=>a.person_id===id)||{},name=id=>account(id).nickname||person(id).full_name||'Equipo TNT';
const thread=()=>S.threads.find(t=>t.id===S.active),today=()=>U.dateKey(),canCreate=()=>TNT.isAdmin||S.tasks.some(t=>t.task_type==='logistics'&&S.assignees.some(a=>a.task_id===t.id&&a.person_id===me()&&a.assignment_status!=='declined')&&S.events.some(e=>e.id===t.event_id&&e.kind!=='saturday'&&e.end_date>=today()));
const art=t=>U.icon(t.thread_type==='task'?'check':t.thread_type==='event'?'calendar':'chat');
const type=t=>({general:'Todo TNT',task:'Equipo de la tarea',event:'Participantes del evento',module:'Equipo · '+(t.module||'TNT'),efe:'Equipo EFE',direct:'Conversación privada'}[t.thread_type]||'Equipo TNT');
const err=e=>e?.message||'No pudimos conectar. Reintentá en unos segundos.';
function roster(t){if(!t)return[];const ids=new Set(S.members.filter(m=>m.thread_id===t.id).map(m=>m.person_id));return [...ids].sort((a,b)=>(b===me())-(a===me())||name(a).localeCompare(name(b)));}
function threadAllowed(t){if(t.thread_type==='general')return true;const event=S.events.find(e=>e.id===(t.event_id||S.tasks.find(x=>x.id===t.task_id)?.event_id));if(!event||event.status==='cancelled')return false;if(event.end_date<today())return false;if(event.kind!=='saturday')return true;const d=today(),weekday=new Date(d+'T12:00:00Z').getUTCDay(),next=U.addDays(d,(6-weekday+7)%7),last=d===next?U.addDays(next,7):next;return event.start_date<=last;}
const summary=id=>S.overview.find(x=>x.thread_id===id)||{};
async function start(){await TNT.ready;if(!TNT.identity||TNT.blocked)return;$('#new-chat').innerHTML=U.icon('plus');$('#new-chat').hidden=true;$('#search-icon').innerHTML=U.icon('search');$('#welcome-icon').innerHTML=U.icon('chat');$('#chat-send').innerHTML=U.icon('send');$('#chat-attach').innerHTML=U.icon('clip');try{S.drafts=JSON.parse(localStorage.getItem(draftKey())||'{}');}catch{}bind();await loadMeta();await loadStars();const requested=new URLSearchParams(location.search).get('thread');history.replaceState({...history.state,tntChatRoom:null},'',location.pathname);window.addEventListener('popstate',event=>{if(document.querySelector('dialog.tnt-select-dialog,dialog.tnt-overlay'))return;const id=event.state?.tntChatRoom;if(id&&S.threads.some(t=>t.id===id)){if(S.active!==id)open(id,false);}else closeRoom();});if(requested){if(S.threads.some(t=>t.id===requested))await open(requested);else $('#chat-error').textContent='Esta conversación no está disponible para tu cuenta.';}let ticks=0;S.timer=setInterval(async()=>{if(document.hidden)return;if(++ticks%4===0)await loadMeta();else await refreshOverview();if(S.active&&roomVisible())await loadMessages(false);},8000);window.addEventListener('pagehide',()=>{persistDraft();cancelRecording();clearInterval(S.timer);},{once:true});document.addEventListener('visibilitychange',()=>{if(!document.hidden&&S.active&&roomVisible())loadMessages(false);});}
async function loadMeta(){const tables={threads:'tnt_chat_threads',people:'tnt_people',accounts:'tnt_accounts',members:'tnt_chat_members',events:'tnt_events',efeGroups:'tnt_efe_groups',efeMembers:'tnt_efe_memberships',groups:'tnt_groups',groupMembers:'tnt_group_members',eventMembers:'tnt_event_members',tasks:'tnt_tasks',assignees:'tnt_task_assignees'},errors=[];await Promise.all(Object.entries(tables).map(async([key,table])=>{try{let q=sb.from(table).select('*');if(key==='threads')q=q.eq('is_archived',false).order('is_pinned',{ascending:false}).order('updated_at',{ascending:false});const r=await q;if(r.error)throw r.error;S[key]=r.data||[];}catch(e){errors.push(err(e));}}));$('#chat-error').textContent=errors.length?'No pudimos actualizar todas las conversaciones.':'';if(errors.length){const b=document.createElement('button');b.className='tnt-button';b.textContent='Reintentar';b.onclick=loadMeta;$('#chat-error').append(b);}await refreshOverview();$('#new-chat').hidden=!canCreate();renderTeam();renderThreads();if(S.active)renderRoomHead();}
async function refreshOverview(){const r=await sb.rpc('tnt_chat_overview');if(r.error){if(!S.overview.length)$('#chat-error').textContent='No pudimos consultar los mensajes pendientes.';return;}S.overview=r.data||[];renderThreads();}
function renderTeam(){const ids=S.accounts.filter(a=>a.enabled&&(a.staff_status==='approved'||a.system_role==='admin')&&a.auth_user_id).map(a=>a.person_id).sort((a,b)=>(b===me())-(a===me())).slice(0,10);$('#chat-team').hidden=ids.length<2;$('#chat-team').innerHTML=ids.map(id=>`<button class="chat-team-person" data-team-person="${id}">${U.avatar(person(id),account(id))}<span>${U.esc(id===me()?'Vos':name(id).split(' ')[0])}</span></button>`).join('');$('#chat-team').querySelectorAll('[data-team-person]').forEach(b=>b.onclick=()=>showPerson(b.dataset.teamPerson));}
function renderThreads(){const term=($('#chat-search').value||'').trim().toLocaleLowerCase('es');const list=S.threads.filter(t=>threadAllowed(t)&&(t.title+' '+type(t)).toLocaleLowerCase('es').includes(term)).sort((a,b)=>Number(b.is_pinned)-Number(a.is_pinned)||String(summary(b.id).last_created_at||b.created_at).localeCompare(String(summary(a.id).last_created_at||a.created_at)));$('#chat-threads').innerHTML=list.map(t=>{const o=summary(t.id);return `<button class="chat-thread ${S.active===t.id?'is-active':''}" data-thread="${t.id}" aria-current="${S.active===t.id}"><span class="thread-art ${t.thread_type}">${art(t)}</span><span><span class="thread-title">${U.esc(t.title)}</span><span class="thread-preview">${U.esc(o.last_body||type(t))}</span></span><span class="thread-meta"><time>${o.last_created_at?U.time(o.last_created_at):''}</time>${Number(o.unread_count)>0?`<span class="thread-unread" aria-label="${Number(o.unread_count)} sin leer">${Number(o.unread_count)>99?'99+':Number(o.unread_count)}</span>`:t.is_pinned?U.icon('pin'):''}</span></button>`;}).join('')||`<div class="tnt-empty">${term?'No hay coincidencias.':'Todavía no hay conversaciones. Abrí el chat desde una tarea o un evento.'}</div>`;$('#chat-threads').querySelectorAll('[data-thread]').forEach(b=>b.onclick=()=>open(b.dataset.thread));}
function roomVisible(){return !document.hidden&&($('#chat-app').classList.contains('room-open')||window.innerWidth>720);}
async function open(id,recordHistory=true){
 if(S.sending)return U.toast('Esperá a que termine el envío.');
 if(S.recording)return U.toast('Terminá o descartá el audio antes de cambiar de conversación.');
 persistDraft();S.request++;S.active=id;S.messages=[];S.reactions=[];S.oldest=null;S.hasOlder=false;
 const d=S.drafts[id]||{};S.reply=d.reply||null;S.audience=d.audience||null;S.bubbleColor=Object.hasOwn(bubbleColors,d.bubbleColor)?d.bubbleColor:'lime';updateBubbleButton();S.pendingMessageId=d.pendingMessageId||null;S.files=d.files||[];S.uploaded=d.uploaded||[];editor.set(d.text||'',d.rich||'');
 $('#chat-app').classList.add('room-open');$('#chat-compose-wrap').hidden=false;$('#chat-composer-status').textContent='';
 $('#chat-audience').hidden=!TNT.isAdmin;
 renderDraft();renderRoomHead();renderThreads();$('#chat-messages').innerHTML='<div class="tnt-empty">Cargando mensajes…</div>';
 if(recordHistory)history.pushState({...history.state,tntChatRoom:id},'','?thread='+encodeURIComponent(id));await loadMessages(true);
}
function closeRoom(){persistDraft();S.request++;S.active=null;$('#chat-app').classList.remove('room-open');$('#chat-compose-wrap').hidden=true;$('#chat-room-head').innerHTML='';renderThreads();}
function canManageThread(t){return !!t&&(TNT.isAdmin||t.thread_type==='task'&&t.created_by===me()&&S.assignees.some(a=>a.task_id===t.task_id&&a.person_id===me()));}
function renderRoomHead(){const t=thread();if(!t)return;const ids=roster(t),joined=S.members.some(m=>m.thread_id===t.id&&m.person_id===me());$('#chat-room-head').innerHTML=`<button class="tnt-icon-button chat-back" id="chat-back" aria-label="Volver a conversaciones">${U.icon('back')}</button><span class="thread-art ${t.thread_type}">${art(t)}</span><div class="room-heading"><h2>${U.esc(t.title)}</h2><p>${U.esc(type(t))}</p></div><button class="room-people" id="room-people" aria-label="Ver participantes">${U.avatarStack(ids,S.people,S.accounts,me(),3)}<small>${ids.length} ${ids.length===1?'participante':'participantes'}</small></button>${TNT.isAdmin&&!joined?'<button class="tnt-button chat-join" id="room-join">Entrar</button>':''}${canManageThread(t)?'<button class="tnt-icon-button" id="room-options" aria-label="Editar conversación">'+U.icon('more')+'</button>':''}`;$('#chat-back').onclick=()=>{if(history.state?.tntChatRoom)history.back();else closeRoom();};$('#room-people').onclick=()=>showParticipants();$('#room-options')?.addEventListener('click',threadOptions);$('#room-join')?.addEventListener('click',async()=>{const r=await sb.from('tnt_chat_members').insert({thread_id:t.id,person_id:me(),member_role:'member'});if(r.error)return U.toast(err(r.error),true);await loadMeta();U.toast('Ahora figurás como participante de este chat.');});}
function threadOptions(){const t=thread();if(!canManageThread(t))return;const o=U.modal('Administrar conversación',`<form class="tnt-form" id="thread-edit"><label>Nombre del chat<input name="title" required minlength="3" maxlength="100" value="${U.esc(t.title)}"></label><button class="tnt-button primary" type="submit">Guardar nombre</button><p role="alert"></p></form><div class="chat-thread-manage"><button class="tnt-button" id="manage-members">Elegir participantes</button><button class="tnt-button danger" id="archive-thread">Eliminar conversación</button></div><p class="tnt-help">Al eliminarla se quita de la lista y podés crear un chat nuevo desde cero. El historial queda archivado.</p>`);o.querySelector('#thread-edit').onsubmit=async e=>{e.preventDefault();const title=e.target.elements.title.value.trim();if(title.length<3)return;const r=await sb.from('tnt_chat_threads').update({title}).eq('id',t.id).select().single();if(r.error){o.querySelector('[role=alert]').textContent=err(r.error);return;}t.title=title;U.closeModal(o);renderRoomHead();renderThreads();};o.querySelector('#manage-members')?.addEventListener('click',()=>{manageMembers(t);});o.querySelector('#archive-thread').onclick=()=>{const confirm=U.modal('Eliminar conversación',`<p>¿Querés quitar <b>${U.esc(t.title)}</b> de los chats? Podrás crear una nueva conversación sin mensajes anteriores. El historial quedará archivado.</p><button class="tnt-button danger" id="confirm-archive">Eliminar conversación</button><p role="alert"></p>`);confirm.querySelector('#confirm-archive').onclick=async()=>{const button=confirm.querySelector('#confirm-archive');button.disabled=true;const r=await sb.from('tnt_chat_threads').update({is_archived:true}).eq('id',t.id).select().single();if(r.error){button.disabled=false;confirm.querySelector('[role=alert]').textContent=err(r.error);return;}U.closeModal(confirm);S.active=null;$('#chat-app').classList.remove('room-open');$('#chat-compose-wrap').hidden=true;$('#chat-room-head').innerHTML='';$('#chat-messages').innerHTML='<div class="chat-welcome"><h2>Elegí una conversación.</h2></div>';history.replaceState({...history.state,tntChatRoom:null},'',location.pathname);await loadMeta();};};}
function manageMembers(t){if(!canManageThread(t))return;const selected=new Set(S.members.filter(m=>m.thread_id===t.id).map(m=>m.person_id));const event=S.events.find(e=>e.id===(t.event_id||S.tasks.find(x=>x.id===t.task_id)?.event_id));const eligible=S.accounts.filter(a=>a.enabled&&(a.staff_status==='approved'||a.system_role==='admin')&&a.auth_user_id&&(TNT.isAdmin||a.person_id===me()||S.eventMembers.some(m=>m.event_id===event?.id&&m.person_id===a.person_id)||S.assignees.some(m=>m.person_id===a.person_id&&S.tasks.some(task=>task.id===m.task_id&&task.event_id===event?.id))));const o=U.modal('Participantes de '+t.title,`<form class="tnt-form" id="member-form"><p>Los Administradores pueden supervisar este chat sin aparecer como participantes. Al marcarlos, se unirán visiblemente.</p><div class="chat-member-picker">${eligible.map(a=>`<label><input type="checkbox" value="${a.person_id}" ${selected.has(a.person_id)?'checked':''} ${!TNT.isAdmin&&a.person_id===me()?'disabled':''}>${U.avatar(person(a.person_id),a)}<span>${U.esc(name(a.person_id))}</span></label>`).join('')}</div><button class="tnt-button primary" type="submit">Guardar participantes</button><p role="alert"></p></form>`);o.querySelector('#member-form').onsubmit=async e=>{e.preventDefault();const button=e.target.querySelector('[type=submit]');button.disabled=true;const next=new Set([...e.target.querySelectorAll('input:checked')].map(x=>x.value));if(!TNT.isAdmin)next.add(me());try{for(const id of next)if(!selected.has(id)){const r=await sb.from('tnt_chat_members').insert({thread_id:t.id,person_id:id,member_role:'member'});if(r.error)throw r.error;}for(const id of selected)if(!next.has(id)){const r=await sb.from('tnt_chat_members').delete().eq('thread_id',t.id).eq('person_id',id);if(r.error)throw r.error;}U.closeModal(o);await loadMeta();await loadMessages(false);U.toast('Participantes actualizados.');}catch(ex){e.target.querySelector('[role=alert]').textContent=err(ex);}finally{button.disabled=false;}};}
async function loadMessages(first=false,older=false){const id=S.active,seq=++S.request;if(!id)return;let q=sb.from('tnt_chat_messages').select('*').eq('thread_id',id).order('created_at',{ascending:false}).order('id',{ascending:false}).limit(60);if(older&&S.oldest)q=q.lt('created_at',S.oldest);const r=await q;if(seq!==S.request||id!==S.active)return;if(r.error){$('#chat-composer-status').textContent='No pudimos actualizar los mensajes. Tu borrador se conserva.';if(first)$('#chat-messages').innerHTML='<div class="tnt-empty">No pudimos cargar esta conversación. <button class="tnt-button" id="retry-messages">Reintentar</button></div>';$('#retry-messages')?.addEventListener('click',()=>loadMessages(true));return;}const batch=(r.data||[]).reverse(),previous=S.messages,atBottom=$('#chat-messages').scrollHeight-$('#chat-messages').scrollTop-$('#chat-messages').clientHeight<100;S.messages=older?[...batch,...previous]:previous.length>60?[...previous.filter(m=>!batch.some(x=>x.id===m.id)&&m.created_at<(batch[0]?.created_at||'')),...batch]:batch;if(first||older)S.hasOlder=batch.length===60;S.oldest=S.messages[0]?.created_at||null;const ids=S.messages.map(m=>m.id);const [rr,mr]=await Promise.all([ids.length?sb.from('tnt_chat_reactions').select('*').in('message_id',ids):Promise.resolve({data:[]}),sb.from('tnt_chat_members').select('*').eq('thread_id',id)]);if(seq!==S.request||id!==S.active)return;if(!rr.error)S.reactions=rr.data||[];if(!mr.error){S.members=[...S.members.filter(m=>m.thread_id!==id),...(mr.data||[])];renderRoomHead();}const signature=JSON.stringify([S.messages,S.reactions,S.members.filter(m=>m.thread_id===id)]);if(S.signature!==signature||first||older){const before=$('#chat-messages').scrollHeight,scroll=$('#chat-messages').scrollTop;renderMessages();if(older)$('#chat-messages').scrollTop=$('#chat-messages').scrollHeight-before+scroll;else if(first||atBottom)$('#chat-messages').scrollTop=$('#chat-messages').scrollHeight;S.signature=signature;}if(!rr.error&&!S.sendError&&!S.sending)$('#chat-composer-status').textContent='';if(roomVisible())await markRead(id);}
async function markRead(id){const last=S.messages.at(-1)?.created_at;if(!last||S.readAt[id]>=last)return;if(TNT.isAdmin&&!S.members.some(m=>m.thread_id===id&&m.person_id===me())){S.readAt[id]=last;return;}const at=new Date().toISOString(),existing=S.members.find(m=>m.thread_id===id&&m.person_id===me());const r=existing?await sb.from('tnt_chat_members').update({last_read_at:at}).eq('thread_id',id).eq('person_id',me()):await sb.from('tnt_chat_members').insert({thread_id:id,person_id:me(),member_role:'member',last_read_at:at});if(r.error)return;S.readAt[id]=last;if(existing)existing.last_read_at=at;else S.members.push({thread_id:id,person_id:me(),last_read_at:at,member_role:'member'});summary(id).unread_count=0;renderThreads();}
function linkify(body){return String(body||'').split(/(https?:\/\/[^\s<>]+)/g).map(s=>/^https?:\/\//.test(s)?`<a href="${U.esc(U.safeUrl(s))}" target="_blank" rel="noopener noreferrer">${U.esc(s)}</a>`:U.esc(s)).join('');}
function firstName(id){return String(name(id)).trim().split(/\s+/)[0]||'TNT';}
function renderMessages(){let day='';const items=S.messages.map((m,index)=>{
 const mine=m.person_id===me(),dk=U.dateKey(m.created_at),previous=S.messages[index-1];
 const grouped=!!previous&&previous.person_id===m.person_id&&U.dateKey(previous.created_at)===dk;
 const files=messageFiles(m),hasAudio=!m.deleted_at&&files.some(isAudioFile);
 let sep='';if(day!==dk){day=dk;sep=`<div class="chat-day">${U.date(m.created_at,{weekday:'long',day:'numeric',month:'long'})}</div>`;}
 const replied=S.messages.find(x=>x.id===m.reply_to),reactions=S.reactions.filter(r=>r.message_id===m.id),groups=[...new Set(reactions.map(r=>r.reaction))];
 const readers=S.members.filter(x=>x.thread_id===S.active&&x.person_id!==me()&&x.last_read_at>=m.created_at&&(!m.audience_person_ids||m.audience_person_ids.includes(x.person_id)));
 const sender=!mine&&!grouped?`<span class="message-name">${U.esc(firstName(m.person_id))}</span>`:'';
 const reply=m.reply_to&&!m.deleted_at?`<button class="message-reply" data-jump="${m.reply_to}"><b>${replied?U.esc(firstName(replied.person_id)):'Respuesta a un mensaje anterior'}</b><span>${replied?.deleted_at?'Mensaje eliminado':U.esc(replied?.body||replied?.attachment_name||'Ver mensaje')}</span></button>`:'';
 const attachments=!m.deleted_at?files.map((f,i)=>`<div class="message-media" data-media="${m.id}" data-media-index="${i}"></div>${isAudioFile(f)?'':`<button class="message-attachment" data-attachment="${m.id}" data-file-index="${i}">${U.icon('file')}<span>${U.esc(f.name||'Archivo')}</span>${U.icon('download')}</button>`}`).join(''):'';
 const reactionsHtml=!m.deleted_at&&groups.length?`<div class="message-reactions">${groups.map(reaction=>{const rs=reactions.filter(r=>r.reaction===reaction);return `<button class="${rs.some(r=>r.person_id===me())?'chosen':''}" data-reaction-id="${m.id}" data-reaction="${U.esc(reaction)}" aria-label="${U.esc(reaction)} · ${rs.length} reacciones" title="${U.esc(rs.map(r=>firstName(r.person_id)).join(', '))}">${U.esc(reaction)} ${rs.length}</button>`;}).join('')}</div>`:'';
 return sep+`<article class="chat-message ${mine?'is-mine':''} ${grouped?'same-sender':''} ${hasAudio?'has-audio':''}" id="message-${m.id}" data-message-id="${m.id}">${!mine&&!grouped&&!hasAudio?U.avatar(person(m.person_id),account(m.person_id)):''}<div class="message-stack"><div class="message-bubble${bubbleClass(m.bubble_color)}">${sender}${m.audience_person_ids?.length?`<span class="message-audience" title="Solo destinatarios elegidos">🔒 Solo ${m.audience_person_ids.length} ${m.audience_person_ids.length===1?'persona':'personas'}</span>`:''}${reply}<div class="message-body ${m.deleted_at?'message-deleted':''}">${m.deleted_at?'Mensaje eliminado':TNTEditor.render(m.body,m.body_rich)}</div>${attachments}<div class="message-info">${S.stars.some(x=>x.entity_id===m.id)?'<span aria-label="Destacado">★</span>':''}${m.pinned&&!m.deleted_at?U.icon('pin'):''}<time>${U.time(m.created_at)}${m.edited_at?' · editado':''}</time>${mine&&readers.length?`<button data-readers="${m.id}">Leído ${U.icon('check')}</button>`:''}${!m.deleted_at?`<button data-message-actions="${m.id}" aria-label="Opciones del mensaje">${U.icon('more')}</button>`:''}</div></div>${reactionsHtml}</div></article>`;
 });
$('#chat-messages').innerHTML=(S.hasOlder?'<button class="tnt-button" id="older-messages">Ver mensajes anteriores</button>':'')+(items.join('')||'<div class="chat-welcome"><h2>Sin mensajes todavía</h2><p>Escribí un mensaje para iniciar la conversación.</p></div>');$('#older-messages')?.addEventListener('click',()=>loadMessages(false,true));$('#chat-messages').querySelectorAll('[data-message-actions]').forEach(b=>b.onclick=()=>messageActions(b.dataset.messageActions));$('#chat-messages').querySelectorAll('[data-reaction-id]').forEach(b=>b.onclick=()=>react(b.dataset.reactionId,b.dataset.reaction));$('#chat-messages').querySelectorAll('[data-attachment]').forEach(b=>b.onclick=()=>attachment(b.dataset.attachment,Number(b.dataset.fileIndex||0)));$('#chat-messages').querySelectorAll('[data-jump]').forEach(b=>b.onclick=()=>jump(b.dataset.jump));$('#chat-messages').querySelectorAll('[data-readers]').forEach(b=>b.onclick=()=>showReaders(b.dataset.readers));bindMessageGestures();hydrateAttachments();const pinned=S.messages.filter(m=>m.pinned&&!m.deleted_at);$('#chat-pinned').hidden=!pinned.length;$('#chat-pinned').innerHTML=pinned.length?`<button id="show-pinned">${U.icon('pin')}<span>${pinned.length} ${pinned.length===1?'mensaje fijado':'mensajes fijados'} · ${U.esc(pinned.at(-1).body||pinned.at(-1).attachment_name)}</span></button>`:'';$('#show-pinned')?.addEventListener('click',()=>{const o=U.modal('Mensajes fijados',pinned.map(m=>`<button class="tnt-button" data-pin-jump="${m.id}">${U.esc(m.body||m.attachment_name)}</button>`).join(''));o.querySelectorAll('[data-pin-jump]').forEach(b=>b.onclick=()=>{U.closeModal(o);jump(b.dataset.pinJump);});});}
function jump(id){const el=document.getElementById('message-'+id);if(!el)return U.toast('Este mensaje es anterior. Cargá los mensajes anteriores para verlo.');el.scrollIntoView({block:'center',behavior:'smooth'});el.classList.add('flash');setTimeout(()=>el.classList.remove('flash'),1600);}
function renderDraft(){
 const chunks=[];
 if(S.audience)chunks.push(`<div class="chat-draft-chip audience"><div><b>Solo: ${U.esc(S.audience.label)}</b><span>${S.audience.ids.length} ${S.audience.ids.length===1?'destinatario':'destinatarios'} · los demás no verán este mensaje</span></div><button class="tnt-icon-button" id="clear-audience" aria-label="Enviar a todo el chat">${U.icon('close')}</button></div>`);
 if(S.reply)chunks.push(`<div class="chat-draft-chip"><div><b>Respondiendo a ${U.esc(name(S.reply.person_id))}</b><span>${U.esc(S.reply.body||S.reply.attachment_name||'Archivo')}</span></div><button class="tnt-icon-button" id="cancel-reply" aria-label="Cancelar respuesta">${U.icon('close')}</button></div>`);
 S.files.forEach((f,i)=>chunks.push(`<div class="chat-draft-chip">${U.icon('file')}<div><b>${fileType(f).startsWith('audio/')?'Mensaje de voz':U.esc(f.name)}</b><span>${fileType(f).startsWith('audio/')?'Listo para enviar':Math.ceil(f.size/1024)+' KB · Listo para enviar'}</span>${fileType(f).startsWith('audio/')?audioWidget(f.previewUrl||'','Vista previa del audio'):''}</div><button class="tnt-icon-button" data-remove-file="${i}" aria-label="Quitar adjunto">${U.icon('close')}</button></div>`));
 $('#chat-draft-context').innerHTML=chunks.join('');
 $('#clear-audience')?.addEventListener('click',()=>{if(S.sending)return;S.audience=null;renderDraft();persistDraft();});
 $('#cancel-reply')?.addEventListener('click',()=>{if(S.sending)return;S.reply=null;renderDraft();persistDraft();});
 $('#chat-draft-context').querySelectorAll('[data-remove-file]').forEach(b=>b.onclick=()=>{if(S.sending)return;const i=Number(b.dataset.removeFile);if(S.files[i].previewUrl)URL.revokeObjectURL(S.files[i].previewUrl);S.files.splice(i,1);S.uploaded.splice(i,1);renderDraft();});
 bindAudioWidgets($('#chat-draft-context'));
}
async function send(e){
 e.preventDefault();const content=editor.get(),body=content.text.trim(),id=S.active;
 if(S.sending||!id||S.recording||(!body&&!S.files.length))return;
 S.sending=true;S.sendError=false;$('#chat-send').disabled=true;editor.lock(true);$('#chat-composer-status').textContent='Enviando…';
 try{
  const messageId=S.pendingMessageId||crypto.randomUUID();S.pendingMessageId=messageId;
  for(let i=0;i<S.files.length;i++)if(!S.uploaded[i]){const f=S.files[i],filename=f.name.replace(/[^a-zA-Z0-9._-]/g,'_'),path=id+'/'+me()+'/'+messageId+'/'+crypto.randomUUID()+'-'+filename,type=fileType(f);const r=await sb.storage.from('tnt-chat-files').upload(path,f,{contentType:type});if(r.error)throw r.error;S.uploaded[i]={path:'tnt-chat-files/'+path,name:f.name,type,size:f.size,...(f.durationSeconds?{duration_seconds:f.durationSeconds}:{})};}
  const payload={id:messageId,thread_id:id,person_id:me(),body,body_rich:body?content.html:null,bubble_color:S.bubbleColor,reply_to:S.reply?.id||null,attachments:S.uploaded.filter(Boolean),audience_person_ids:S.audience?.ids||null};
  const r=await sb.from('tnt_chat_messages').insert(payload).select().single();if(r.error)throw r.error;
  S.files.forEach(f=>f.previewUrl&&URL.revokeObjectURL(f.previewUrl));S.files=[];S.uploaded=[];S.reply=null;S.audience=null;S.bubbleColor='lime';updateBubbleButton();S.pendingMessageId=null;editor.set('');delete S.drafts[id];persistDraft();$('#chat-file').value='';renderDraft();await loadMessages(false);$('#chat-messages').scrollTop=$('#chat-messages').scrollHeight;$('#chat-composer-status').textContent='';await refreshOverview();
 }catch(e){S.sendError=true;persistDraft();$('#chat-composer-status').textContent='No se envió: '+err(e)+' Tu mensaje sigue acá.';}
 finally{S.sending=false;$('#chat-send').disabled=false;editor.lock(false);}
}
function resizeInput(){persistDraft();}
async function react(id,reaction){const existing=S.reactions.find(r=>r.message_id===id&&r.person_id===me()&&r.reaction===reaction);const r=existing?await sb.from('tnt_chat_reactions').delete().eq('message_id',id).eq('person_id',me()).eq('reaction',reaction):await sb.from('tnt_chat_reactions').insert({message_id:id,person_id:me(),reaction});if(r.error)return U.toast(err(r.error),true);await loadMessages(false);}
function messageActions(id){const m=S.messages.find(x=>x.id===id);if(!m||m.deleted_at)return;const own=m.person_id===me(),manage=own||TNT.isAdmin;const o=U.modal('Mensaje de '+name(m.person_id),`<div class="chat-actions">${['👍','❤️','🙌','👀','✅'].map(r=>`<button data-react="${r}" aria-label="Reaccionar ${r}">${r}</button>`).join('')}</div><div class="tnt-form"><button class="tnt-button" id="star-message">${S.stars.some(x=>x.entity_id===id)?'Quitar de destacados':'★ Destacar para mí'}</button><button class="tnt-button" id="copy-message">Copiar texto</button><button class="tnt-button" id="reply-message">${U.icon('reply')} Responder</button>${manage?`<button class="tnt-button" id="pin-message">${U.icon('pin')} ${m.pinned?'Desfijar':'Fijar mensaje'}</button>`:''}${own&&m.body?'<button class="tnt-button" id="edit-message">Editar mensaje</button>':''}${manage?'<button class="tnt-button" id="delete-message">Eliminar mensaje</button>':''}</div>`);o.querySelectorAll('[data-react]').forEach(b=>b.onclick=()=>{U.closeModal(o);react(id,b.dataset.react);});o.querySelector('#star-message').onclick=async()=>{await toggleStar(m);U.closeModal(o);};o.querySelector('#copy-message').onclick=async()=>{try{await navigator.clipboard.writeText(m.body||'');U.closeModal(o);U.toast('Texto copiado');}catch{U.toast('No pudimos copiar el texto.',true);}};o.querySelector('#reply-message').onclick=()=>{S.reply=m;U.closeModal(o);renderDraft();editor.focus();};o.querySelector('#pin-message')?.addEventListener('click',async()=>{const r=await sb.from('tnt_chat_messages').update({pinned:!m.pinned}).eq('id',id).select().single();if(r.error)return U.toast(err(r.error),true);U.closeModal(o);await loadMessages(false);});o.querySelector('#edit-message')?.addEventListener('click',()=>{editMessage(m);});o.querySelector('#delete-message')?.addEventListener('click',()=>{deleteMessage(m);});}
function editMessage(m){const o=U.modal('Editar mensaje',`<form class="tnt-form"><textarea aria-label="Mensaje" name="body" maxlength="10000">${U.esc(m.body)}</textarea><button class="tnt-button primary">Guardar cambios</button><p role="alert"></p></form>`),ed=TNTEditor.attach(o.querySelector('textarea'),{html:m.body_rich});o.querySelector('form').onsubmit=async e=>{e.preventDefault();const c=ed.get();if(!c.text.trim())return;const r=await sb.from('tnt_chat_messages').update({body:c.text.trim(),body_rich:c.html,edited_at:new Date().toISOString()}).eq('id',m.id).select().single();if(r.error)return o.querySelector('[role=alert]').textContent=err(r.error);U.closeModal(o);await loadMessages(false);};}
function deleteMessage(m){const o=U.modal('Eliminar mensaje','<p>El equipo verá que este mensaje fue eliminado.</p><button class="tnt-button" id="confirm-delete">Eliminar mensaje</button>');o.querySelector('#confirm-delete').onclick=async()=>{const r=await sb.from('tnt_chat_messages').update({deleted_at:new Date().toISOString(),pinned:false}).eq('id',m.id).select().single();if(r.error)return U.toast(err(r.error),true);U.closeModal(o);await loadMessages(false);await refreshOverview();};}
async function downloadFile(f){const url=await fileUrl(f),response=await fetch(url);if(!response.ok)throw Error('No pudimos descargar el archivo.');const blob=await response.blob(),objectUrl=URL.createObjectURL(blob),link=document.createElement('a');link.href=objectUrl;link.download=f.name||'archivo';document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(objectUrl),60000);}
async function attachment(id,index=0){const m=S.messages.find(x=>x.id===id);if(!m||m.deleted_at)return;const f=messageFiles(m)[index];if(!f)return;if(!f.type?.startsWith('image/')&&!f.type?.startsWith('video/')&&!isAudioFile(f)){try{await downloadFile(f);}catch(e){U.toast(err(e),true);}return;}const o=U.modal(isAudioFile(f)?'Mensaje de voz':f.name||'Archivo','<p id="file-loading">Preparando archivo…</p>');try{const url=await fileUrl(f);o.querySelector('#file-loading').outerHTML=`${f.type?.startsWith('image/')||/\.(png|jpg|jpeg|webp)$/i.test(f.name)?`<img class="chat-file-preview" src="${U.esc(url)}" alt="${U.esc(f.name)}">`:f.type?.startsWith('video/')?`<video class="chat-file-preview" controls playsinline src="${U.esc(url)}"></video>`:audioWidget(url,'Mensaje de voz')}<button class="tnt-button primary" id="download-media" type="button">${U.icon('download')} Descargar</button>`;o.querySelector('#download-media').onclick=async()=>{try{await downloadFile(f);}catch(e){U.toast(err(e),true);}};bindAudioWidgets(o);}catch(e){o.querySelector('#file-loading').textContent=err(e);}}
function showParticipants(mention=false){const ids=roster(thread());const o=U.modal(mention?'Mencionar participante':'Participantes',`<p>${U.esc(type(thread()))}. Los avatares identifican al equipo de esta conversación.</p>${ids.map(id=>`<div class="chat-participant">${U.avatar(person(id),account(id))}<div><b>${U.esc(name(id))}${id===me()?' · Vos':''}</b><small>${U.esc(account(id).ministry_role||'Participante')}</small></div>${mention?`<button class="tnt-button" data-mention-person="${id}">Mencionar</button>`:''}</div>`).join('')||'<p>Los participantes aparecerán al sumarse a la conversación.</p>'}`);o.querySelectorAll('[data-mention-person]').forEach(b=>b.onclick=()=>{const i=$('#chat-text');editor.set(editor.get().text+' @'+name(b.dataset.mentionPerson)+' ');U.closeModal(o);editor.focus();resizeInput();});}
function showPerson(id){U.modal(name(id),`<div class="chat-participant">${U.avatar(person(id),account(id))}<div><b>${U.esc(account(id).ministry_role||'Equipo TNT')}</b><small>${U.esc(account(id).bio||'Parte del equipo TNT')}</small></div></div><a class="tnt-button" href="/organizacion/?person=${encodeURIComponent(id)}">Ver responsabilidades</a>`);}
function showReaders(id){const m=S.messages.find(x=>x.id===id);if(!m)return;const readers=S.members.filter(x=>x.thread_id===S.active&&x.person_id!==me()&&x.last_read_at>=m.created_at&&(!m.audience_person_ids||m.audience_person_ids.includes(x.person_id)));U.modal('Visto por',readers.map(x=>`<div class="chat-participant">${U.avatar(person(x.person_id),account(x.person_id))}<div><b>${U.esc(name(x.person_id))}</b></div></div>`).join('')||'<p>Todavía no hay lecturas registradas.</p>');}
function chooseAudience(){
 if(!TNT.isAdmin||!S.active)return;
 const room=thread(),eligible=new Set(roster(room).filter(id=>id!==me()&&S.accounts.some(a=>a.person_id===id&&a.enabled&&(a.staff_status==='approved'||a.system_role==='admin')&&a.auth_user_id)));
 const groups=[
  ...S.groups.filter(g=>room.thread_type==='general'||room.event_id===g.event_id).map(g=>({label:g.name,ids:S.groupMembers.filter(m=>m.group_id===g.id).map(m=>m.person_id).filter(id=>eligible.has(id))})),
  ...S.efeGroups.filter(g=>room.thread_type==='general'||room.module==='efe'&&room.scope===g.code).map(g=>({label:'EFE · '+g.name,ids:S.efeMembers.filter(m=>m.group_id===g.id&&m.active).map(m=>m.person_id).filter(id=>eligible.has(id))}))
 ].filter(g=>g.ids.length);
 const o=U.modal('Destinatarios del mensaje',`<p>Solo las personas elegidas podrán leer este mensaje y abrir sus archivos. La selección se aplica a este envío.</p><div class="chat-audience-list"><button type="button" class="tnt-button" id="audience-all">Todo el chat</button>${groups.map((g,i)=>`<button type="button" class="tnt-button" data-audience-group="${i}"><b>${U.esc(g.label)}</b><small>${g.ids.length} ${g.ids.length===1?'persona':'personas'}</small></button>`).join('')}</div><form class="tnt-form" id="audience-people"><h3>Elegir personas</h3><div class="chat-audience-people">${[...eligible].map(id=>`<label><input type="checkbox" name="person" value="${id}" ${S.audience?.ids.includes(id)?'checked':''}> ${U.esc(name(id))}</label>`).join('')||'<p>No hay otras cuentas habilitadas en esta conversación.</p>'}</div><button class="tnt-button primary" type="submit">Aplicar a este mensaje</button><p role="alert"></p></form>`);
 const select=(label,ids)=>{S.audience=ids.length?{label,ids:[...new Set(ids)]}:null;U.closeModal(o);renderDraft();persistDraft();};
 o.querySelector('#audience-all').onclick=()=>select('',[]);
 o.querySelectorAll('[data-audience-group]').forEach(b=>b.onclick=()=>{const g=groups[Number(b.dataset.audienceGroup)];select(g.label,g.ids);});
 o.querySelector('#audience-people').onsubmit=e=>{e.preventDefault();const ids=[...o.querySelectorAll('[name=person]:checked')].map(x=>x.value);if(!ids.length){o.querySelector('[role=alert]').textContent='Elegí al menos una persona.';return;}select(ids.length===1?name(ids[0]):'Personas elegidas',ids);};
}
function newChat(){
 if(!canCreate())return U.toast('Solo administradores y responsables de tareas de eventos pueden crear conversaciones.',true);
 const d=today(),weekday=new Date(d+'T12:00:00Z').getUTCDay(),next=U.addDays(d,(6-weekday+7)%7),last=d===next?U.addDays(d,7):next;
 const active=S.threads.filter(t=>!t.is_archived),available=S.events.filter(e=>e.status!=='cancelled');
 const saturdays=TNT.isAdmin?available.filter(e=>e.kind==='saturday'&&e.start_date>=d&&e.start_date<=last&&!active.some(t=>t.thread_type==='event'&&t.event_id===e.id)):[];
 const events=TNT.isAdmin?available.filter(e=>e.kind!=='saturday'&&e.end_date>=d&&S.eventMembers.some(m=>m.event_id===e.id&&m.event_role==='organizer')&&!active.some(t=>t.thread_type==='event'&&t.event_id===e.id)):[];
 const tasks=S.tasks.filter(t=>{const e=available.find(x=>x.id===t.event_id);return t.task_type==='logistics'&&e&&e.kind!=='saturday'&&e.end_date>=d&&!active.some(c=>c.thread_type==='task'&&c.task_id===t.id)&&S.assignees.some(a=>a.task_id===t.id&&a.assignment_status!=='declined'&&account(a.person_id).enabled&&account(a.person_id).auth_user_id)&&(TNT.isAdmin||S.assignees.some(a=>a.task_id===t.id&&a.person_id===me()&&a.assignment_status!=='declined'));});
 const cards=[...(TNT.isAdmin&&!active.some(t=>t.thread_type==='general')?[{value:'general',title:'General TNT',subtitle:'Todo el equipo'}]:[]),...saturdays.map(e=>({value:'event|'+e.id,title:e.name,subtitle:'Sábado preparado · '+U.date(e.start_date+'T12:00:00-03:00')})),...events.map(e=>({value:'event|'+e.id,title:e.name,subtitle:'Encuentro · '+U.date(e.start_date+'T12:00:00-03:00')})),...tasks.map(t=>({value:'task|'+t.id,title:t.title,subtitle:'Equipo de '+(available.find(e=>e.id===t.event_id)?.name||'evento')}))];
 if(!cards.length)return U.toast('Primero prepará un sábado o evento en Organización y asigná un responsable a la tarea.');
 const o=U.modal('Nueva conversación',`<form class="tnt-form" id="create-thread"><p>La conversación se vincula al sábado, evento o área de trabajo preparada en Organización.</p><fieldset class="chat-context-picker"><legend>Elegí el contexto</legend>${cards.map((c,i)=>`<label><input type="radio" name="context" value="${c.value}" ${i===0?'checked':''}><span class="chat-context-card"><b>${U.esc(c.title)}</b><small>${U.esc(c.subtitle)}</small></span></label>`).join('')}</fieldset><label>Nombre de la conversación<input name="title" maxlength="100" minlength="3" required value="${U.esc(cards[0].title)}"></label><fieldset class="chat-invite-picker"><legend>Personas invitadas</legend><label><input type="radio" name="invite" value="all" checked> Todas las personas de este contexto</label><label><input type="radio" name="invite" value="selected"> Elegir una por una</label><div class="chat-member-picker" id="invite-people" hidden></div></fieldset><section class="chat-create-review" id="chat-review" aria-live="polite"></section><label><input type="checkbox" name="reviewed" required> Revisé el contexto, responsables e invitados</label><button class="tnt-button primary" type="submit">Crear conversación</button><p role="alert"></p></form>`);
 const form=o.querySelector('#create-thread'),picker=o.querySelector('#invite-people'),review=o.querySelector('#chat-review');
 const context=()=>{const [kind,id]=form.elements.context.value.split('|'),task=S.tasks.find(t=>t.id===id),event=available.find(e=>e.id===(kind==='task'?task?.event_id:id));return{kind,id,task,event};};
 function drawPeople(){const {kind,task,event}=context(),scope=event?.id,leaders=kind==='task'?S.assignees.filter(a=>a.task_id===task.id&&a.assignment_status!=='declined'&&account(a.person_id).enabled&&account(a.person_id).auth_user_id).map(a=>a.person_id):[],coordinators=S.eventMembers.filter(m=>m.event_id===scope&&m.event_role==='organizer'&&account(m.person_id).system_role!=='admin'&&account(m.person_id).enabled&&account(m.person_id).auth_user_id).map(m=>m.person_id),required=[...new Set([...leaders,...coordinators])];
  const previouslySelected=new Set([...picker.querySelectorAll('[name=person]:checked')].map(x=>x.value));const eligible=S.accounts.filter(a=>a.enabled&&(a.staff_status==='approved'||a.system_role==='admin')&&a.auth_user_id&&(kind==='general'||event?.kind==='saturday'||S.eventMembers.some(m=>m.event_id===scope&&m.person_id===a.person_id)||S.assignees.some(m=>m.person_id===a.person_id&&S.tasks.some(t=>t.id===m.task_id&&t.event_id===scope))));
  picker.innerHTML=eligible.map(a=>`<label><input type="checkbox" name="person" value="${a.person_id}" ${required.includes(a.person_id)?'checked disabled':previouslySelected.has(a.person_id)?'checked':''}>${U.avatar(person(a.person_id),a)}<span>${U.esc(name(a.person_id))}${required.includes(a.person_id)?' · Responsable':''}</span></label>`).join('');
  const selected=form.elements.invite.value==='selected';form.querySelector('.chat-invite-picker').hidden=kind==='general';picker.hidden=kind==='general'||!selected;
  const checked=selected?[...picker.querySelectorAll('[name=person]:checked')].map(x=>x.value):eligible.filter(a=>a.system_role!=='admin').map(a=>a.person_id),invited=new Set([...checked,...required]);
  review.innerHTML=`<h3>Antes de crear</h3><p><b>Conversación:</b> ${U.esc(form.elements.title.value.trim()||'Sin nombre')}</p><p><b>Origen:</b> ${U.esc(kind==='general'?'Todo TNT':event?.name||'Evento')} ${task?'· '+U.esc(task.title):''}</p><p><b>Encargados del área:</b> ${kind==='task'?leaders.map(id=>U.esc(name(id))).join(', '):'No corresponde a una tarea'}</p><p><b>Coordinadores:</b> ${coordinators.map(id=>U.esc(name(id))).join(', ')||'Sin coordinadores añadidos'}</p><p><b>Invitados:</b> ${[...invited].map(id=>U.esc(name(id))).join(', ')||'Ninguno'}</p><small>Los administradores pueden supervisar sin figurar como participantes. Solo aparecen si se los invita.</small>`;
  picker.querySelectorAll('[name=person]').forEach(x=>x.onchange=drawPeople);
 }
 form.querySelectorAll('[name=context]').forEach(r=>r.onchange=()=>{form.elements.title.value=cards.find(x=>x.value===r.value)?.title||'';form.elements.reviewed.checked=false;drawPeople();});form.querySelectorAll('[name=invite]').forEach(r=>r.onchange=()=>{form.elements.reviewed.checked=false;drawPeople();});form.elements.title.oninput=drawPeople;drawPeople();
 form.onsubmit=async e=>{e.preventDefault();const button=form.querySelector('[type=submit]'),{kind,id,task}=context(),title=form.elements.title.value.trim(),all=kind==='general'||form.elements.invite.value==='all',people=[...picker.querySelectorAll('[name=person]:checked')].map(x=>x.value);if(title.length<3||!form.elements.reviewed.checked)return;if(kind==='task'&&!S.assignees.some(a=>a.task_id===task?.id&&a.assignment_status!=='declined'&&account(a.person_id).enabled&&account(a.person_id).auth_user_id))return form.querySelector('[role=alert]').textContent='Asigná un encargado al área en Organización antes de crear este chat.';if(!all&&!people.length)return form.querySelector('[role=alert]').textContent='Elegí al menos una persona.';button.disabled=true;try{const r=await sb.rpc('tnt_create_chat',{p_title:title,p_general:kind==='general',p_event:kind==='event'?id:null,p_task:kind==='task'?id:null,p_all:all,p_people:all?[]:people});if(r.error)throw r.error;U.closeModal(o);await loadMeta();await open(r.data);}catch(ex){form.querySelector('[role=alert]').textContent=err(ex);button.disabled=false;}};
}
function bind(){
 $('#chat-search').oninput=renderThreads;$('#new-chat').onclick=newChat;$('#chat-composer').onsubmit=send;
 editor=TNTEditor.attach($('#chat-text'));editor.wrap.querySelector('.tnt-editor-tools').hidden=true;
 $('#chat-format').onclick=()=>{const toolbar=editor.wrap.querySelector('.tnt-editor-tools');toolbar.hidden=!toolbar.hidden;};
 $('#chat-bubble-color').onclick=chooseBubbleColor;
 $('#chat-audience')?.addEventListener('click',chooseAudience);
 $('#chat-attach').onclick=()=>{if(S.sending||S.recording)return;const o=U.modal('Adjuntar',`<div class="chat-attach-options"><button type="button" data-attach="photo">📷 <span><b>Fotos y videos</b><small>Elegí desde tu galería</small></span></button><button type="button" data-attach="camera">📸 <span><b>Cámara</b><small>Sacá una foto ahora</small></span></button><button type="button" data-attach="file">📄 <span><b>Documento o archivo</b><small>PDF, Word, planillas y más</small></span></button></div>`);o.querySelectorAll('[data-attach]').forEach(b=>b.onclick=()=>{const input=$('#chat-'+b.dataset.attach);U.closeModal(o);input.click();});};
 ['photo','camera','file'].forEach(kind=>$('#chat-'+kind).onchange=e=>{queueFiles([...e.target.files]);e.target.value='';});
 const voice=$('#chat-voice');let voiceTouch=false,voiceStart=null;
 const lockHint=$('#chat-voice-lock');
 const hideLock=()=>{lockHint.hidden=true;lockHint.classList.remove('is-locked');lockHint.style.removeProperty('--drag-y');};
 voice.onpointerdown=e=>{if(e.pointerType==='mouse')return;voiceTouch=true;voiceStart={x:e.clientX,y:e.clientY};$('#chat-compose-wrap').classList.add('gesture-held');lockHint.hidden=false;lockHint.classList.remove('is-locked');voice.setPointerCapture?.(e.pointerId);recordAudio();};
 voice.onpointermove=e=>{if(!voiceStart)return;const dx=e.clientX-voiceStart.x,dy=e.clientY-voiceStart.y;
   lockHint.style.setProperty('--drag-y',Math.max(-65,Math.min(0,dy))+'px');
   if(!S.recording)return;
   if(dy< -55){S.recording.locked=true;lockHint.classList.add('is-locked');$('#chat-record-status').classList.add('locked');}
   else if(dx< -80)S.recording.cancelOnRelease=true;
 };
 voice.onpointerup=e=>{if(!voiceStart)return;voiceStart=null;$('#chat-compose-wrap').classList.remove('gesture-held');hideLock();const recording=S.recording;if(!recording)return;
   if(recording.cancelOnRelease)cancelRecording();
   else if(!recording.locked)finishRecording(true);
 };
 voice.onpointercancel=()=>{voiceStart=null;$('#chat-compose-wrap').classList.remove('gesture-held');hideLock();cancelRecording();};
 voice.onclick=()=>{if(voiceTouch){voiceTouch=false;return;}if(!S.recording)recordAudio();};
 $('#chat-mention').onclick=()=>showParticipants(true);$('#chat-text').oninput=resizeInput;
 $('#chat-text').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing&&window.innerWidth>720){e.preventDefault();$('#chat-composer').requestSubmit();}};
 $('#chat-find').onclick=searchMessages;$('#chat-starred').onclick=showStarred;
}

function persistDraft(){if(!S.active||!editor)return;const c=editor.get();S.drafts[S.active]={text:c.text,rich:c.html,reply:S.reply,audience:S.audience,bubbleColor:S.bubbleColor,pendingMessageId:S.pendingMessageId,files:S.files,uploaded:S.uploaded};try{const safe=Object.fromEntries(Object.entries(S.drafts).map(([id,d])=>[id,{text:d.text,rich:d.rich,reply:d.reply,audience:d.audience,bubbleColor:d.bubbleColor,pendingMessageId:d.pendingMessageId}]));localStorage.setItem(draftKey(),JSON.stringify(safe));}catch{}}
const fileTypes={pdf:'application/pdf',txt:'text/plain',csv:'text/csv',zip:'application/zip',doc:'application/msword',docx:'application/vnd.openxmlformats-officedocument.wordprocessingml.document',xls:'application/vnd.ms-excel',xlsx:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',ppt:'application/vnd.ms-powerpoint',pptx:'application/vnd.openxmlformats-officedocument.presentationml.presentation',mp3:'audio/mpeg',m4a:'audio/mp4',webm:'audio/webm',ogg:'audio/ogg',mp4:'video/mp4',mov:'video/quicktime',jpg:'image/jpeg',jpeg:'image/jpeg',png:'image/png',webp:'image/webp',heic:'image/heic',heif:'image/heif'};
function fileType(f){return (f.type||fileTypes[f.name.split('.').pop().toLowerCase()]||'application/octet-stream').split(';')[0];}
function queueFiles(files){for(const f of files){if(S.files.length>=10){U.toast('Podés adjuntar hasta 10 archivos.',true);break;}if(f.size>10485760){U.toast(f.name+': el máximo es 10 MB.',true);continue;}if(!Object.values(fileTypes).includes(fileType(f))){U.toast(f.name+': este tipo de archivo no está admitido.',true);continue;}if(fileType(f).startsWith('audio/'))f.previewUrl=URL.createObjectURL(f);S.files.push(f);}renderDraft();}
function isAudioFile(f){return f.type?.startsWith('audio/')||(!f.type&&/^Audio-.*\.(webm|m4a|ogg|mp3)$/i.test(f.name||''));}
function messageFiles(m){return m.attachments?.length?m.attachments:m.attachment_url?[{path:m.attachment_url,name:m.attachment_name,type:''}]:[];}
function audioWidget(url,label,senderId,duration=0){const bars=[8,12,19,11,25,15,9,20,29,17,10,25,18,13,26,31,19,12,24,16,9,20,28,14,22,12,18,25,10,16];return `<div class="chat-audio" data-audio-duration="${Number(duration)||0}">${senderId?`<span class="chat-audio-avatar">${U.avatar(person(senderId),account(senderId))}<small>🎙</small></span>`:''}<button type="button" data-audio-toggle aria-label="Reproducir ${U.esc(label)}">▶</button><div class="chat-audio-track"><div class="chat-audio-wave"><span class="chat-audio-bars" aria-hidden="true">${bars.map(h=>`<i style="height:${h}px"></i>`).join('')}</span><input type="range" min="0" max="100" value="0" aria-label="Posición del audio"></div><time>0:00</time></div><audio preload="metadata" src="${U.esc(url)}"></audio></div>`;}
function bindAudioWidgets(root){root.querySelectorAll('.chat-audio').forEach(widget=>{const player=widget.querySelector('audio'),button=widget.querySelector('button'),range=widget.querySelector('input'),time=widget.querySelector('time'),clock=n=>Number.isFinite(n)?Math.floor(n/60)+':'+String(Math.floor(n%60)).padStart(2,'0'):'0:00';button.onclick=async()=>{if(player.paused){try{await player.play()}catch{U.toast('No pudimos reproducir este audio.',true);}}else player.pause();};player.onplay=()=>{button.textContent='Ⅱ';button.setAttribute('aria-label','Pausar audio');};player.onpause=()=>{button.textContent='▶';button.setAttribute('aria-label','Reproducir audio');};const update=()=>{const duration=Number.isFinite(player.duration)&&player.duration>0?player.duration:Number(widget.dataset.audioDuration)||0;range.value=duration?String(Math.round(player.currentTime/duration*100)):'0';time.textContent=clock(player.paused&&player.currentTime===0?duration:player.currentTime);widget.style.setProperty('--audio-progress',range.value+'%');};player.onloadedmetadata=update;player.ontimeupdate=update;player.onended=()=>{player.currentTime=0;update();};range.oninput=()=>{const duration=Number.isFinite(player.duration)&&player.duration>0?player.duration:Number(widget.dataset.audioDuration)||0;if(duration)player.currentTime=Number(range.value)/100*duration;};});}
const signedFiles=new Map();
async function fileUrl(f){const cached=signedFiles.get(f.path);if(cached&&cached.expires>Date.now())return cached.url;let url=f.path;if(url.startsWith('tnt-chat-files/')){const r=await sb.storage.from('tnt-chat-files').createSignedUrl(url.slice(15),600);if(r.error)throw r.error;url=r.data.signedUrl;}url=U.safeUrl(url);if(!url)throw Error('El enlace no es válido.');signedFiles.set(f.path,{url,expires:Date.now()+540000});return url;}
function hydrateAttachments(){$('#chat-messages').querySelectorAll('[data-media]').forEach(async el=>{const m=S.messages.find(x=>x.id===el.dataset.media),f=messageFiles(m)[Number(el.dataset.mediaIndex)];if(!f||!isAudioFile(f)&&!f.type?.startsWith('image/')&&!f.type?.startsWith('video/'))return;try{const url=await fileUrl(f);if(!el.isConnected)return;if(isAudioFile(f)){el.innerHTML=audioWidget(url,'Audio de '+name(m.person_id),m.person_id,f.duration_seconds)+`<button type="button" class="chat-audio-download" aria-label="Descargar mensaje de voz">${U.icon('download')}</button>`;el.querySelector('.chat-audio-download').onclick=async()=>{try{await downloadFile(f);}catch(e){U.toast(err(e),true);}};}else el.innerHTML=f.type.startsWith('video/')?`<video controls playsinline preload="metadata" src="${U.esc(url)}"></video>`:`<img loading="lazy" src="${U.esc(url)}" alt="${U.esc(f.name)}">`;bindAudioWidgets(el);if(f.type?.startsWith('image/'))el.onclick=()=>attachment(m.id,Number(el.dataset.mediaIndex));}catch{el.textContent='No se pudo cargar la vista previa.';}});}
function bindMessageGestures(){$('#chat-messages').querySelectorAll('[data-message-id]').forEach(el=>{let start=null,timer=null;el.onpointerdown=e=>{if(e.target.closest('button,a,audio,input')||e.pointerType==='mouse')return;start={x:e.clientX,y:e.clientY};timer=setTimeout(()=>{start=null;messageActions(el.dataset.messageId);},550);};el.onpointermove=e=>{if(!start)return;const x=e.clientX-start.x,y=e.clientY-start.y;if(Math.abs(x)>8||Math.abs(y)>8)clearTimeout(timer);if(x>12&&Math.abs(y)<25)el.style.transform=`translateX(${Math.min(x,65)}px)`;};el.onpointerup=e=>{clearTimeout(timer);el.style.transform='';if(start&&e.clientX-start.x>55&&Math.abs(e.clientY-start.y)<30){const m=S.messages.find(x=>x.id===el.dataset.messageId);if(m&&!m.deleted_at){S.reply=m;renderDraft();persistDraft();editor.focus();}}start=null;};el.onpointercancel=()=>{clearTimeout(timer);el.style.transform='';start=null;};});}
async function loadStars(){const r=await sb.from('tnt_favorites').select('*').eq('person_id',me()).eq('entity_type','message');if(!r.error)S.stars=r.data||[];}
async function toggleStar(m){const exists=S.stars.some(x=>x.entity_id===m.id);const r=exists?await sb.from('tnt_favorites').delete().eq('person_id',me()).eq('entity_type','message').eq('entity_id',m.id):await sb.from('tnt_favorites').insert({person_id:me(),entity_type:'message',entity_id:m.id,label:(m.body||'Archivo').slice(0,150),href:'/chat/?thread='+m.thread_id});if(r.error)return U.toast(err(r.error),true);await loadStars();renderMessages();U.toast(exists?'Quitado de destacados':'Guardado en tus destacados');}
function showStarred(){const o=U.modal('Tus mensajes destacados',S.stars.length?S.stars.map(x=>`<button class="tnt-button" data-star-id="${x.entity_id}" data-star-thread="${U.esc(x.href)}">★ ${U.esc(x.label)}</button>`).join(''):'<p>Todavía no destacaste mensajes.</p>');o.querySelectorAll('[data-star-id]').forEach(b=>b.onclick=async()=>{const r=await sb.from('tnt_chat_messages').select('*').eq('id',b.dataset.starId).single();if(r.error)return U.toast('El mensaje ya no está disponible.',true);showFound(r.data);});}
function showFound(m){U.modal(m.deleted_at?'Mensaje eliminado':name(m.person_id),`<p>${U.date(m.created_at)} · ${U.time(m.created_at)}</p><div class="tnt-rich">${m.deleted_at?'Este mensaje fue eliminado.':TNTEditor.render(m.body,m.body_rich)}</div><button class="tnt-button" id="found-open">Abrir conversación</button>`).querySelector('#found-open').onclick=async e=>{U.closeModal(e.target.closest('dialog'));await open(m.thread_id);};}
function searchMessages(){if(!S.active)return U.toast('Elegí una conversación primero.');const id=S.active,o=U.modal('Buscar en esta conversación','<form class="tnt-form"><input name="q" type="search" required placeholder="Buscar mensajes" aria-label="Buscar mensajes"><button class="tnt-button primary">Buscar</button><div id="found-results" role="status"></div></form>');o.querySelector('form').onsubmit=async e=>{e.preventDefault();const q=e.target.elements.q.value.trim();if(!q)return;const list=o.querySelector('#found-results');list.textContent='Buscando…';const r=await sb.from('tnt_chat_messages').select('*').eq('thread_id',id).is('deleted_at',null).ilike('body','%'+q.replace(/[\%_]/g,'\\$&')+'%').order('created_at',{ascending:false}).limit(80);if(r.error){list.textContent=err(r.error);return;}list.innerHTML=(r.data||[]).map(m=>`<button class="tnt-button" data-found="${m.id}">${U.esc(m.body?.slice(0,160))}</button>`).join('')||'No encontramos mensajes.';list.querySelectorAll('[data-found]').forEach(b=>b.onclick=()=>showFound(r.data.find(m=>m.id===b.dataset.found)));};}
async function recordAudio(){
 if(S.sending||S.recording)return;
 if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder)return U.toast('Este navegador no permite grabar. Podés adjuntar un archivo de audio.',true);
 const state={cancelled:false,locked:false,finishRequested:false,autoSend:false,cancelOnRelease:false,stream:null,recorder:null,chunks:[],timer:null,pausedAt:0,pausedMs:0,previewUrl:null};S.recording=state;
 try{state.stream=await navigator.mediaDevices.getUserMedia({audio:true});if(state.cancelled){state.stream.getTracks().forEach(t=>t.stop());if(S.recording===state)S.recording=null;return;}
 const mime=['audio/webm;codecs=opus','audio/mp4','audio/ogg;codecs=opus'].find(t=>MediaRecorder.isTypeSupported(t));state.recorder=new MediaRecorder(state.stream,mime?{mimeType:mime}:{});const started=Date.now();
 $('#chat-compose-wrap').classList.add('is-recording');
 $('#chat-record-status').innerHTML='<div class="chat-record-line"><span class="chat-record-dot" aria-hidden="true"></span><b id="record-time" role="timer">0:00</b><div class="chat-record-wave" aria-hidden="true"></div></div><div class="chat-record-preview" id="record-preview" hidden><button type="button" id="record-preview-play" aria-label="Escuchar grabación">▶</button><span>Escuchá antes de enviar</span><audio id="record-preview-audio" preload="metadata"></audio></div><div class="chat-record-actions"><button type="button" id="record-cancel" aria-label="Descartar audio">🗑</button><button type="button" id="record-pause" aria-label="Pausar grabación">Ⅱ <span>Pausar</span></button><button type="button" id="record-stop" aria-label="Enviar audio">➤</button></div><small class="chat-record-hint">Soltá para enviar · arriba para bloquear · izquierda para descartar</small>';
 $('#record-stop').onclick=()=>finishRecording(true);$('#record-cancel').onclick=cancelRecording;
 const clearPreview=()=>{const audio=$('#record-preview-audio');if(audio?.hasAttribute('src'))audio.pause();if(state.previewUrl){URL.revokeObjectURL(state.previewUrl);state.previewUrl=null;}if(audio)audio.removeAttribute('src');};
 const updatePreview=()=>{if(!state.chunks.length||state.recorder?.state!=='paused')return;clearPreview();state.previewUrl=URL.createObjectURL(new Blob(state.chunks,{type:state.recorder.mimeType}));const audio=$('#record-preview-audio'),button=$('#record-preview-play');audio.src=state.previewUrl;$('#record-preview').hidden=false;button.onclick=async()=>{if(audio.paused){try{await audio.play();button.textContent='Ⅱ';button.setAttribute('aria-label','Pausar reproducción');}catch{U.toast('No pudimos escuchar esta grabación.',true);}}else{audio.pause();button.textContent='▶';button.setAttribute('aria-label','Escuchar grabación');}};audio.onended=audio.onpause=()=>{button.textContent='▶';button.setAttribute('aria-label','Escuchar grabación');};};
 $('#record-pause').onclick=()=>{if(!state.recorder)return;const button=$('#record-pause');if(state.recorder.state==='recording'&&state.recorder.pause){state.recorder.pause();state.pausedAt=Date.now();button.innerHTML='▶ <span>Reanudar</span>';$('#chat-record-status').classList.add('paused');state.locked=true;try{state.recorder.requestData?.();}catch{}updatePreview();}else if(state.recorder.state==='paused'&&state.recorder.resume){clearPreview();$('#record-preview').hidden=true;state.recorder.resume();state.pausedMs+=Date.now()-state.pausedAt;state.pausedAt=0;button.innerHTML='Ⅱ <span>Pausar</span>';$('#chat-record-status').classList.remove('paused');}};
 state.recorder.ondataavailable=e=>{if(e.data.size){state.chunks.push(e.data);updatePreview();}};
 state.recorder.onstop=()=>{
   clearInterval(state.timer);clearPreview();state.stream.getTracks().forEach(t=>t.stop());$('#chat-record-status').innerHTML='';$('#chat-record-status').classList.remove('locked','paused');$('#chat-compose-wrap').classList.remove('is-recording');S.recording=null;
   if(!state.cancelled&&state.chunks.length){const type=state.recorder.mimeType.split(';')[0],ext=type.includes('mp4')?'m4a':type.includes('ogg')?'ogg':'webm';const file=new File(state.chunks,'Audio-'+new Date().toISOString().replace(/[:.]/g,'-')+'.'+ext,{type});file.durationSeconds=Math.max(1,Math.round(((state.pausedAt||Date.now())-started-state.pausedMs)/1000));queueFiles([file]);if(state.autoSend)send({preventDefault(){}});}
 };
 state.recorder.start();
 if(state.finishRequested){state.recorder.stop();return;}
 state.timer=setInterval(()=>{const seconds=Math.floor(((state.pausedAt||Date.now())-started-state.pausedMs)/1000);const clock=$('#record-time');if(clock)clock.textContent=Math.floor(seconds/60)+':'+String(seconds%60).padStart(2,'0');if(seconds>=180)finishRecording(false);},500);
 }catch(e){state.stream?.getTracks().forEach(t=>t.stop());S.recording=null;$('#chat-record-status').textContent='';$('#chat-compose-wrap').classList.remove('is-recording');U.toast(e.name==='NotAllowedError'?'Habilitá el micrófono en el navegador para mandar audios.':'No pudimos iniciar la grabación.',true);}
}
function finishRecording(autoSend=false){const r=S.recording;if(!r)return;r.autoSend=autoSend;r.finishRequested=true;if(r.recorder&&['recording','paused'].includes(r.recorder.state))r.recorder.stop();}
function cancelRecording(){const r=S.recording;if(!r)return;r.cancelled=true;if(r.previewUrl){URL.revokeObjectURL(r.previewUrl);r.previewUrl=null;}clearInterval(r.timer);$('#chat-compose-wrap').classList.remove('is-recording');$('#chat-record-status').innerHTML='';if(r.recorder&&['recording','paused'].includes(r.recorder.state))r.recorder.stop();else{r.stream?.getTracks().forEach(t=>t.stop());S.recording=null;}}

start();
})();
