const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');const {stripTypeScriptTypes}=require('node:module');
const original=fs.readFileSync(require('node:path').join(__dirname,'../supabase/functions/camp-notifications/index.ts'),'utf8');
function worker({authorized=true,notes={},states={},messages={},members=[],accounts=[],subscriptions=[],queue=[],resolved=false,expired=false}={}){
 let handler;const calls=[],delivered=[],updates=[],removed=[];
 class Query{constructor(t){this.t=t;this.filters=[];}select(){return this;}eq(k,v){this.filters.push([k,v]);return this;}update(v){this.value=v;return this;}delete(){this.remove=true;return this;}maybeSingle(){this.single=true;return this;}then(resolve,reject){return Promise.resolve().then(()=>{let rows=({tnt_notifications:Object.values(notes),tnt_notification_state:Object.values(states),tnt_chat_messages:Object.values(messages),tnt_chat_members:members,tnt_accounts:accounts,tnt_push_subscriptions:subscriptions}[this.t]||[]).filter(r=>this.filters.every(([k,v])=>r[k]===v));if(this.value)updates.push({table:this.t,filters:this.filters,value:this.value});if(this.remove)removed.push({table:this.t,filters:this.filters});return{data:this.single?rows[0]||null:rows,error:null};}).then(resolve,reject)}}
 const sb={from:t=>new Query(t),rpc:async(name,args)=>{calls.push({name,args});return{error:null,data:name==='tnt_worker_secret'?(args.p_name==='tnt_worker_dispatch'?'test-dispatch-secret':'test-vapid'):name==='tnt_claim_push'?queue:name==='tnt_camp_claim_outbox'?[]:name==='tnt_notification_resolved'?resolved:['tnt_notification_visible_for','tnt_recipient_has_module'].includes(name)?true:null};}};
 const code=stripTypeScriptTypes(original.replace(/^import .*;\n/gm,''));vm.runInNewContext(code,{createClient:()=>sb,webpush:{setVapidDetails(){},async sendNotification(sub,payload,options){if(expired)throw{statusCode:410};delivered.push({sub,payload:JSON.parse(payload),options});}},Deno:{env:{get:n=>({SUPABASE_URL:'https://test.invalid',SUPABASE_SERVICE_ROLE_KEY:'test-key'}[n]||'')},serve(fn){handler=fn;}},Response,URL,Date,JSON,fetch:()=>{throw Error('Este ensayo no envía emails.');}});
 return{run:()=>handler({headers:new Headers(authorized?{authorization:'Bearer test-dispatch-secret'}:{})}),calls,delivered,updates,removed};
}
const base=()=>({accounts:[{person_id:'person',enabled:true,staff_status:'approved'}],subscriptions:[{person_id:'person',endpoint:'endpoint',subscription:{endpoint:'endpoint'}}],queue:[{id:'outbox',person_id:'person',endpoint:'endpoint',attempts:1,payload:{notification_id:'note',title:'Aviso',url:'/organizacion/',tag:'tnt-notification-note'}}],notes:{note:{id:'note',person_id:'person'}}});
test('El worker rechaza una llamada sin autorización antes de reclamar o enviar avisos',async()=>{const w=worker({authorized:false});const r=await w.run();assert.equal(r.status,401);assert.equal(w.calls.length,1);assert.equal(w.delivered.length,0);});
test('El worker descarta avisos resueltos, leídos y eliminados',async()=>{for(const variant of [{resolved:true},{states:{one:{notification_id:'note',person_id:'person',read_at:'today'}}},{states:{one:{notification_id:'note',person_id:'person',dismissed_at:'today'}}}]){const w=worker({...base(),...variant});const r=await w.run();assert.equal((await r.json()).team_skipped,1);assert.equal(w.delivered.length,0);}});
test('El worker vuelve a comprobar destinatarios privados y cuentas deshabilitadas',async()=>{for(const disabled of [false,true]){const b=base();b.queue[0].payload={message_id:'message',url:'/chat/'};b.messages={message:{id:'message',thread_id:'thread',created_at:'2026-10-04T20:00Z',audience_person_ids:disabled?['person']:['another-person']}};b.members=[{thread_id:'thread',person_id:'person'}];b.accounts[0].enabled=!disabled;const w=worker(b);await w.run();assert.equal(w.delivered.length,0);assert(w.updates.some(u=>u.value.status==='skipped'));}});
test('Un aviso pendiente usa el destino TNT y el icono de dinamita',async()=>{const w=worker(base());const r=await w.run();assert.equal((await r.json()).team_sent,1);assert.equal(w.delivered.length,1);const p=w.delivered[0].payload;assert.equal(p.url,'https://trastornadores.vercel.app/organizacion/');assert.equal(p.icon,'https://trastornadores.vercel.app/icons/icon-192.png');assert.equal(p.badge,'https://trastornadores.vercel.app/icons/notification-badge.png');assert.equal(p.tag,'tnt-notification-note');});
test('El worker elimina una suscripción vencida y no envía enlaces externos',async()=>{let w=worker({...base(),expired:true});await w.run();assert(w.removed.some(x=>x.table==='tnt_push_subscriptions'));const b=base();b.queue[0].payload.url='https://external.invalid/';w=worker(b);await w.run();assert.equal(w.delivered.length,0);assert(w.updates.some(x=>x.value.status==='failed'));});
