(() => {
'use strict';
const U=TNTUI,sb=TNT.sb,app=document.getElementById('camp-app'),E=U.esc;
const S={editions:[],people:[],registrations:[],payments:[],resources:[],assignments:[],formFields:[],messages:[],camp:null,tab:'dashboard',query:'',filter:'all',loading:false};
const money=n=>new Intl.NumberFormat('es-AR',{style:'currency',currency:'ARS',maximumFractionDigits:0}).format(Number(n||0));
const statusLabel={pending:'Pendiente',confirmed:'Confirmada',cancelled:'Cancelada'};
const kindLabel={room:'Habitaciones',bus:'Transporte',team:'Equipos'};
const can=action=>TNT.isAdmin||!!TNT.canAction?.('campamento',action,'*');
const canHealth=()=>TNT.hasAccess('campamento-salud','*','view');
const canHealthEdit=()=>TNT.hasAccess('campamento-salud','*','edit');
const edition=()=>S.editions.find(c=>c.id===S.camp);
const person=id=>S.people.find(p=>p.id===id)||{};
const registration=id=>S.registrations.find(r=>r.id===id);
const active=()=>S.registrations.filter(r=>r.camp_id===S.camp&&!r.deleted_at&&r.status!=='cancelled');
const paid=id=>S.payments.filter(p=>p.registration_id===id&&!p.voided_at).reduce((n,p)=>n+Number(p.amount||0),0);
const balance=r=>Number(r.fee||0)-paid(r.id);
const age=p=>{if(!p?.birthday)return null;const d=new Date(p.birthday+'T12:00:00');const now=new Date();let a=now.getFullYear()-d.getFullYear();if(now.getMonth()<d.getMonth()||(now.getMonth()===d.getMonth()&&now.getDate()<d.getDate()))a--;return a};
const initials=n=>String(n||'?').trim().split(/\s+/).slice(0,2).map(x=>x[0]||'').join('').toUpperCase();
const field=(label,name,value='',type='text',extra='')=>`<label class="camp-field"><span>${E(label)}</span><input name="${name}" type="${type}" value="${E(value)}" ${extra}></label>`;
function modal(title,content,wide=false){return U.modal(title,content,wide)}
async function checked(q){const r=await q;if(r.error)throw r.error;return r.data}
async function formSave(o,fn){const form=o.querySelector('form'),btn=form?.querySelector('[type=submit]');if(btn?.disabled)return;if(btn)btn.disabled=true;try{await fn(new FormData(form));U.closeModal(o);await load();}catch(err){const a=o.querySelector('[role=alert]');if(a)a.textContent=err.message;else U.toast(err.message,true)}finally{if(btn)btn.disabled=false}}
function campFields(){return S.formFields.filter(x=>x.camp_id===S.camp&&x.active).sort((a,b)=>a.sort_order-b.sort_order)}
function resourceCount(id){return S.assignments.filter(a=>a.resource_id===id&&active().some(r=>r.id===a.registration_id)).length}
function assigned(regId,kind){const a=S.assignments.find(x=>x.registration_id===regId&&x.kind===kind);return S.resources.find(r=>r.id===a?.resource_id)}
function registrationHistory(personId){return S.registrations.filter(r=>r.person_id===personId&&!r.deleted_at).sort((a,b)=>(S.editions.find(e=>e.id===b.camp_id)?.start_date||'').localeCompare(S.editions.find(e=>e.id===a.camp_id)?.start_date||''))}
function phoneUrl(p){let n=String(p.phone||'').replace(/\D/g,'');if(!n)return'';if(n.startsWith('54'))n=n.slice(2);if(n.startsWith('9')&&n.length>10)n=n.slice(1);while(n.startsWith('0'))n=n.slice(1);if(n.length===10)n='549'+n;return n.length>=11?'https://wa.me/'+n:''}
async function load(){
 if(S.loading)return;S.loading=true;
 try{
  const tables=['tnt_camp_editions','tnt_people','tnt_camp_registrations','tnt_camp_payments','tnt_camp_resources','tnt_camp_assignments','tnt_camp_form_fields','tnt_camp_messages'];
  const [c,p,r,pay,res,a,ff,msg]=await Promise.all(tables.map(t=>checked(sb.from(t).select('*'))));
  S.editions=c.sort((a,b)=>b.start_date.localeCompare(a.start_date));S.people=p;S.registrations=r;S.payments=pay;S.resources=res;S.assignments=a;S.formFields=ff;S.messages=msg;
  if(!S.editions.some(c=>c.id===S.camp))S.camp=S.editions.find(c=>c.status==='open')?.id||S.editions[0]?.id||null;
  render();
 }catch(err){
  app.innerHTML=`<div class="tnt-error"><b>No pudimos cargar Campamento.</b><p>${E(err.message)}</p><button class="tnt-button" id="camp-retry">Reintentar</button></div>`;
  app.querySelector('#camp-retry').onclick=load;
 }finally{S.loading=false}
}
function navItems(){
 const rows=[['dashboard','Inicio'],['registrations','Inscripciones'],['people','Personas'],['payments','Pagos'],['rooms','Habitaciones'],['buses','Transporte'],['teams','Equipos'],['checkin','Check-in'],['communications','Mensajes'],['form','Formulario'],['mine','Mi ficha'],['trash','Papelera']];
 return rows.filter(([id])=>{
   if(id==='payments')return can('payments')||TNT.isAdmin;
   if(['rooms','buses','teams'].includes(id))return can('logistics')||TNT.hasAccess('campamento','*','view');
   if(id==='checkin')return can('checkin')||TNT.hasAccess('campamento','*','view');
   if(id==='communications')return can('communications')||TNT.hasAccess('campamento','*','view');
   if(id==='form')return can('form')||TNT.hasAccess('campamento','*','view');
   return true;
 });
}
function render(){
 const c=edition();
 if(!c){
  app.innerHTML=`<header class="camp-topbar"><a href="/" class="camp-back">←</a><div><span class="camp-eyebrow">TNT</span><h1>Campamento</h1></div></header><section class="camp-empty-state"><div>🏕️</div><h2>Creá la primera edición</h2><p>Campamento guarda personas, pagos, salud, habitaciones, transporte, equipos y check-in por edición.</p>${can('manage_editions')?'<button class="tnt-button primary" id="new-edition">Nueva edición</button>':''}</section>`;
  app.querySelector('#new-edition')?.addEventListener('click',()=>editEdition());
  return;
 }
 const regs=active(),received=regs.reduce((n,r)=>n+paid(r.id),0),due=regs.reduce((n,r)=>n+Math.max(0,balance(r)),0),capacity=Math.max(1,Number(c.capacity)||1),pct=Math.min(100,Math.round(regs.length/capacity*100));
 app.innerHTML=`<div class="camp-shell">
  <header class="camp-topbar">
   <a href="/" class="camp-back">←</a>
   <div class="camp-brand"><span class="camp-eyebrow">TNT · CAMPAMENTO</span><h1>${E(c.name)}</h1><p>${U.date(c.start_date+'T12:00:00-03:00',{day:'numeric',month:'short'})} – ${U.date(c.end_date+'T12:00:00-03:00',{day:'numeric',month:'short',year:'numeric'})} · ${E(c.location||'Lugar a confirmar')}</p></div>
   <div class="camp-top-actions">${can('manage_editions')?'<button class="camp-icon-btn" id="edit-edition" title="Configurar edición">⚙</button>':''}</div>
  </header>
  <section class="camp-edition-switch">
    <label><span>Edición</span><select id="camp-edition">${S.editions.map(x=>`<option value="${x.id}" ${x.id===S.camp?'selected':''}>${E(x.name)}${x.status==='archived'?' · Archivada':''}</option>`).join('')}</select></label>
    ${can('manage_editions')?'<button class="tnt-button" id="duplicate-edition">Duplicar edición</button><button class="tnt-button primary" id="new-edition">+ Nueva</button>':''}
  </section>
  <section class="camp-hero">
    <div><span class="camp-status ${E(c.status)}">${E({planning:'En preparación',open:'Inscripciones abiertas',closed:'Inscripciones cerradas',archived:'Archivada'}[c.status]||c.status)}</span><h2>${regs.length} personas inscriptas</h2><p>${pct}% del cupo · ${Math.max(0,capacity-regs.length)} lugares disponibles</p></div>
    <div class="camp-capacity-ring" style="--p:${pct}"><b>${regs.length}</b><small>/ ${capacity}</small></div>
  </section>
  <section class="camp-kpis">
   <button data-go="registrations"><small>Inscripciones</small><b>${regs.length}</b><span>${regs.filter(r=>r.status==='pending').length} pendientes</span></button>
   <button data-go="payments"><small>Recibido</small><b>${money(received)}</b><span>Saldo ${money(due)}</span></button>
   <button data-go="checkin"><small>En el predio</small><b>${regs.filter(r=>r.checked_in_at&&!r.checked_out_at).length}</b><span>${regs.filter(r=>!r.checked_in_at).length} sin ingresar</span></button>
   <button data-go="people"><small>Documentación</small><b>${regs.filter(r=>r.authorization).length}/${regs.length}</b><span>${regs.filter(r=>!r.authorization).length} pendientes</span></button>
  </section>
  <nav class="camp-nav">${navItems().map(([id,label])=>`<button data-tab="${id}" class="${S.tab===id?'on':''}">${label}</button>`).join('')}</nav>
  <main id="camp-view"></main>
 </div>`;
 app.querySelector('#camp-edition').onchange=e=>{S.camp=e.target.value;S.tab='dashboard';render()};
 app.querySelector('#edit-edition')?.addEventListener('click',()=>editEdition(c));
 app.querySelector('#new-edition')?.addEventListener('click',()=>editEdition());
 app.querySelector('#duplicate-edition')?.addEventListener('click',()=>duplicateEdition(c));
 app.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{S.tab=b.dataset.tab;S.query='';S.filter='all';renderView()});
 app.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>{if(navItems().some(x=>x[0]===b.dataset.go)){S.tab=b.dataset.go;render()}});
 renderView();
}
function renderView(){
 const view=app.querySelector('#camp-view');if(!view)return;
 if(S.tab==='dashboard')return renderDashboard(view);
 if(S.tab==='registrations')return renderRegistrations(view,false);
 if(S.tab==='people')return renderPeople(view);
 if(S.tab==='payments')return renderPayments(view);
 if(S.tab==='rooms')return renderResources(view,'room');
 if(S.tab==='buses')return renderResources(view,'bus');
 if(S.tab==='teams')return renderResources(view,'team');
 if(S.tab==='checkin')return renderCheckin(view);
 if(S.tab==='communications')return renderCommunications(view);
 if(S.tab==='form')return renderFormBuilder(view);
 if(S.tab==='mine')return renderMine(view);
 if(S.tab==='trash')return renderRegistrations(view,true);
}
function renderDashboard(view){
 const regs=active(),c=edition(),unassigned=kind=>regs.filter(r=>!S.assignments.some(a=>a.registration_id===r.id&&a.kind===kind)).length,recent=S.payments.filter(p=>regs.some(r=>r.id===p.registration_id)).sort((a,b)=>b.paid_at.localeCompare(a.paid_at)).slice(0,5);
 const alerts=[];
 if(regs.length>=Number(c.capacity))alerts.push('El cupo está completo.');
 if(regs.some(r=>!r.authorization))alerts.push(regs.filter(r=>!r.authorization).length+' autorizaciones pendientes.');
 if(unassigned('room'))alerts.push(unassigned('room')+' personas sin habitación.');
 if(unassigned('bus'))alerts.push(unassigned('bus')+' personas sin transporte.');
 view.innerHTML=`<section class="camp-dashboard-grid">
   <article class="camp-panel camp-actions-panel"><span class="camp-eyebrow">ACCESOS RÁPIDOS</span><h2>Organizá la edición</h2><div class="camp-quick-grid">
    ${can('registrations')?'<button data-dash="new-reg"><b>＋</b><span>Inscribir persona</span></button>':''}
    ${can('payments')?'<button data-dash="payments"><b>$</b><span>Registrar pago</span></button>':''}
    ${can('checkin')?'<button data-dash="checkin"><b>✓</b><span>Check-in</span></button>':''}
    ${can('logistics')?'<button data-dash="logistics"><b>▦</b><span>Distribuir lugares</span></button>':''}
    ${can('registrations')?'<button data-dash="import"><b>⇧</b><span>Importar fichas</span></button>':''}
    ${can('communications')?'<button data-dash="message"><b>✉</b><span>Nuevo mensaje</span></button>':''}
   </div></article>
   <article class="camp-panel"><span class="camp-eyebrow">PENDIENTES</span><h2>Para revisar</h2><div class="camp-alert-list">${alerts.map(x=>`<div><span>!</span><p>${E(x)}</p></div>`).join('')||'<div class="ok"><span>✓</span><p>No hay alertas importantes.</p></div>'}</div></article>
  </section>
  <section class="camp-section-head"><div><span class="camp-eyebrow">LOGÍSTICA</span><h2>Distribución</h2></div></section>
  <div class="camp-resource-summary">${['room','bus','team'].map(k=>{const rs=S.resources.filter(r=>r.camp_id===S.camp&&r.kind===k),assignedCount=regs.length-unassigned(k),cap=rs.reduce((n,r)=>n+Number(r.capacity||0),0);return`<button data-open-resource="${k}"><span>${{room:'🛏',bus:'🚌',team:'⚑'}[k]}</span><div><b>${kindLabel[k]}</b><small>${assignedCount}/${regs.length} asignados · ${cap} lugares</small></div><i>›</i></button>`}).join('')}</div>
  <section class="camp-section-head"><div><span class="camp-eyebrow">ÚLTIMOS MOVIMIENTOS</span><h2>Pagos recientes</h2></div></section>
  <div class="camp-list">${recent.map(p=>{const r=registration(p.registration_id);return`<article class="camp-list-row"><div class="camp-person-avatar">${initials(person(r?.person_id).full_name)}</div><div><b>${E(person(r?.person_id).full_name||'Persona')}</b><small>${U.date(p.paid_at)} · ${p.voided_at?'Anulado':E({cash:'Efectivo',transfer:'Transferencia',other:'Otro'}[p.method]||'Otro')}</small></div><strong>${money(p.amount)}</strong></article>`}).join('')||'<div class="camp-empty">Todavía no hay pagos.</div>'}</div>`;
 view.querySelector('[data-dash=new-reg]')?.addEventListener('click',()=>editRegistration());
 view.querySelector('[data-dash=payments]')?.addEventListener('click',()=>{S.tab='payments';render()});
 view.querySelector('[data-dash=checkin]')?.addEventListener('click',()=>{S.tab='checkin';render()});
 view.querySelector('[data-dash=logistics]')?.addEventListener('click',()=>{S.tab='rooms';render()});
 view.querySelector('[data-dash=import]')?.addEventListener('click',importCamp);
 view.querySelector('[data-dash=message]')?.addEventListener('click',()=>messageForm());
 view.querySelectorAll('[data-open-resource]').forEach(b=>b.onclick=()=>{S.tab={room:'rooms',bus:'buses',team:'teams'}[b.dataset.openResource];render()});
}
function registrationCard(r){
 const p=person(r.person_id),bal=balance(r),room=assigned(r.id,'room'),bus=assigned(r.id,'bus'),team=assigned(r.id,'team');
 return `<article class="camp-reg-card" data-open="${r.id}"><div class="camp-reg-top"><div class="camp-person-avatar">${initials(p.full_name)}</div><div><h3>${E(p.full_name)}</h3><p>${age(p)??'—'} años · ${E(r.document_no?'DNI '+r.document_no:'Sin DNI')}</p></div><span class="camp-reg-status ${r.status}">${statusLabel[r.status]||r.status}</span></div><div class="camp-reg-chips"><span>${r.authorization?'✓ Autorización':'! Autorización'}</span><span>${bal>0?'Debe '+money(bal):bal<0?'A favor '+money(-bal):'Pagado'}</span></div><div class="camp-reg-logistics"><small>🛏 ${E(room?.name||'Sin habitación')}</small><small>🚌 ${E(bus?.name||'Sin transporte')}</small><small>⚑ ${E(team?.name||'Sin equipo')}</small></div></article>`;
}
function renderRegistrations(view,trash=false){
 const base=S.registrations.filter(r=>r.camp_id===S.camp&&(trash?!!r.deleted_at:!r.deleted_at));
 view.innerHTML=`<section class="camp-section-head"><div><span class="camp-eyebrow">${trash?'RECUPERACIÓN':'INSCRIPCIONES'}</span><h2>${trash?'Papelera':'Personas inscriptas'}</h2><p>${trash?'Las fichas conservan pagos e historial.':'Buscá, filtrá y abrí cualquier ficha.'}</p></div>${!trash&&can('registrations')?'<div class="camp-head-actions"><button class="tnt-button" id="import-camp">Importar</button><button class="tnt-button primary" id="new-registration">+ Inscribir</button></div>':''}</section><div class="camp-filterbar"><input id="camp-search" type="search" placeholder="Buscar nombre, DNI o teléfono"><select id="camp-filter"><option value="all">Todas</option><option value="pending">Pendientes</option><option value="confirmed">Confirmadas</option><option value="debt">Con saldo</option><option value="missing_auth">Sin autorización</option></select></div><div id="camp-reg-list" class="camp-reg-grid"></div>`;
 const paint=()=>{const q=(view.querySelector('#camp-search').value||'').toLowerCase(),filter=view.querySelector('#camp-filter').value;const rows=base.filter(r=>{const p=person(r.person_id),hay=(p.full_name+' '+(p.phone||'')+' '+r.document_no).toLowerCase().includes(q),ok=filter==='all'||filter==='debt'&&balance(r)>0||filter==='missing_auth'&&!r.authorization||r.status===filter;return hay&&ok});view.querySelector('#camp-reg-list').innerHTML=rows.map(r=>trash?`<article class="camp-reg-card"><div class="camp-reg-top"><div class="camp-person-avatar">${initials(person(r.person_id).full_name)}</div><div><h3>${E(person(r.person_id).full_name)}</h3><p>Archivada en esta edición</p></div></div>${can('registrations')?`<button class="tnt-button" data-restore="${r.id}">Restaurar ficha</button>`:''}</article>`:registrationCard(r)).join('')||'<div class="camp-empty">No hay fichas para este filtro.</div>';view.querySelectorAll('[data-open]').forEach(x=>x.onclick=()=>showRegistration(x.dataset.open));view.querySelectorAll('[data-restore]').forEach(x=>x.onclick=()=>restoreRegistration(x.dataset.restore));};
 view.querySelector('#camp-search').oninput=paint;view.querySelector('#camp-filter').onchange=paint;view.querySelector('#new-registration')?.addEventListener('click',()=>editRegistration());view.querySelector('#import-camp')?.addEventListener('click',importCamp);paint();
}
function renderPeople(view){
 const rows=S.people.filter(p=>p.active!==false&&registrationHistory(p.id).length);
 view.innerHTML=`<section class="camp-section-head"><div><span class="camp-eyebrow">BASE CENTRAL</span><h2>Personas de Campamento</h2><p>Una misma persona conserva su historial entre ediciones.</p></div><a class="tnt-button" href="/perfiles/datos/">Abrir Perfiles</a></section><div class="camp-filterbar"><input id="people-search" type="search" placeholder="Buscar persona"></div><div id="camp-people" class="camp-list"></div>`;
 const paint=()=>{const q=(view.querySelector('#people-search').value||'').toLowerCase();view.querySelector('#camp-people').innerHTML=rows.filter(p=>(p.full_name+' '+(p.phone||'')).toLowerCase().includes(q)).map(p=>{const hist=registrationHistory(p.id),current=hist.find(r=>r.camp_id===S.camp);return`<article class="camp-list-row"><div class="camp-person-avatar">${initials(p.full_name)}</div><div><b>${E(p.full_name)}</b><small>${hist.length} ${hist.length===1?'campamento':'campamentos'} · ${E(p.phone||'Sin teléfono')}</small></div>${current?`<button class="tnt-button" data-open-person-reg="${current.id}">Ficha actual</button>`:'<span class="camp-muted">No inscripto/a este año</span>'}</article>`}).join('')||'<div class="camp-empty">Sin resultados.</div>';view.querySelectorAll('[data-open-person-reg]').forEach(b=>b.onclick=()=>showRegistration(b.dataset.openPersonReg));};
 view.querySelector('#people-search').oninput=paint;paint();
}
function customFieldMarkup(f,value=''){
 const req=f.required?' required':'';
 if(f.field_type==='textarea')return `<label class="camp-field"><span>${E(f.label)}${f.required?' *':''}</span><textarea name="custom_${f.id}"${req}>${E(value||'')}</textarea></label>`;
 if(f.field_type==='select'){const opts=Array.isArray(f.options)?f.options:[];return`<label class="camp-field"><span>${E(f.label)}${f.required?' *':''}</span><select name="custom_${f.id}"${req}><option value="">Elegir</option>${opts.map(o=>`<option value="${E(o)}" ${String(value)===String(o)?'selected':''}>${E(o)}</option>`).join('')}</select></label>`}
 if(f.field_type==='checkbox')return `<label class="camp-check"><input type="checkbox" name="custom_${f.id}" ${value?'checked':''}> <span>${E(f.label)}</span></label>`;
 return `<label class="camp-field"><span>${E(f.label)}${f.required?' *':''}</span><input type="${f.field_type==='number'?'number':f.field_type==='date'?'date':'text'}" name="custom_${f.id}" value="${E(value||'')}"${req}></label>`;
}
function editRegistration(r=null){
 if(!can('registrations'))return U.toast('No tenés permiso para editar inscripciones.',true);
 let p=r?person(r.person_id):{},chosen=p.id||null,id=r?.id||crypto.randomUUID(),c=edition(),fields=campFields(),answers=r?.answers||{};
 const available=S.people.filter(x=>x.active!==false&&!S.registrations.some(reg=>reg.camp_id===c.id&&reg.person_id===x.id&&!reg.deleted_at&&reg.id!==r?.id));
 const o=modal(r?'Editar inscripción':'Inscribir persona',`<form class="camp-form">${!r?`<label class="camp-field"><span>Buscar en Perfiles</span><select name="existing"><option value="">Crear perfil central nuevo</option>${available.map(x=>`<option value="${x.id}">${E(x.full_name)}</option>`).join('')}</select><small>Campamento usa la misma base de Perfiles, EFE y Sábados.</small></label>`:''}<div class="camp-form-grid">${field('Nombre completo','full_name',p.full_name||'','text','required maxlength="150"')}${field('Fecha de nacimiento','birthday',p.birthday||'','date')}</div><div class="camp-form-grid">${field('Teléfono / WhatsApp','phone',p.phone||'','tel')}${field('Documento','document_no',r?.document_no||'')}</div>${field('Congregación','congregation',r?.congregation||'')}<div class="camp-form-grid">${field('Importe de esta inscripción','fee',r?.fee??c.fee,'number','min="0" step="0.01" required')}<label class="camp-field"><span>Estado</span><select name="status">${Object.entries(statusLabel).map(([v,l])=>`<option value="${v}" ${r?.status===v?'selected':''}>${l}</option>`).join('')}</select></label></div><label class="camp-check"><input name="authorization" type="checkbox" ${r?.authorization?'checked':''}> <span>Autorización / documentación recibida</span></label>${fields.length?`<div class="camp-form-divider"><span>Formulario de esta edición</span></div>${fields.map(f=>customFieldMarkup(f,answers[f.field_key])).join('')}`:''}<label class="camp-field"><span>Notas de organización</span><textarea name="notes">${E(r?.notes||'')}</textarea></label><button class="tnt-button primary" type="submit">Guardar inscripción</button><div role="alert"></div></form>`,true);
 o.querySelector('[name=existing]')?.addEventListener('change',ev=>{chosen=ev.target.value||null;p=person(chosen);for(const key of ['full_name','birthday','phone']){const el=o.querySelector(`[name=${key}]`);if(el)el.value=p[key]||''}});
 o.querySelector('form').onsubmit=ev=>{ev.preventDefault();formSave(o,async fd=>{const name=String(fd.get('full_name')).trim();if(!chosen){const same=S.people.find(x=>x.full_name.toLowerCase().trim()===name.toLowerCase().trim());if(same)chosen=same.id}const custom={};fields.forEach(f=>{custom[f.field_key]=f.field_type==='checkbox'?fd.has('custom_'+f.id):(fd.get('custom_'+f.id)||'')});await checked(sb.rpc('tnt_save_camp_registration',{p_id:id,p_camp:c.id,p_person:chosen,p_person_values:{full_name:name,birthday:fd.get('birthday')||null,phone:fd.get('phone')||null,sex:p.sex||'U'},p_values:{document_no:fd.get('document_no')||'',congregation:fd.get('congregation')||'',fee:Number(fd.get('fee')),status:fd.get('status'),authorization:fd.has('authorization'),notes:fd.get('notes')||'',answers:custom}}));})};
}
function showRegistration(id){
 const r=registration(id),p=person(r?.person_id);if(!r||!p)return;const bal=balance(r),payments=S.payments.filter(x=>x.registration_id===id).sort((a,b)=>b.paid_at.localeCompare(a.paid_at)),history=registrationHistory(p.id);
 const o=modal(p.full_name,`<div class="camp-detail-head"><div class="camp-person-avatar big">${initials(p.full_name)}</div><div><span class="camp-reg-status ${r.status}">${statusLabel[r.status]}</span><h2>${E(p.full_name)}</h2><p>${age(p)??'—'} años · ${E(p.phone||'Sin teléfono')} · ${E(r.document_no||'Sin DNI')}</p></div></div><div class="camp-detail-grid"><div class="camp-metric"><small>Inscripción</small><b>${money(r.fee)}</b></div><div class="camp-metric"><small>${bal<0?'Saldo a favor':'Saldo pendiente'}</small><b>${money(Math.abs(bal))}</b></div><div class="camp-metric"><small>Documentación</small><b>${r.authorization?'Completa':'Pendiente'}</b></div></div><div class="camp-detail-actions">${can('registrations')?'<button class="tnt-button" id="edit-reg">Editar</button><button class="tnt-button danger" id="delete-reg">Papelera</button>':''}${can('payments')?'<button class="tnt-button primary" id="pay-reg">Registrar pago</button>':''}${canHealth()||p.id===TNT.person.id?'<button class="tnt-button" id="health-reg">Salud</button>':''}${phoneUrl(p)?`<a class="tnt-button" href="${phoneUrl(p)}" target="_blank" rel="noopener">WhatsApp</a>`:''}</div><section class="camp-detail-section"><h3>Datos y notas</h3><p>${E(r.congregation||'Sin congregación')}<br>${E(r.notes||'Sin notas')}</p>${campFields().map(f=>r.answers?.[f.field_key]!==undefined&&r.answers?.[f.field_key]!==''?`<div class="camp-answer"><span>${E(f.label)}</span><b>${E(String(r.answers[f.field_key]===true?'Sí':r.answers[f.field_key]===false?'No':r.answers[f.field_key]))}</b></div>`:'').join('')}</section><section class="camp-detail-section"><h3>Pagos</h3><div class="camp-list">${payments.map(x=>`<article class="camp-list-row"><div><b>${money(x.amount)} ${x.voided_at?'· Anulado':''}</b><small>${U.date(x.paid_at)} · ${x.method==='cash'?'Efectivo':x.method==='transfer'?'Transferencia':'Otro'} · ${E(x.reference)}</small></div>${can('payments')&&!x.voided_at?`<button class="tnt-button danger" data-void="${x.id}">Anular</button>`:''}</article>`).join('')||'<div class="camp-empty compact">Sin pagos.</div>'}</div></section><section class="camp-detail-section"><h3>Logística</h3>${['room','bus','team'].map(k=>{const res=assigned(r.id,k);return`<div class="camp-list-row"><div><b>${{room:'Habitación',bus:'Transporte',team:'Equipo'}[k]}</b><small>${E(res?.name||'Sin asignar')}</small></div>${can('logistics')?`<button class="tnt-button" data-assign="${k}">Cambiar</button>`:''}</div>`}).join('')}</section><section class="camp-detail-section"><h3>Historial de campamentos</h3>${history.map(h=>{const ed=S.editions.find(e=>e.id===h.camp_id);return`<div class="camp-history-row"><b>${E(ed?.name||'Edición')}</b><span>${statusLabel[h.status]||h.status} · ${money(h.fee)}</span></div>`}).join('')}</section>`,true);
 o.querySelector('#edit-reg')?.addEventListener('click',()=>editRegistration(r));o.querySelector('#pay-reg')?.addEventListener('click',()=>paymentForm(r));o.querySelector('#delete-reg')?.addEventListener('click',()=>deleteRegistration(r));o.querySelector('#health-reg')?.addEventListener('click',()=>healthForm(r));o.querySelectorAll('[data-void]').forEach(b=>b.onclick=()=>voidPayment(b.dataset.void));o.querySelectorAll('[data-assign]').forEach(b=>b.onclick=()=>assignResource(r,b.dataset.assign));
}
function paymentForm(r){
 if(!can('payments'))return U.toast('No tenés permiso para registrar pagos.',true);
 const id=crypto.randomUUID(),o=modal('Registrar pago · '+person(r.person_id).full_name,`<form class="camp-form">${field('Importe recibido','amount','','number','min="0.01" step="0.01" required')}<label class="camp-field"><span>Medio de pago</span><select name="method"><option value="cash">Efectivo</option><option value="transfer">Transferencia</option><option value="other">Otro</option></select></label>${field('Referencia / comprobante','reference')}<div class="camp-note">Saldo actual: <b>${money(balance(r))}</b>. Si el pago lo supera, queda saldo a favor.</div><button type="submit" class="tnt-button primary">Registrar pago</button><div role="alert"></div></form>`);
 o.querySelector('form').onsubmit=e=>{e.preventDefault();formSave(o,fd=>checked(sb.from('tnt_camp_payments').upsert({id,registration_id:r.id,amount:Number(fd.get('amount')),method:fd.get('method'),reference:fd.get('reference')||'',recorded_by:TNT.person.id},{onConflict:'id'}).select().single()))};
}
function deleteRegistration(r){if(!can('registrations'))return;const o=modal('Mover a papelera',`<p>La inscripción de <b>${E(person(r.person_id).full_name)}</b> se archiva solo en esta edición. Su perfil, pagos e historial se conservan.</p><form class="camp-form"><button class="tnt-button danger" type="submit">Mover a papelera</button><div role="alert"></div></form>`);o.querySelector('form').onsubmit=e=>{e.preventDefault();formSave(o,()=>checked(sb.from('tnt_camp_registrations').update({deleted_at:new Date().toISOString(),deleted_by:TNT.person.id}).eq('id',r.id).select().single()))}}
async function restoreRegistration(id){if(!can('registrations'))return;try{await checked(sb.from('tnt_camp_registrations').update({deleted_at:null,deleted_by:null}).eq('id',id).select().single());await load();U.toast('Ficha restaurada')}catch(e){U.toast(e.message,true)}}
async function checkin(id){if(!can('checkin'))return U.toast('No tenés permiso para Check-in.',true);try{const r=await sb.rpc('tnt_camp_checkin',{p_registration:id});if(r.error)throw r.error;await load();U.toast(r.data?.state==='out'?'Salida registrada':'Ingreso registrado')}catch(e){U.toast(e.message,true)}}
function voidPayment(id){if(!can('payments'))return;const o=modal('Anular pago',`<form class="camp-form">${field('Motivo','reason','','text','required')}<button class="tnt-button danger" type="submit">Anular pago</button><div role="alert"></div></form>`);o.querySelector('form').onsubmit=e=>{e.preventDefault();formSave(o,fd=>checked(sb.from('tnt_camp_payments').update({voided_at:new Date().toISOString(),void_reason:fd.get('reason')}).eq('id',id).select().single()))}}
async function healthForm(r){try{const h=await checked(sb.from('tnt_camp_health').select('*').eq('registration_id',r.id).maybeSingle())||{},editable=canHealthEdit();const o=modal('Salud · '+person(r.person_id).full_name,`<div class="camp-health-notice">Información sensible. Solo la ve el equipo autorizado y la persona vinculada.</div><form class="camp-form">${[['allergies','Alergias'],['medication','Medicación e indicaciones'],['dietary','Alimentación / restricciones'],['conditions','Información relevante']].map(([k,l])=>`<label class="camp-field"><span>${l}</span><textarea name="${k}" ${!editable?'readonly':''}>${E(h[k]||'')}</textarea></label>`).join('')}${field('Contacto de emergencia','emergency_name',h.emergency_name||'','text',!editable?'readonly':'')}${field('Teléfono de emergencia','emergency_phone',h.emergency_phone||'','tel',!editable?'readonly':'')}${editable?'<button class="tnt-button primary" type="submit">Guardar salud</button>':''}<div role="alert"></div></form>`);o.querySelector('form').onsubmit=e=>{e.preventDefault();if(!editable)return;formSave(o,fd=>checked(sb.from('tnt_camp_health').upsert({...Object.fromEntries(fd),registration_id:r.id,updated_at:new Date().toISOString()}).select().single()))}}catch(e){U.toast(e.message,true)}}
function renderPayments(view){
 const regs=active(),ids=new Set(regs.map(r=>r.id)),rows=S.payments.filter(p=>ids.has(p.registration_id)).sort((a,b)=>b.paid_at.localeCompare(a.paid_at)),received=rows.filter(p=>!p.voided_at).reduce((n,p)=>n+Number(p.amount),0),due=regs.reduce((n,r)=>n+Math.max(0,balance(r)),0);
 view.innerHTML=`<section class="camp-section-head"><div><span class="camp-eyebrow">FINANZAS</span><h2>Pagos</h2><p>Movimientos, saldos y medios de pago.</p></div></section><div class="camp-finance-summary"><div><small>Total recibido</small><b>${money(received)}</b></div><div><small>Saldo pendiente</small><b>${money(due)}</b></div><div><small>Pagados completos</small><b>${regs.filter(r=>balance(r)<=0).length}</b></div></div><div class="camp-list">${rows.map(p=>{const r=registration(p.registration_id);return`<article class="camp-list-row ${p.voided_at?'is-void':''}"><div><b>${E(person(r?.person_id).full_name||'Persona')}</b><small>${U.date(p.paid_at)} · ${p.voided_at?'Anulado':E({cash:'Efectivo',transfer:'Transferencia',other:'Otro'}[p.method]||'Otro')} · ${E(p.reference||'')}</small></div><strong>${money(p.amount)}</strong><button class="tnt-button" data-open="${r?.id}">Ficha</button></article>`}).join('')||'<div class="camp-empty">Todavía no hay movimientos.</div>'}</div>`;
 view.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>showRegistration(b.dataset.open));
}
function renderResources(view,kind){
 const rs=S.resources.filter(r=>r.camp_id===S.camp&&r.kind===kind),regs=active(),unassigned=regs.filter(r=>!S.assignments.some(a=>a.registration_id===r.id&&a.kind===kind));
 view.innerHTML=`<section class="camp-section-head"><div><span class="camp-eyebrow">LOGÍSTICA</span><h2>${kindLabel[kind]}</h2><p>${unassigned.length} personas sin asignar.</p></div>${can('logistics')?`<div class="camp-head-actions"><button class="tnt-button" id="auto-assign">Distribuir automáticamente</button><button class="tnt-button primary" id="new-resource">+ Agregar</button></div>`:''}</section><div class="camp-resource-grid">${rs.map(r=>{const members=S.assignments.filter(a=>a.resource_id===r.id&&regs.some(x=>x.id===a.registration_id)),pct=Math.min(100,Math.round(members.length/Math.max(1,r.capacity)*100));return`<article class="camp-resource-card"><div class="camp-resource-head"><div><span>${{room:'🛏',bus:'🚌',team:'⚑'}[kind]}</span><div><h3>${E(r.name)}</h3><small>${members.length}/${r.capacity} ocupados</small></div></div><b>${pct}%</b></div><div class="camp-progress"><i style="width:${pct}%"></i></div><div class="camp-resource-members">${members.map(a=>{const reg=registration(a.registration_id);return`<button data-open="${reg.id}">${E(person(reg.person_id).full_name)}</button>`}).join('')||'<span>Sin personas asignadas</span>'}</div>${can('logistics')?`<button class="tnt-button" data-edit-resource="${r.id}">Configurar</button>`:''}</article>`}).join('')||'<div class="camp-empty">Todavía no cargaste '+kindLabel[kind].toLowerCase()+'.</div>'}</div>`;
 view.querySelector('#new-resource')?.addEventListener('click',()=>resourceForm(null,kind));view.querySelector('#auto-assign')?.addEventListener('click',()=>autoAssign(kind));view.querySelectorAll('[data-edit-resource]').forEach(b=>b.onclick=()=>resourceForm(S.resources.find(x=>x.id===b.dataset.editResource),kind));view.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>showRegistration(b.dataset.open));
}
function resourceForm(r,kind=r?.kind){
 if(!can('logistics'))return;const o=modal(r?'Configurar '+kindLabel[kind].slice(0,-1):'Agregar '+kindLabel[kind].slice(0,-1),`<form class="camp-form">${field('Nombre','name',r?.name||'','text','required')}${field('Capacidad','capacity',r?.capacity||10,'number','min="1" required')}<button class="tnt-button primary" type="submit">Guardar</button>${r?'<button class="tnt-button danger" type="button" id="delete-resource">Eliminar</button>':''}<div role="alert"></div></form>`);
 o.querySelector('form').onsubmit=e=>{e.preventDefault();formSave(o,async fd=>{const row={camp_id:S.camp,kind,name:fd.get('name'),capacity:Number(fd.get('capacity'))};if(r&&resourceCount(r.id)>row.capacity)throw Error('Hay más personas asignadas que lugares.');await checked(r?sb.from('tnt_camp_resources').update(row).eq('id',r.id).select().single():sb.from('tnt_camp_resources').insert(row).select().single())})};
 o.querySelector('#delete-resource')?.addEventListener('click',async()=>{if(resourceCount(r.id))return U.toast('Primero quitá las personas asignadas.',true);if(!await U.confirm('¿Eliminar '+r.name+'?'))return;const q=await sb.from('tnt_camp_resources').delete().eq('id',r.id);if(q.error)return U.toast(q.error.message,true);U.closeModal(o);await load()});
}
function assignResource(r,kind){
 if(!can('logistics'))return;const options=S.resources.filter(x=>x.camp_id===S.camp&&x.kind===kind),current=S.assignments.find(a=>a.registration_id===r.id&&a.kind===kind),o=modal('Asignar '+kindLabel[kind].toLowerCase(),`<form class="camp-form"><label class="camp-field"><span>Destino</span><select name="resource"><option value="">Sin asignar</option>${options.map(x=>`<option value="${x.id}" ${x.id===current?.resource_id?'selected':''}>${E(x.name)} · ${resourceCount(x.id)}/${x.capacity}</option>`).join('')}</select></label><button class="tnt-button primary" type="submit">Guardar</button><div role="alert"></div></form>`);
 o.querySelector('form').onsubmit=e=>{e.preventDefault();formSave(o,fd=>checked(fd.get('resource')?sb.from('tnt_camp_assignments').upsert({registration_id:r.id,kind,resource_id:fd.get('resource')},{onConflict:'registration_id,kind'}).select().single():sb.from('tnt_camp_assignments').delete().eq('registration_id',r.id).eq('kind',kind)))};
}
async function autoAssign(kind){
 if(!can('logistics'))return;const count=active().filter(r=>!S.assignments.some(a=>a.registration_id===r.id&&a.kind===kind)).length;if(!count)return U.toast('Todos ya tienen '+kindLabel[kind].toLowerCase()+'.');if(!S.resources.some(r=>r.camp_id===S.camp&&r.kind===kind))return U.toast('Primero creá '+kindLabel[kind].toLowerCase()+'.',true);
 if(!await U.confirm('¿Distribuir automáticamente '+count+' personas sin asignar? Las asignaciones existentes no se cambian.'))return;
 const r=await sb.rpc('tnt_camp_auto_assign',{p_camp:S.camp,p_kind:kind});if(r.error)return U.toast(r.error.message,true);await load();U.toast((r.data||0)+' personas distribuidas');
}
function renderCheckin(view){
 const regs=active();view.innerHTML=`<section class="camp-section-head"><div><span class="camp-eyebrow">INGRESO Y SALIDA</span><h2>Check-in</h2><p>Buscá por nombre o DNI y registrá en un toque.</p></div></section><div class="camp-filterbar"><input id="checkin-search" type="search" placeholder="Nombre o DNI"><select id="checkin-filter"><option value="all">Todos</option><option value="out">Sin ingresar</option><option value="in">En el predio</option><option value="left">Ya salió</option></select></div><div id="checkin-list" class="camp-checkin-list"></div>`;
 const paint=()=>{const q=(view.querySelector('#checkin-search').value||'').toLowerCase(),f=view.querySelector('#checkin-filter').value;const rows=regs.filter(r=>{const p=person(r.person_id),state=r.checked_in_at&&!r.checked_out_at?'in':r.checked_out_at?'left':'out';return(p.full_name+' '+r.document_no).toLowerCase().includes(q)&&(f==='all'||f===state)});view.querySelector('#checkin-list').innerHTML=rows.map(r=>{const p=person(r.person_id),inside=r.checked_in_at&&!r.checked_out_at;return`<article class="camp-check-row ${inside?'inside':''}"><div class="camp-person-avatar">${initials(p.full_name)}</div><div><b>${E(p.full_name)}</b><small>${r.checked_out_at?'Salida '+new Date(r.checked_out_at).toLocaleTimeString('es-AR',{hour:'2-digit',minute:'2-digit'}):r.checked_in_at?'Ingreso '+new Date(r.checked_in_at).toLocaleTimeString('es-AR',{hour:'2-digit',minute:'2-digit'}):'Todavía no ingresó'}</small></div>${can('checkin')?`<button class="tnt-button ${inside?'danger':'primary'}" data-check="${r.id}">${inside?'Registrar salida':'Registrar ingreso'}</button>`:''}</article>`}).join('')||'<div class="camp-empty">Sin resultados.</div>';view.querySelectorAll('[data-check]').forEach(b=>b.onclick=()=>checkin(b.dataset.check))};
 view.querySelector('#checkin-search').oninput=paint;view.querySelector('#checkin-filter').onchange=paint;paint();
}
function renderCommunications(view){
 const rows=S.messages.filter(m=>m.camp_id===S.camp).sort((a,b)=>b.created_at.localeCompare(a.created_at));
 view.innerHTML=`<section class="camp-section-head"><div><span class="camp-eyebrow">COMUNICACIONES</span><h2>Mensajes</h2><p>Plantillas para WhatsApp, Instagram o avisos generales.</p></div>${can('communications')?'<button class="tnt-button primary" id="new-message">+ Mensaje</button>':''}</section><div class="camp-message-grid">${rows.map(m=>`<article class="camp-message-card"><span>${E(m.channel==='whatsapp'?'WhatsApp':m.channel==='instagram'?'Instagram':'General')}</span><h3>${E(m.title)}</h3><p>${E(m.body)}</p><div class="camp-head-actions"><button class="tnt-button" data-copy-message="${m.id}">Copiar</button>${can('communications')?`<button class="tnt-button" data-edit-message="${m.id}">Editar</button><button class="tnt-button danger" data-delete-message="${m.id}">Eliminar</button>`:''}</div></article>`).join('')||'<div class="camp-empty">Todavía no hay plantillas de mensajes.</div>'}</div>`;
 view.querySelector('#new-message')?.addEventListener('click',()=>messageForm());view.querySelectorAll('[data-edit-message]').forEach(b=>b.onclick=()=>messageForm(S.messages.find(x=>x.id===b.dataset.editMessage)));view.querySelectorAll('[data-copy-message]').forEach(b=>b.onclick=()=>copyText(S.messages.find(x=>x.id===b.dataset.copyMessage)?.body||''));view.querySelectorAll('[data-delete-message]').forEach(b=>b.onclick=async()=>{if(!await U.confirm('¿Eliminar este mensaje?'))return;const r=await sb.from('tnt_camp_messages').delete().eq('id',b.dataset.deleteMessage);if(r.error)return U.toast(r.error.message,true);await load()});
}
function messageForm(m=null){
 if(!can('communications'))return;const o=modal(m?'Editar mensaje':'Nuevo mensaje',`<form class="camp-form">${field('Título','title',m?.title||'','text','required')}<label class="camp-field"><span>Canal</span><select name="channel"><option value="whatsapp" ${m?.channel==='whatsapp'?'selected':''}>WhatsApp</option><option value="instagram" ${m?.channel==='instagram'?'selected':''}>Instagram</option><option value="general" ${m?.channel==='general'?'selected':''}>General</option></select></label><label class="camp-field"><span>Mensaje</span><textarea name="body" rows="8" required>${E(m?.body||'')}</textarea></label><button class="tnt-button primary" type="submit">Guardar mensaje</button><div role="alert"></div></form>`);
 o.querySelector('form').onsubmit=e=>{e.preventDefault();formSave(o,fd=>checked(m?sb.from('tnt_camp_messages').update({title:fd.get('title'),body:fd.get('body'),channel:fd.get('channel')}).eq('id',m.id).select().single():sb.from('tnt_camp_messages').insert({camp_id:S.camp,title:fd.get('title'),body:fd.get('body'),channel:fd.get('channel'),created_by:TNT.person.id}).select().single()))};
}
async function copyText(value){try{await navigator.clipboard.writeText(value)}catch{const t=document.createElement('textarea');t.value=value;document.body.append(t);t.select();document.execCommand('copy');t.remove()}U.toast('Copiado')}
function renderFormBuilder(view){
 const rows=S.formFields.filter(f=>f.camp_id===S.camp).sort((a,b)=>a.sort_order-b.sort_order);
 view.innerHTML=`<section class="camp-section-head"><div><span class="camp-eyebrow">FORMULARIO</span><h2>Campos de inscripción</h2><p>Definí preguntas adicionales para esta edición.</p></div>${can('form')?'<button class="tnt-button primary" id="new-field">+ Campo</button>':''}</section><div class="camp-list">${rows.map((f,idx)=>`<article class="camp-list-row ${f.active?'':'is-muted'}"><div><b>${E(f.label)}</b><small>${E({text:'Texto',textarea:'Texto largo',date:'Fecha',number:'Número',select:'Opciones',checkbox:'Sí / No'}[f.field_type]||f.field_type)} · ${f.required?'Obligatorio':'Opcional'} · ${f.active?'Visible':'Oculto'}</small></div>${can('form')?`<div class="camp-head-actions"><button class="tnt-button" data-move-field="${f.id}" data-dir="-1" ${idx===0?'disabled':''}>↑</button><button class="tnt-button" data-move-field="${f.id}" data-dir="1" ${idx===rows.length-1?'disabled':''}>↓</button><button class="tnt-button" data-edit-field="${f.id}">Editar</button></div>`:''}</article>`).join('')||'<div class="camp-empty">No hay campos adicionales. Nombre, nacimiento, teléfono, DNI, pago y autorización ya vienen incluidos.</div>'}</div>`;
 view.querySelector('#new-field')?.addEventListener('click',()=>fieldForm());view.querySelectorAll('[data-edit-field]').forEach(b=>b.onclick=()=>fieldForm(S.formFields.find(x=>x.id===b.dataset.editField)));view.querySelectorAll('[data-move-field]').forEach(b=>b.onclick=()=>moveField(b.dataset.moveField,Number(b.dataset.dir),rows));
}
function fieldForm(f=null){
 if(!can('form'))return;const opts=Array.isArray(f?.options)?f.options.join('\n'):'';const o=modal(f?'Editar campo':'Nuevo campo',`<form class="camp-form">${field('Etiqueta','label',f?.label||'','text','required')}<label class="camp-field"><span>Tipo</span><select name="type">${[['text','Texto'],['textarea','Texto largo'],['date','Fecha'],['number','Número'],['select','Opciones'],['checkbox','Sí / No']].map(([v,l])=>`<option value="${v}" ${f?.field_type===v?'selected':''}>${l}</option>`).join('')}</select></label><label class="camp-field"><span>Opciones — una por línea</span><textarea name="options" rows="5">${E(opts)}</textarea><small>Solo se usa cuando el tipo es Opciones.</small></label><label class="camp-check"><input type="checkbox" name="required" ${f?.required?'checked':''}> <span>Obligatorio</span></label><label class="camp-check"><input type="checkbox" name="active" ${f?.active===false?'':'checked'}> <span>Visible</span></label><button class="tnt-button primary" type="submit">Guardar campo</button>${f?'<button type="button" class="tnt-button danger" id="delete-field">Eliminar</button>':''}<div role="alert"></div></form>`);
 o.querySelector('form').onsubmit=e=>{e.preventDefault();formSave(o,fd=>{const label=String(fd.get('label')).trim(),row={camp_id:S.camp,label,field_key:f?.field_key||label.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,'')+'_'+Date.now().toString(36),field_type:fd.get('type'),required:fd.has('required'),active:fd.has('active'),options:String(fd.get('options')||'').split(/\n+/).map(x=>x.trim()).filter(Boolean),sort_order:f?.sort_order??S.formFields.filter(x=>x.camp_id===S.camp).length,updated_at:new Date().toISOString()};return checked(f?sb.from('tnt_camp_form_fields').update(row).eq('id',f.id).select().single():sb.from('tnt_camp_form_fields').insert(row).select().single())})};
 o.querySelector('#delete-field')?.addEventListener('click',async()=>{if(!await U.confirm('¿Eliminar este campo? Las respuestas históricas quedan guardadas en las fichas.'))return;const r=await sb.from('tnt_camp_form_fields').delete().eq('id',f.id);if(r.error)return U.toast(r.error.message,true);U.closeModal(o);await load()});
}
async function moveField(id,dir,rows){const idx=rows.findIndex(x=>x.id===id),j=idx+dir;if(idx<0||j<0||j>=rows.length)return;const a=rows[idx],b=rows[j];await Promise.all([sb.from('tnt_camp_form_fields').update({sort_order:b.sort_order}).eq('id',a.id),sb.from('tnt_camp_form_fields').update({sort_order:a.sort_order}).eq('id',b.id)]);await load()}
function renderMine(view){const r=S.registrations.find(r=>r.camp_id===S.camp&&r.person_id===TNT.person.id&&!r.deleted_at);if(!r){view.innerHTML='<div class="camp-empty">No tenés una inscripción vinculada a esta edición.</div>';return}const p=person(r.person_id);view.innerHTML=`<section class="camp-my-card"><span class="camp-eyebrow">MI CAMPAMENTO</span><h2>${E(p.full_name)}</h2><div class="camp-detail-grid"><div class="camp-metric"><small>Estado</small><b>${statusLabel[r.status]}</b></div><div class="camp-metric"><small>Saldo</small><b>${money(Math.max(0,balance(r)))}</b></div><div class="camp-metric"><small>Habitación</small><b>${E(assigned(r.id,'room')?.name||'—')}</b></div><div class="camp-metric"><small>Equipo</small><b>${E(assigned(r.id,'team')?.name||'—')}</b></div></div><button class="tnt-button" id="my-health">Mi ficha de salud</button></section>`;view.querySelector('#my-health').onclick=()=>healthForm(r)}
function editEdition(c=null){
 if(!can('manage_editions'))return;const o=modal(c?'Configurar edición':'Nueva edición',`<form class="camp-form">${field('Nombre','name',c?.name||'','text','required maxlength="100"')}<div class="camp-form-grid">${field('Comienza','start_date',c?.start_date||'','date','required')}${field('Termina','end_date',c?.end_date||'','date','required')}</div>${field('Lugar','location',c?.location||'')}${field('Cupo total','capacity',c?.capacity||100,'number','min="1" required')}${field('Valor de inscripción','fee',c?.fee||0,'number','min="0" step="0.01" required')}<label class="camp-field"><span>Estado</span><select name="status">${[['planning','En preparación'],['open','Inscripciones abiertas'],['closed','Inscripciones cerradas'],['archived','Archivada']].map(([v,l])=>`<option value="${v}" ${v===c?.status?'selected':''}>${l}</option>`).join('')}</select></label><label class="camp-field"><span>Descripción</span><textarea name="description">${E(c?.description||'')}</textarea></label><button class="tnt-button primary" type="submit">Guardar edición</button><div role="alert"></div></form>`);
 o.querySelector('form').onsubmit=e=>{e.preventDefault();formSave(o,async fd=>{const row=Object.fromEntries(fd);row.capacity=Number(row.capacity);row.fee=Number(row.fee);row.created_by=c?.created_by||TNT.person.id;if(String(row.end_date)<String(row.start_date))throw Error('La fecha final no puede ser anterior al inicio.');await checked(c?sb.from('tnt_camp_editions').update(row).eq('id',c.id).select().single():sb.from('tnt_camp_editions').insert(row).select().single())})};
}
function duplicateEdition(c){
 if(!can('manage_editions'))return;const o=modal('Duplicar edición',`<form class="camp-form">${field('Nombre','name',c.name+' · copia','text','required')}<div class="camp-form-grid">${field('Comienza','start','','date','required')}${field('Termina','end','','date','required')}</div><p>Se copian configuración, habitaciones, transporte, equipos y campos del formulario. No se copian inscriptos ni pagos.</p><button class="tnt-button primary" type="submit">Duplicar</button><div role="alert"></div></form>`);o.querySelector('form').onsubmit=e=>{e.preventDefault();formSave(o,async fd=>{const r=await sb.rpc('tnt_camp_duplicate_edition',{p_camp:c.id,p_name:fd.get('name'),p_start:fd.get('start'),p_end:fd.get('end')});if(r.error)throw r.error;S.camp=r.data})}
}
async function ensureXLSX(){if(window.XLSX)return;await new Promise((resolve,reject)=>{const sc=document.createElement('script');sc.src='https://cdn.jsdelivr.net/npm/xlsx@0.18.5/dist/xlsx.full.min.js';sc.onload=resolve;sc.onerror=()=>reject(new Error('No se pudo cargar el lector de Excel.'));document.head.append(sc)})}
function normalizeImportRow(row){
 const get=(...keys)=>{for(const k of keys){const hit=Object.keys(row).find(x=>x.toLowerCase().replace(/[^a-z0-9]/g,'')===k.toLowerCase().replace(/[^a-z0-9]/g,''));if(hit&&row[hit]!==undefined&&row[hit]!==null)return String(row[hit]).trim()}return''};
 return {full_name:(get('nombrecompleto','nombreyapellido')||[get('nombre'),get('apellido')].filter(Boolean).join(' ')).trim(),birthday:get('fechanacimiento','nacimiento','cumpleanos'),phone:get('telefono','whatsapp','celular'),document_no:get('dni','documento'),congregation:get('congregacion','iglesia'),fee:Number((get('total','importe','valor')||edition().fee).replace?.(',','.')||edition().fee),paid:Number((get('pago','abonado','pagado')||0).replace?.(',','.')||0),authorization:/^(si|sí|true|1|ok)$/i.test(get('autorizacion','documentacion'))};
}
async function parseImportFile(file){
 if(file.name.toLowerCase().endsWith('.json')){const d=JSON.parse(await file.text());if(Array.isArray(d))return d.map(normalizeImportRow);if(Array.isArray(d.People)){return d.People.map(p=>normalizeImportRow({...p,...((d.Enroll||[]).find(e=>e.PersonaId===p.Id)||{})}))}throw Error('No reconocimos la estructura del JSON.')}
 if(file.name.toLowerCase().endsWith('.csv')){const text=await file.text(),lines=text.split(/\r?\n/).filter(Boolean),sep=(lines[0].match(/;/g)||[]).length>(lines[0].match(/,/g)||[]).length?';':',';const headers=lines.shift().split(sep).map(x=>x.replace(/^"|"$/g,'').trim());return lines.map(line=>{const vals=line.split(sep).map(x=>x.replace(/^"|"$/g,'').trim()),obj={};headers.forEach((h,i)=>obj[h]=vals[i]||'');return normalizeImportRow(obj)})}
 await ensureXLSX();const data=await file.arrayBuffer(),wb=XLSX.read(data,{type:'array'}),sheet=wb.Sheets[wb.SheetNames[0]],rows=XLSX.utils.sheet_to_json(sheet,{defval:''});return rows.map(normalizeImportRow);
}
function importCamp(){
 if(!can('registrations'))return;const o=modal('Importar fichas',`<div class="camp-import"><p>Podés traer Excel, CSV o JSON. Antes de guardar, TNT compara con Perfiles para evitar clones.</p><input class="camp-file-native" id="campImportFile" type="file" accept=".xlsx,.xls,.csv,.json,application/json,text/csv"><label class="camp-file-picker" for="campImportFile"><span>⇧</span><div><b>Elegir archivo</b><small>Excel, CSV o JSON</small></div><i>›</i></label><div id="camp-import-preview"></div><div role="alert"></div></div>`,true);
 o.querySelector('#campImportFile').onchange=async e=>{const file=e.target.files?.[0];if(!file)return;try{const rows=(await parseImportFile(file)).filter(r=>r.full_name),preview=o.querySelector('#camp-import-preview');const mapped=rows.map((row,idx)=>{const phone=String(row.phone||'').replace(/\D/g,''),existing=S.people.find(p=>p.full_name.toLowerCase().trim()===row.full_name.toLowerCase().trim()||(phone&&String(p.phone||'').replace(/\D/g,'').endsWith(phone.slice(-8))));return{...row,idx,existing}});preview.innerHTML=`<div class="camp-import-summary"><b>${mapped.length} filas encontradas</b><span>${mapped.filter(x=>x.existing).length} coinciden con Perfiles · ${mapped.filter(x=>!x.existing).length} crearían un perfil nuevo</span></div><div class="camp-import-rows">${mapped.map(x=>`<label><input type="checkbox" data-import-row="${x.idx}" checked><div><b>${E(x.full_name)}</b><small>${x.existing?'Coincide con '+E(x.existing.full_name):'Perfil nuevo'} · ${E(x.document_no||'Sin DNI')}</small></div></label>`).join('')}</div><button class="tnt-button primary" id="confirm-camp-import">Importar seleccionadas</button>`;preview.querySelector('#confirm-camp-import').onclick=async ev=>{ev.target.disabled=true;try{let count=0;for(const x of mapped.filter(x=>preview.querySelector(`[data-import-row="${x.idx}"]`)?.checked)){if(x.existing&&S.registrations.some(r=>r.camp_id===S.camp&&r.person_id===x.existing.id&&!r.deleted_at))continue;const rr=await sb.rpc('tnt_save_camp_registration',{p_id:null,p_camp:S.camp,p_person:x.existing?.id||null,p_person_values:{full_name:x.full_name,birthday:/^\d{4}-\d{2}-\d{2}$/.test(x.birthday)?x.birthday:null,phone:x.phone||'',sex:x.existing?.sex||'U'},p_values:{document_no:x.document_no||'',congregation:x.congregation||'',fee:Number(x.fee)||edition().fee,status:'pending',authorization:!!x.authorization,notes:'Importada desde archivo.',answers:{}}});if(rr.error)throw rr.error;if(Number(x.paid)>0&&can('payments')){const pr=await sb.from('tnt_camp_payments').insert({registration_id:rr.data,amount:Number(x.paid),method:'other',reference:'Pago importado',recorded_by:TNT.person.id});if(pr.error)throw pr.error}count++}U.closeModal(o);await load();U.toast(count+' fichas importadas')}catch(err){o.querySelector('[role=alert]').textContent=err.message;ev.target.disabled=false}}}catch(err){o.querySelector('[role=alert]').textContent=err.message}};
}
TNT.ready.then(()=>{if(TNT.identity&&!TNT.blocked)load()});
})();