(() => {
const U=TNTUI,date=U.dateKey(),next=U.addDays(date,7),pid=n=>'00000000-0000-4000-8000-'+String(n).padStart(12,'0');
const people=['Nora Pérez','Bruno Díaz','Mara López','Lucas Rey','Ana Paz'].map((full_name,i)=>({id:pid(i+1),full_name,active:true,sex:i%2?'M':'F',birthday:'2000-03-04'}));
const accounts=people.map((p,i)=>({person_id:p.id,auth_user_id:pid(100+i),nickname:p.full_name.split(' ')[0],avatar_url:'/__preview__/avatar/'+i+'.svg',system_role:i===0?'admin':'user',ministry_role:i===0?'Pastor/a':'Líder',enabled:true,service_areas:['Organización'],email:'demo'+i+'@example.test'}));
const events=[{id:pid(20),name:'Sábado TNT · Somos equipo',kind:'saturday',start_date:date,end_date:date,status:'planning',location:'Centro Cristiano de Hurlingham',auto_generated:true},{id:pid(21),name:'United Camp · Trascendentes',kind:'camp',start_date:next,end_date:U.addDays(next,2),status:'confirmed',location:'Campamento',color:'#d2c4f5'}];
const tasks=['Bienvenida & conexión','Preparar la merienda','Dinámica en equipos','Multimedia y sonido'].map((title,i)=>({id:pid(30+i),event_id:pid(20),title,status:['preparing','unread','ready','progress'][i],priority:'medium',planned_start:date+'T'+(21+i)+':00:00Z',duration_minutes:30,sort_order:i,description:'Coordinamos los detalles con el equipo.',materials:'Materiales para la actividad',task_type:'simple'}));
const assignees=[{task_id:pid(30),person_id:pid(1),assignment_status:'assigned'},{task_id:pid(30),person_id:pid(2),assignment_status:'accepted'},{task_id:pid(30),person_id:pid(3),assignment_status:'accepted'},{task_id:pid(31),person_id:pid(1),assignment_status:'accepted'},{task_id:pid(31),person_id:pid(5),assignment_status:'accepted'},{task_id:pid(32),person_id:pid(4),assignment_status:'accepted'},{task_id:pid(33),person_id:pid(2),assignment_status:'assigned'}];
const threads=[{id:pid(60),title:'Bienvenida & conexión',thread_type:'task',task_id:pid(30),created_by:pid(1),created_at:date+'T12:00:00Z',updated_at:date+'T22:00:00Z',is_pinned:true,is_archived:false},{id:pid(61),title:'Equipo TNT',thread_type:'general',created_at:date+'T12:00:00Z',is_archived:false},{id:pid(62),title:'United Camp',thread_type:'event',event_id:pid(21),created_at:date+'T12:00:00Z',is_archived:false}];
const messages=[{id:pid(70),thread_id:pid(60),person_id:pid(2),body:'¡Equipo! ¿Cómo venimos con la bienvenida del sábado?',created_at:date+'T20:30:00Z',pinned:true},{id:pid(71),thread_id:pid(60),person_id:pid(1),body:'Ya está todo preparado 🙌 Nos encontramos media hora antes para organizar la entrada.',created_at:date+'T20:32:00Z'},{id:pid(72),thread_id:pid(60),person_id:pid(3),body:'¡Dale! Yo llevo los carteles.\n¿Sumamos música mientras van llegando?',created_at:date+'T20:34:00Z',reply_to:pid(71)}];
const db=window.__fixtureDB={tnt_people:people,tnt_accounts:accounts,tnt_events:events,tnt_event_members:[...people.map(p=>({event_id:pid(20),person_id:p.id,event_role:p.id===pid(1)?'organizer':'participant'})),{event_id:pid(21),person_id:pid(1),event_role:'organizer'}],tnt_tasks:tasks,tnt_task_assignees:assignees,tnt_schedule_days:[{id:pid(40),event_id:pid(20),date,label:'Sábado',sort_order:0}],tnt_schedule_items:tasks.map((t,i)=>({id:pid(50+i),day_id:pid(40),task_id:t.id,title:t.title,starts_at:(18+i)+':00:00',duration_minutes:30,item_type:'activity',run_status:'pending',sort_order:i})),tnt_schedule_responsibles:assignees.map(a=>({item_id:pid(Number(a.task_id.slice(-2))+20),person_id:a.person_id})),tnt_notifications:[{id:pid(90),title:'Te sumaste a Bienvenida',body:'Confirmá tu participación.',person_id:pid(1),created_at:date+'T12:00:00Z',read_at:null}],tnt_chat_threads:threads,tnt_chat_messages:messages,tnt_chat_members:people.slice(0,3).map((p,i)=>({thread_id:pid(60),person_id:p.id,member_role:'member',last_read_at:date+(i===2?'T20:20:00Z':'T20:40:00Z')})),tnt_chat_reactions:[{message_id:pid(71),person_id:pid(2),reaction:'❤️'},{message_id:pid(71),person_id:pid(3),reaction:'❤️'}],tnt_settings:[{key:'organization_defaults',value:{auto_saturdays:true,saturday_start:'18:30',default_activities:['Bienvenida','Merienda']}}],tnt_templates:[],tnt_template_items:[],tnt_library_items:[],tnt_availability:[],tnt_checkins:[]};
window.__fixtureCalls=[];window.__fixtureFailures={};
class Q{constructor(t){this.t=t;this.filters=[];this.orders=[];this.action='read';this.singleResult=false;}select(){return this;}eq(k,v){this.filters.push(x=>x[k]===v);return this;}neq(k,v){this.filters.push(x=>x[k]!==v);return this;}is(k,v){return this.eq(k,v);}in(k,v){this.filters.push(x=>v.includes(x[k]));return this;}lt(k,v){this.filters.push(x=>x[k]<v);return this;}gte(k,v){this.filters.push(x=>x[k]>=v);return this;}order(k,o={}){this.orders.push([k,o.ascending!==false]);return this;}limit(n){this.n=n;return this;}range(a,b){this.a=a;this.n=b-a+1;return this;}single(){this.singleResult=true;return this;}maybeSingle(){return this.single();}update(v){this.action='update';this.value=v;return this;}insert(v){this.action='insert';this.value=v;return this;}upsert(v){this.action='upsert';this.value=v;return this;}delete(){this.action='delete';return this;}then(resolve,reject){return Promise.resolve().then(async()=>{window.__fixtureCalls.push({table:this.t,action:this.action,value:this.value});const failure=window.__fixtureFailures[this.t+':'+this.action]||window.__fixtureFailures[this.t];if(failure)return {data:null,error:{message:failure}};let all=db[this.t]||(db[this.t]=[]),rows=all.filter(x=>this.filters.every(f=>f(x)));if(this.action==='insert'||this.action==='upsert'){rows=(Array.isArray(this.value)?this.value:[this.value]).map(v=>({id:crypto.randomUUID(),created_at:new Date().toISOString(),...v}));all.push(...rows);}if(this.action==='update')rows.forEach(x=>Object.assign(x,this.value));if(this.action==='delete')db[this.t]=all.filter(x=>!rows.includes(x));rows=[...rows];for(const [k,asc]of this.orders.slice().reverse())rows.sort((a,b)=>(String(a[k]||'').localeCompare(String(b[k]||'')))*(asc?1:-1));if(this.n)rows=rows.slice(this.a||0,(this.a||0)+this.n);return {data:this.singleResult?rows[0]||null:structuredClone(rows),error:null};}).then(resolve,reject);}}
const sb={from:t=>new Q(t),rpc:async(n,args)=>{window.__fixtureCalls.push({rpc:n,args});if(window.__fixtureFailures['rpc:'+n])return{error:{message:window.__fixtureFailures['rpc:'+n]}};if(n==='tnt_save_task'){const t=db.tnt_tasks.find(t=>t.id===args.p_id);if(t)Object.assign(t,args.p_values);return{data:args.p_id,error:null};}if(n==='tnt_chat_overview')return{data:threads.map(t=>{const m=db.tnt_chat_messages.filter(m=>m.thread_id===t.id).at(-1);return{thread_id:t.id,last_body:m?.body,last_created_at:m?.created_at,unread_count:t.id===pid(60)?2:0};})};if(n==='tnt_open_activity_chat')return{data:pid(60)};if(n==='tnt_set_assignment_response'){const a=assignees.find(a=>a.task_id===args.p_task&&a.person_id===pid(1));if(a)a.assignment_status=args.p_status;}return{data:{created:0},error:null};},auth:{signOut:async()=>({}),getSession:async()=>({data:{session:{user:{id:pid(100)}}}})},storage:{from:()=>({upload:async()=>({data:{}}),createSignedUrl:async()=>({data:{signedUrl:'/__preview__/avatar/0.svg'}})})},channel:()=>({on(){return this},subscribe(){return this}})};
const identity={display_name:'Nora',person_id:pid(1),system_role:'admin',email:'demo@example.test'};
window.TNT={sb,ready:Promise.resolve(),person:people[0],account:accounts[0],identity,isAdmin:true,session:{user:{id:pid(100)}},grants:['organizacion','chat','campamento','efe','lista-sabados','glosario','buffet'].map(module=>({module,scope:'*',enabled:true,access_level:'manage'})),displayName:()=>identity.display_name,avatar:()=>accounts[0].avatar_url,hasAccess:()=>true,accessLevel:()=> 'manage',setTheme(t){document.documentElement.dataset.tntTheme=t;document.dispatchEvent(new CustomEvent('tnt:theme'));},toggleTheme(){this.setTheme(document.documentElement.dataset.tntTheme==='dark'?'light':'dark')},editProfile:()=>U.modal('Perfil de demostración','<p>Cuenta de prueba.</p>'),logout(){}};
TNT.setTheme('dark');if(!location.pathname.includes('/hub')){document.body.classList.add('tnt-shell-active');document.body.insertAdjacentHTML('beforeend',`<header id="tnt-shell"><a class="tnt-shell-home" href="/__preview__/hub">${U.icon('home')}</a><div class="tnt-shell-brand"><b>TNT</b><small>Demostración · datos de prueba</small></div><button class="tnt-shell-icon" onclick="TNT.toggleTheme()" aria-label="Cambiar tema">${U.icon('sun')}</button><span class="tnt-shell-user">${U.avatar(people[0],accounts[0])}Nora</span></header>`);}
})();
