'use strict';
const app=document.getElementById('orgApp'),sb=TNT.sb;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const S={tab:'mine',date:new Date().toISOString().slice(0,10),month:new Date(new Date().getFullYear(),new Date().getMonth(),1),people:[],accounts:[],events:[],members:[],tasks:[],assignees:[],days:[],items:[],resp:[],notes:[],groups:[],groupMembers:[],files:[],settings:[],checkins:[],availability:[]};
const person=id=>S.people.find(x=>x.id===id)||{id,full_name:'Persona'},acct=id=>S.accounts.find(x=>x.person_id===id)||{},event=id=>S.events.find(x=>x.id===id);
const initials=n=>String(n||'?').split(/\s+/).slice(0,2).map(x=>x[0]||'').join('').toUpperCase();
const fmt=x=>x?new Intl.DateTimeFormat('es-AR',{weekday:'short',day:'numeric',month:'short'}).format(new Date(x+'T12:00:00')):'';
const mine=t=>S.assignees.some(a=>a.task_id===t.id&&a.person_id===TNT.person?.id);
const taskPeople=id=>S.assignees.filter(a=>a.task_id===id).map(a=>person(a.person_id));
const itemPeople=id=>S.resp.filter(a=>a.item_id===id).map(a=>person(a.person_id));
const status=s=>({unread:'No leído',assigned:'Asignado',read:'Leído',accepted:'Aceptado',declined:'No puedo',preparing:'En preparación',progress:'Avanzando',review:'Necesita revisión',ready:'Listo',done:'Terminado',replacement:'Necesita reemplazo'}[s]||s||'Pendiente');
function avatar(p){const a=acct(p.id);return a.avatar_url?`<img class="ava" src="${esc(a.avatar_url)}" title="${esc(p.full_name)}">`:`<span class="ava" title="${esc(p.full_name)}">${esc(initials(a.nickname||p.full_name))}</span>`}
function avatars(ps){return `<div class="avatars">${ps.slice(0,5).map(avatar).join('')}${ps.length>5?`<span class="ava">+${ps.length-5}</span>`:''}</div>`}
async function load(){await TNT.ready;if(!TNT.identity)return;const map=[['tnt_people','people'],['tnt_accounts','accounts'],['tnt_events','events'],['tnt_event_members','members'],['tnt_tasks','tasks'],['tnt_task_assignees','assignees'],['tnt_schedule_days','days'],['tnt_schedule_items','items'],['tnt_schedule_responsibles','resp'],['tnt_notifications','notes'],['tnt_groups','groups'],['tnt_group_members','groupMembers'],['tnt_library_items','files'],['tnt_settings','settings'],['tnt_checkins','checkins'],['tnt_availability','availability']];for(const [t,k] of map){let q=sb.from(t).select('*');const r=await q;if(!r.error)S[k]=r.data||[]}render()}
function nav(){return `<nav class="nav">${[['mine','Mi TNT'],['calendar','Calendario'],['activities','Actividades'],['events','Eventos'],['groups','Grupos'],['team','Equipo'],['brief','Briefing'],['files','Archivos'],['advanced','Avanzado']].map(([k,l])=>`<button data-tab="${k}" class="${S.tab===k?'on':''}">${l}</button>`).join('')}</nav>`}
function render(){app.innerHTML=`<div class="org"><header class="head"><div><div class="ey">CENTRO DE OPERACIONES</div><h1>Organización</h1><p>${esc(TNT.displayName())}, acá ves lo tuyo y también el panorama general.</p></div><div class="headacts"><button class="round" id="chat">◌</button><button class="round" id="print">⇧</button></div></header>${nav()}<section>${view()}</section></div>`;bind()}
function view(){return S.tab==='mine'?mineView():S.tab==='calendar'?calendarView():S.tab==='activities'?activitiesView():S.tab==='events'?eventsView():S.tab==='groups'?groupsView():S.tab==='team'?teamView():S.tab==='brief'?briefView():S.tab==='files'?filesView():'<iframe class="legacy" src="/organizacion/legacy.html?embedded=1"></iframe>'}
function mineView(){const mt=S.tasks.filter(mine).filter(t=>!['done','completed'].includes(t.status)),today=new Date().toISOString().slice(0,10),ev=S.events.filter(e=>e.start_date<=today&&e.end_date>=today),un=S.notes.filter(n=>(!n.person_id||n.person_id===TNT.person.id)&&!n.read_at);return `<div class="brief"><div style="font-size:8px;font-weight:900;letter-spacing:.13em">MI CUENTA TNT</div><h2>${mt.length?mt.length+' responsabilidades activas':'Todo al día'}</h2><p>${un.length} notificaciones sin leer · ${ev.length} eventos hoy</p></div><div class="section"><div><h2>Mis actividades</h2><p>Las tareas donde participás aparecen destacadas.</p></div></div><div class="cards">${mt.length?mt.map(taskCard).join(''):'<div class="empty">No tenés tareas pendientes.</div>'}</div>`}
function taskCard(t){const ps=taskPeople(t.id),e=event(t.event_id),isMine=mine(t);return `<button class="card ${isMine?'mine':''}" data-task="${t.id}" style="text-align:left;color:inherit;width:100%">${isMine?'<span class="mineTag">SOS PARTE</span>':''}<div class="taskTop"><span class="taskIco">${esc(t.icon||'✓')}</span><div class="taskBody"><h3>${esc(t.title)}</h3><p>${esc(e?.name||'Organización')}${t.due_at?' · '+new Date(t.due_at).toLocaleString('es-AR',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'}):''}</p></div></div>${avatars(ps)}<div class="meta"><span class="status">${esc(status(t.status))}</span><span class="status">${ps.length} responsables</span></div></button>`}
function calendarView(){const y=S.month.getFullYear(),m=S.month.getMonth(),first=new Date(y,m,1),last=new Date(y,m+1,0),start=(first.getDay()+6)%7,a=[];for(let i=0;i<start;i++)a.push('<span></span>');const def=S.settings.find(x=>x.key==='organization_defaults')?.value||{},auto=def.auto_saturdays!==false;for(let d=1;d<=last.getDate();d++){const dt=`${y}-${String(m+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`,has=S.events.some(e=>e.start_date<=dt&&e.end_date>=dt)||S.days.some(x=>x.date===dt),sat=new Date(dt+'T12:00:00').getDay()===6;a.push(`<button class="day ${has?'has':''} ${sat&&auto?'sat':''} ${S.date===dt?'sel':''}" data-date="${dt}">${d}${has?'<i class="dot"></i>':''}</button>`)}const ag=agenda(S.date);return `<div class="calendarWrap"><div class="calendar"><div class="calHead"><button data-month="-1">‹</button><b>${esc(new Intl.DateTimeFormat('es-AR',{month:'long',year:'numeric'}).format(S.month))}</b><button data-month="1">›</button></div><div class="week">${['Lu','Ma','Mi','Ju','Vi','Sa','Do'].map(x=>'<span>'+x+'</span>').join('')}</div><div class="days">${a.join('')}</div>${TNT.isAdmin?`<div style="margin-top:10px;display:flex;justify-content:space-between;align-items:center"><small>Sábados TNT automáticos</small><button class="btn ${auto?'good':''}" id="autoSat">${auto?'Activados':'Desactivados'}</button></div>`:''}</div><div><div class="section"><div><h2>${fmt(S.date)}</h2><p>${ag.length} actividades</p></div>${TNT.isAdmin&&auto&&new Date(S.date+'T12:00:00').getDay()===6?'<button class="btn primary" id="createSat">Crear Sábado TNT</button>':''}</div><div class="agenda">${ag.length?ag.map(agendaCard).join(''):'<div class="empty">No hay actividades cargadas.</div>'}</div></div></div>`}
function agenda(date){const ds=S.days.filter(d=>d.date===date),ids=new Set(ds.map(d=>d.id));return S.items.filter(i=>ids.has(i.day_id))}
function agendaCard(i){const ps=itemPeople(i.id);return `<article class="agendaItem" style="--c:${i.item_type==='game'?'#ff6a35':i.item_type==='meal'?'#f0b94f':'#7868ff'}"><time>${i.starts_at?String(i.starts_at).slice(0,5):'—'}</time><div><b>${esc(i.title)}</b><small>${esc(i.location||i.description||i.item_type)}</small>${ps.length?avatars(ps):''}</div><button data-item="${i.id}">›</button></article>`}
function activitiesView(){return `<div class="section"><div><h2>Actividades y tareas</h2><p>Podés ver lo tuyo resaltado y el trabajo de los demás.</p></div></div><div class="cards">${S.tasks.length?S.tasks.map(taskCard).join(''):'<div class="empty">Todavía no hay tareas.</div>'}</div>`}
function eventsView(){return `<div class="section"><div><h2>Eventos</h2><p>Sábados, congresos, campamentos y actividades especiales.</p></div>${TNT.isAdmin||TNT.hasAccess('organizacion','*','manage')?'<button class="btn primary" id="newEvent">＋ Evento</button>':''}</div><div class="eventgrid">${S.events.length?S.events.sort((a,b)=>a.start_date.localeCompare(b.start_date)).map(eventCard).join(''):'<div class="empty">Todavía no hay eventos.</div>'}</div>`}
function eventCard(e){const n=S.members.filter(m=>m.event_id===e.id).length,c=S.checkins.filter(x=>x.event_id===e.id&&!x.checked_out_at).length;return `<article class="card event"><span class="status good">${esc(e.status)}</span><h3>${esc(e.name)}</h3><p>${fmt(e.start_date)} · ${esc(e.location||'Sin lugar')}</p><div class="meta"><span class="status">${n} personas</span><span class="status">${c} presentes</span></div><div class="eventActions"><button class="btn" data-event="${e.id}">Ver</button><button class="btn good" data-check="${e.id}">✓ Ya llegué</button><button class="btn" data-eventchat="${e.id}">Chat</button></div></article>`}
function groupsView(){const byDay={};for(const g of S.groups)(byDay[g.day_id||'general']??=[]).push(g);return `<div class="section"><div><h2>Grupos por día</h2><p>Rojo/Azul y otros grupos configurables. Sexo solo si está confirmado.</p></div></div><div class="groupgrid">${Object.entries(byDay).flatMap(([d,gs])=>gs.map(g=>{const mem=S.groupMembers.filter(x=>x.group_id===g.id).map(x=>person(x.person_id));return `<article class="card" style="border-top:4px solid ${esc(g.color)}"><h3>${esc(g.name)}</h3><p style="font-size:8px;color:var(--tnt-muted)">${mem.length} integrantes</p>${avatars(mem)}</article>`})).join('')||'<div class="empty">Todavía no hay grupos generados.</div>'}</div>`}
function teamView(){const workload=id=>S.assignees.filter(a=>a.person_id===id&&S.tasks.some(t=>t.id===a.task_id&&!['done','completed'].includes(t.status))).length;return `<div class="section"><div><h2>Equipo</h2><p>Perfiles, disponibilidad y carga de trabajo.</p></div></div><div class="teamgrid">${S.people.filter(p=>acct(p.id).auth_user_id).map(p=>{const a=acct(p.id),w=workload(p.id);return `<button class="card member" data-person="${p.id}" style="color:inherit;text-align:left"><span class="ava">${esc(initials(a.nickname||p.full_name))}</span><div><h3>${esc(a.nickname||p.full_name)}</h3><p>${esc(a.ministry_role||'Timoteo')} · ${w} tareas activas</p><div class="workbar"><i style="width:${Math.min(100,w*16)}%"></i></div></div><span>›</span></button>`}).join('')}</div>`}
function briefView(){const list=S.tasks.filter(mine).filter(t=>!['done','completed'].includes(t.status));return `<div class="brief"><div style="font-size:8px;font-weight:900">MI BRIEFING</div><h2>Lo que necesitás saber</h2><p>Responsabilidades, horarios, equipo y próximos compromisos.</p><div class="briefList">${list.map(t=>`<div class="briefItem"><b>${esc(t.title)}</b><small>${esc(event(t.event_id)?.name||'TNT')} · ${esc(status(t.status))}</small></div>`).join('')||'<div class="briefItem">No tenés responsabilidades pendientes.</div>'}</div></div>`}
function filesView(){return `<div class="section"><div><h2>Biblioteca TNT</h2><p>Links, videos, documentos e imágenes.</p></div>${TNT.isAdmin||TNT.hasAccess('organizacion','*','edit')?'<button class="btn primary" id="addFile">＋ Agregar</button>':''}</div><div class="cards">${S.files.filter(f=>!f.module||f.module==='organizacion').map(f=>`<a class="card file" href="${esc(f.url)}" target="_blank" style="color:inherit;text-decoration:none"><span class="ico">↗</span><div><b>${esc(f.title)}</b><small>${esc(f.folder)} · ${esc(f.item_type)}</small></div><span>›</span></a>`).join('')||'<div class="empty">Todavía no hay archivos.</div>'}</div>`}
function bind(){document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{S.tab=b.dataset.tab;render()});document.querySelectorAll('[data-task]').forEach(b=>b.onclick=()=>taskModal(b.dataset.task));document.querySelectorAll('[data-item]').forEach(b=>b.onclick=()=>itemModal(b.dataset.item));document.querySelectorAll('[data-event]').forEach(b=>b.onclick=()=>eventModal(b.dataset.event));document.querySelectorAll('[data-eventchat]').forEach(b=>b.onclick=()=>openChat('event',b.dataset.event,event(b.dataset.event)?.name));document.querySelectorAll('[data-check]').forEach(b=>b.onclick=()=>checkin(b.dataset.check));document.querySelectorAll('[data-person]').forEach(b=>b.onclick=()=>personModal(b.dataset.person));document.querySelectorAll('[data-date]').forEach(b=>b.onclick=()=>{S.date=b.dataset.date;render()});document.querySelectorAll('[data-month]').forEach(b=>b.onclick=()=>{S.month=new Date(S.month.getFullYear(),S.month.getMonth()+Number(b.dataset.month),1);render()});document.getElementById('chat').onclick=()=>location.href='/chat/';document.getElementById('print').onclick=()=>window.print();document.getElementById('newEvent')?.addEventListener('click',newEvent);document.getElementById('autoSat')?.addEventListener('click',toggleAuto);document.getElementById('createSat')?.addEventListener('click',createSat);document.getElementById('addFile')?.addEventListener('click',addFile)}
function taskModal(id){const t=S.tasks.find(x=>x.id===id),ps=taskPeople(id),e=event(t.event_id);const box=TNT.sheet(t.title,`<p>${esc(t.description||'Sin descripción')}</p>${avatars(ps)}<div class="meta"><span class="status">${esc(e?.name||'')}</span><span class="status">${esc(status(t.status))}</span></div>${mine(t)?'<div class="eventActions"><button class="btn good" data-r="accepted">Acepto</button><button class="btn" data-r="read">Leído</button><button class="btn" data-r="declined">No puedo</button></div>':''}<div class="eventActions"><button class="btn primary" id="taskChat">Chat de esta tarea</button></div>`);document.querySelectorAll('[data-r]',box).forEach(b=>b.onclick=async()=>{await sb.rpc('tnt_set_assignment_response',{p_task:id,p_status:b.dataset.r,p_note:null});document.querySelector('.tnt-overlay')?.remove();load()});document.getElementById('taskChat').onclick=()=>openChat('task',id,t.title,t.event_id)}
function itemModal(id){const i=S.items.find(x=>x.id===id),ps=itemPeople(id);const yt=youtube(i.video_url);const box=TNT.sheet(i.title,`<p>${esc(i.description||'')}</p>${avatars(ps)}<div class="meta"><span class="status">${esc(i.item_type)}</span>${i.starts_at?`<span class="status">${String(i.starts_at).slice(0,5)}</span>`:''}${i.location?`<span class="status">${esc(i.location)}</span>`:''}</div>${i.materials?`<div class="card" style="margin-top:10px"><b>Materiales</b><p>${esc(i.materials)}</p></div>`:''}${yt?`<iframe class="youtube" src="${yt}" allowfullscreen></iframe>`:''}<div class="section"><div><h2>Responsables</h2></div></div>${ps.map(p=>`<button class="card member" data-resp="${p.id}" style="width:100%;color:inherit;text-align:left"><span class="ava">${esc(initials(acct(p.id).nickname||p.full_name))}</span><div><h3>${esc(acct(p.id).nickname||p.full_name)}</h3><p>Ver responsabilidades</p></div><span>›</span></button>`).join('')||'<div class="empty">Sin responsables.</div>'}`);document.querySelectorAll('[data-resp]',box).forEach(b=>b.onclick=()=>personModal(b.dataset.resp))}
function youtube(url){if(!url)return'';try{const u=new URL(url),id=u.hostname.includes('youtu.be')?u.pathname.slice(1):u.searchParams.get('v');return id?'https://www.youtube.com/embed/'+id:''}catch{return''}}
function personModal(id){const p=person(id),a=acct(id),ts=S.tasks.filter(t=>S.assignees.some(x=>x.task_id===t.id&&x.person_id===id)),its=S.items.filter(i=>S.resp.some(x=>x.item_id===i.id&&x.person_id===id));TNT.sheet(a.nickname||p.full_name,`<div class="tnt-profile-head"><span class="tnt-avatar fallback">${esc(initials(a.nickname||p.full_name))}</span><div><b>${esc(p.full_name)}</b><small>${esc(a.ministry_role||'Timoteo')}</small></div></div><div class="section"><div><h2>Responsabilidades</h2></div></div><div class="cards">${its.map(i=>`<div class="card"><b>${esc(i.title)}</b><p>${i.starts_at?String(i.starts_at).slice(0,5):''}</p></div>`).join('')}${ts.map(t=>`<div class="card"><b>${esc(t.title)}</b><p>${esc(status(t.status))}</p></div>`).join('')||'<div class="empty">Sin responsabilidades.</div>'}</div>`)}
function eventModal(id){const e=event(id);TNT.sheet(e.name,`<p>${esc(e.description||'')}</p><div class="meta"><span class="status">${fmt(e.start_date)}</span><span class="status">${esc(e.location||'Sin lugar')}</span></div><div class="eventActions"><button class="btn primary" id="evChat">Chat</button><button class="btn" id="project">Modo pantalla</button></div>`);document.getElementById('evChat').onclick=()=>openChat('event',id,e.name);document.getElementById('project').onclick=()=>project(id)}
async function openChat(type,id,title,eventId){let q=sb.from('tnt_chat_threads').select('*').eq(type==='task'?'task_id':'event_id',id).maybeSingle(),r=await q,thread=r.data;if(!thread){const c=await sb.from('tnt_chat_threads').insert({title,thread_type:type,module:'organizacion',scope:'*',task_id:type==='task'?id:null,event_id:type==='event'?id:eventId||null,created_by:TNT.person.id}).select('*');thread=c.data?.[0]}if(thread)location.href='/chat/?thread='+thread.id}
async function checkin(eid){const c=S.checkins.find(x=>x.event_id===eid&&x.person_id===TNT.person.id&&!x.checked_out_at);if(c)await sb.from('tnt_checkins').update({checked_out_at:new Date().toISOString()}).eq('id',c.id);else await sb.from('tnt_checkins').upsert({event_id:eid,person_id:TNT.person.id,checked_in_at:new Date().toISOString(),checked_out_at:null},{onConflict:'event_id,person_id'}).select('*');load()}
function project(eid){const e=event(eid),dids=new Set(S.days.filter(d=>d.event_id===eid).map(d=>d.id)),list=S.items.filter(i=>dids.has(i.day_id)),d=document.createElement('div');d.className='project';d.innerHTML=`<button class="closeProj">×</button><div style="color:#9b90ff;font-weight:900">MODO EVENTO</div><h1>${esc(e.name)}</h1><p>${fmt(e.start_date)} · ${esc(e.location||'')}</p><div class="agenda">${list.map(agendaCard).join('')}</div>`;document.body.appendChild(d);d.querySelector('.closeProj').onclick=()=>d.remove()}
async function toggleAuto(){const row=S.settings.find(x=>x.key==='organization_defaults'),v={...(row?.value||{})};v.auto_saturdays=!(v.auto_saturdays!==false);await sb.from('tnt_settings').upsert({key:'organization_defaults',value:v,updated_by:TNT.person.id},{onConflict:'key'}).select('*');load()}
async function createSat(){const r=await sb.rpc('tnt_create_saturday',{p_date:S.date,p_name:'Sábado TNT'});if(r.error)alert(r.error.message);else load()}
function newEvent(){TNT.sheet('Nuevo evento',`<div class="field"><label>Nombre</label><input id="n"></div><div class="field"><label>Fecha</label><input id="d" type="date" value="${S.date}"></div><div class="field"><label>Lugar</label><input id="l"></div><button class="btn primary" id="save">Crear</button>`);document.getElementById('save').onclick=async()=>{const n=document.getElementById('n').value.trim(),d=document.getElementById('d').value;if(!n)return;await sb.from('tnt_events').insert({name:n,kind:'event',start_date:d,end_date:d,location:document.getElementById('l').value,status:'planning',created_by:TNT.person.id}).select('*');document.querySelector('.tnt-overlay')?.remove();load()}}
function addFile(){TNT.sheet('Agregar recurso',`<div class="field"><label>Título</label><input id="ft"></div><div class="field"><label>URL</label><input id="fu"></div><button class="btn primary" id="fs">Guardar</button>`);document.getElementById('fs').onclick=async()=>{const title=document.getElementById('ft').value.trim(),url=document.getElementById('fu').value.trim();if(!title||!url)return;await sb.from('tnt_library_items').insert({title,url,folder:'Organización',item_type:'link',module:'organizacion',uploaded_by:TNT.person.id}).select('*');document.querySelector('.tnt-overlay')?.remove();load()}}
document.addEventListener('tnt:ready',load,{once:true});setTimeout(()=>TNT.identity&&load(),300);