function viewMy(){
  let myA=S.assignees.filter(a=>a.person_id===currentPersonId()&&a.assignment_status!=='declined').map(a=>({a,t:taskBy(a.task_id)})).filter(x=>x.t).sort((x,y)=>(x.t.due_at||'9999').localeCompare(y.t.due_at||'9999'));
  let upcoming=S.events.filter(e=>e.end_date>=today()).slice(0,5),notes=S.notifications.filter(n=>n.person_id===currentPersonId()||n.person_id===null).slice(0,5);
  let open=myA.filter(x=>x.t.status!=='completed').length;return `<div class="page"><section class="hero"><div class="eyebrow">Tu espacio</div><h1>Hola, ${esc(S.account.nickname||S.person.full_name)} 👋</h1><p>Todo lo que necesitás servir, confirmar y organizar sin perseguir mensajes por WhatsApp.</p></section><div class="grid g4"><div class="card kpi"><b>${open}</b><span>Tareas abiertas</span></div><div class="card kpi"><b>${notes.filter(n=>!n.read_at).length}</b><span>Notificaciones</span></div><div class="card kpi"><b>${upcoming.length}</b><span>Próximos eventos</span></div><div class="card kpi"><b>${workloadFor(currentPersonId())}</b><span>Asignaciones este mes</span></div></div><div class="sectionHead"><h2>Próximo</h2><button class="btn small" data-view="tasks">Ver todas</button></div>${myA.length?`<div class="list">${myA.slice(0,5).map(({a,t})=>taskRow(t,a)).join('')}</div>`:empty('Sin asignaciones','Cuando te asignen algo va a aparecer acá.')}<div class="sectionHead"><h2>Próximos eventos</h2><button class="btn small" data-view="events">Ver eventos</button></div>${upcoming.length?`<div class="grid g2">${upcoming.map(eventCard).join('')}</div>`:empty('No hay eventos próximos','')}<div class="sectionHead"><h2>Notificaciones</h2></div>${notes.length?`<div class="list">${notes.map(noteRow).join('')}</div>`:empty('Sin notificaciones','')}</div>`}
function taskRow(t,a){let e=eventBy(t.event_id);return `<button class="rowCard" data-task-open="${t.id}"><div class="ico">${esc(t.icon||'✓')}</div><div><b>${esc(t.title)}</b><div class="meta">${esc(e?.name||'Evento')} ${t.due_at?'· vence '+new Date(t.due_at).toLocaleDateString('es-AR'):''}</div><div class="chips">${statusChip(t.status)}${a?assignChip(a.assignment_status):''}</div></div><span class="arr">›</span></button>`}
function noteRow(n){return `<div class="rowCard"><div class="ico">🔔</div><div><b>${esc(n.title)}</b><div class="meta">${esc(n.body||'')}</div><div class="tiny">${new Date(n.created_at).toLocaleString('es-AR')}</div></div>${n.href?`<button class="btn small" data-note-href="${esc(n.href)}">Abrir</button>`:''}</div>`}
function eventCard(e){return `<button class="card click" data-event-open="${e.id}"><div class="quick"><div class="ico">${e.kind==='saturday'?'🗓':e.kind==='camp'?'🏕️':'◇'}</div><div class="grow"><h3>${esc(e.name)}</h3><p>${fmtDate(e.start_date)}${e.end_date!==e.start_date?' → '+fmtDate(e.end_date):''}${e.location?' · '+esc(e.location):''}</p><div class="chips"><span class="chip">${esc(e.status)}</span>${e.event_mode?'<span class="chip">▶ Modo evento</span>':''}</div></div><span class="arr">›</span></div></button>`}
function workloadFor(pid){let now=new Date(),m=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-01`;return S.workload.find(x=>x.person_id===pid&&x.month===m)?.assignments||0}

function viewSchedule(){
  let ev=S.events.filter(e=>e.end_date>=new Date(Date.now()-86400000*30).toISOString().slice(0,10));if(!S.selectedEvent&&ev[0])S.selectedEvent=ev[0].id;let e=eventBy(S.selectedEvent);if(!e)return `<div class="page">${empty('Todavía no hay eventos','Creá un sábado o evento para empezar.',isPastor()||isAdmin()?'Crear evento':'','new-event')}</div>`;
  let days=eventDays(e.id);if(!S.selectedDay||!days.some(d=>d.id===S.selectedDay))S.selectedDay=days[0]?.id||null;
  return `<div class="page"><div class="selectBar"><select id="eventSelect" class="control">${S.events.map(x=>`<option value="${x.id}" ${x.id===e.id?'selected':''}>${esc(x.name)} · ${fmtShort(x.start_date)}</option>`).join('')}</select><div class="actions">${canManageEvent(e.id)?`<button class="btn ${e.event_mode?'good':''}" id="toggleEventMode">${e.event_mode?'■ Salir modo evento':'▶ Modo evento'}</button><button class="btn" data-action="event-members">Personas</button>`:''}</div></div><div class="tabs"><button class="tab ${S.cronTab==='schedule'?'on':''}" data-cron="schedule">Cronograma</button><button class="tab ${S.cronTab==='groups'?'on':''}" data-cron="groups">Grupos por día</button></div>${S.cronTab==='schedule'?schedulePanel(e,days):groupsPanel(e,days)}</div>`}
function schedulePanel(e,days){return `<div class="sectionHead"><h2>${esc(e.name)}</h2>${canManageEvent(e.id)?'<button class="btn primary small" id="addDay">+ Día</button>':''}</div>${days.length?`<div class="tabs">${days.map(d=>`<button class="tab ${d.id===S.selectedDay?'on':''}" data-day="${d.id}">${esc(d.label)}${d.date?' · '+fmtShort(d.date):''}</button>`).join('')}</div>${scheduleDayPanel(e,dayBy(S.selectedDay))}`:empty('Sin días cargados','Agregá “Día 1 / Viernes”, “Día 2 / Sábado”, etc.',canManageEvent(e.id)?'Agregar primer día':'','')}`}
function scheduleDayPanel(e,d){if(!d)return'';let its=dayItems(d.id);return `<div class="sectionHead"><h2>${esc(d.label)}</h2>${canManageEvent(e.id)?'<button class="btn primary small" id="addScheduleItem">+ Actividad</button>':''}</div>${its.length?`<div class="timeline">${its.map(i=>scheduleItemRow(e,i)).join('')}</div>`:empty('Sin actividades','Cargá juegos, comidas, reuniones y todo el cronograma.')}`}
function scheduleItemRow(e,i){let rp=itemPeople(i.id);return `<article class="timeItem"><div class="timeBox">${fmtTime(i.starts_at)}<small>${i.duration_minutes?i.duration_minutes+' min':''}</small></div><div><h3 style="margin:0">${esc(i.title)}</h3><div class="tiny">${esc(i.item_type)}${i.location?' · '+esc(i.location):''}</div>${rp.length?`<div class="responsibles">${rp.map(id=>`<button class="personLink" data-person-open="${id}">${esc(displayName(id))}</button>`).join('')}</div>`:'<div class="tiny" style="margin-top:7px">Sin responsable</div>'}</div><div class="actions">${runChip(i.run_status||'pending')}<button class="btn small" data-item-open="${i.id}">Ver</button>${e.event_mode&&canManageEvent(e.id)?`<button class="btn small" data-run-next="${i.id}">Cambiar estado</button>`:''}</div></article>`}

function groupsPanel(e,days){if(!days.length)return empty('Primero cargá los días','Los equipos se generan por día.');let d=dayBy(S.selectedDay)||days[0];let gs=S.groups.filter(g=>g.event_id===e.id&&g.day_id===d.id).sort((a,b)=>a.sort_order-b.sort_order);let members=eventMembers(e.id).filter(m=>m.include_in_groups!==false);let missing=[];let cfg=S.groupConfigs.find(c=>c.event_id===e.id&&c.day_id===d.id);for(let m of members){let p=pBy(m.person_id);if(!p)continue;if((cfg?.balance_sex??true)&&(!p.sex||p.sex==='U'))missing.push(displayName(p.id)+' · sexo');if((cfg?.balance_age??true)&&!p.birthday)missing.push(displayName(p.id)+' · nacimiento')}
  return `<div class="tabs">${days.map(x=>`<button class="tab ${x.id===d.id?'on':''}" data-day="${x.id}">${esc(x.label)}</button>`).join('')}</div><div class="sectionHead"><div><h2>División · ${esc(d.label)}</h2><div class="tiny">${members.length} personas incluidas</div></div>${canManageEvent(e.id)?'<div class="actions"><button class="btn" data-action="event-members">Participantes</button><button class="btn primary" data-action="group-config">Generar / configurar</button></div>':''}</div>${missing.length?`<div class="warning">Para equilibrar correctamente faltan datos confirmados: ${esc([...new Set(missing)].join(', '))}. La app no infiere sexo por el nombre.</div>`:''}${gs.length?`<div class="groupGrid" style="margin-top:13px">${gs.map(g=>groupBox(g,gs)).join('')}</div>`:empty('Todavía no hay equipos','Configurá Rojo/Azul (o los nombres que quieras) y generá la división.')}`}
function groupBox(g,allGroups){let ms=S.groupMembers.filter(m=>m.group_id===g.id);let avg=ms.length?Math.round(ms.reduce((s,m)=>s+(m.age_snapshot||0),0)/ms.length):0;let sex=ms.reduce((o,m)=>(o[m.sex_snapshot||'U']=(o[m.sex_snapshot||'U']||0)+1,o),{});return `<section class="teamBox"><header class="teamHead"><h3><span class="teamDot" style="background:${esc(g.color)}"></span>${esc(g.name)}</h3><span class="tiny">${ms.length} · edad prom. ${avg||'—'} · F ${sex.F||0} / M ${sex.M||0}</span></header><div class="teamMembers">${ms.map(m=>{let p=pBy(m.person_id);return `<div class="member">${avatarHtml(m.person_id)}<div><b>${esc(displayName(m.person_id))}</b><div class="tiny">${m.age_snapshot??'—'} años · ${m.sex_snapshot==='F'?'F':m.sex_snapshot==='M'?'M':'Sin confirmar'}</div></div>${canManageEvent(g.event_id)?`<select data-move-person="${m.person_id}" data-from-group="${g.id}">${allGroups.map(x=>`<option value="${x.id}" ${x.id===g.id?'selected':''}>${esc(x.name)}</option>`).join('')}</select>`:''}</div>`}).join('')||'<div class="tiny">Sin personas</div>'}</div></section>`}

function viewSaturdays(){let m=S.satMonth,year=m.getFullYear(),month=m.getMonth();let dates=[];let x=new Date(year,month,1);while(x.getMonth()===month){if(x.getDay()===6)dates.push(x.toISOString().slice(0,10));x.setDate(x.getDate()+1)}let monthLabel=new Intl.DateTimeFormat('es-AR',{month:'long',year:'numeric'}).format(m);return `<div class="page"><div class="sectionHead"><div><h2 style="text-transform:capitalize">${esc(monthLabel)}</h2><div class="tiny">Los sábados aparecen automáticamente</div></div><div class="actions"><button class="btn" id="satPrev">‹</button><button class="btn" id="satNext">›</button>${isAdmin()||isPastor()?'<button class="btn primary" data-action="new-saturday">+ Sábado</button>':''}</div></div><div class="grid g2">${dates.map(d=>{let e=S.events.find(e=>e.kind==='saturday'&&e.start_date===d);return e?eventCard(e):`<div class="card"><div class="quick"><div class="ico">🗓</div><div class="grow"><h3>${fmtDate(d)}</h3><p>Sin preparar</p></div>${isAdmin()||isPastor()?`<button class="btn small primary" data-create-sat="${d}">Preparar</button>`:''}</div></div>`}).join('')}</div></div>`}
function viewEvents(){let es=S.events.filter(e=>e.kind!=='saturday');return `<div class="page"><section class="hero"><div class="eyebrow">Organización general</div><h1>Eventos</h1><p>Congresos, campamentos, vigilias, salidas y actividades especiales con responsables, tareas y seguimiento.</p></section><div class="sectionHead"><h2>Todos</h2>${isAdmin()||isPastor()?'<button class="btn primary" data-action="new-event">+ Crear evento</button>':''}</div>${es.length?`<div class="grid g2">${es.map(eventCard).join('')}</div>`:empty('Sin eventos','Creá uno desde una plantilla.')}</div>`}
function viewMyTasks(){let xs=S.assignees.filter(a=>a.person_id===currentPersonId()).map(a=>({a,t:taskBy(a.task_id)})).filter(x=>x.t).sort((x,y)=>(x.t.due_at||'9999').localeCompare(y.t.due_at||'9999'));return `<div class="page"><section class="hero"><div class="eyebrow">Responsabilidades</div><h1>Mis tareas</h1><p>Leé, aceptá o avisá si no podés. El estado de la tarea se gestiona por separado.</p></section>${xs.length?`<div class="list">${xs.map(({a,t})=>taskRow(t,a)).join('')}</div>`:empty('Sin tareas','')}</div>`}
function viewTeam(){let q=(window._teamSearch||'').toLowerCase();let ps=S.people.filter(p=>p.active!==false&&displayName(p.id).toLowerCase().includes(q));return `<div class="page"><div class="sectionHead"><div><h2>Equipo TNT</h2><div class="tiny">${ps.length} perfiles</div></div><div class="actions"><input class="control" id="teamSearch" placeholder="Buscar" value="${esc(window._teamSearch||'')}">${isAdmin()?'<button class="btn primary" data-action="new-person">+ Perfil</button>':''}</div></div><div class="peopleGrid">${ps.map(personCard).join('')}</div></div>`}
function personCard(p){let a=aByPid(p.id),w=workloadFor(p.id),pct=Math.min(100,w*18);return `<article class="personCard"><div class="personTop">${avatarHtml(p.id)}<div class="grow"><h3>${esc(a?.nickname||p.full_name)}</h3><p>${esc(a?.ministry_role||'Sin rol')}${a?.system_role==='admin'?' · Admin':''}</p></div><button class="btn small" data-person-open="${p.id}">Ver</button></div><div class="workload"><div class="bar"><span style="width:${pct}%"></span></div><span class="tiny">${w} este mes</span></div>${a?.service_areas?.length?`<div class="chips">${a.service_areas.slice(0,3).map(x=>`<span class="chip">${esc(x)}</span>`).join('')}</div>`:''}</article>`}
function viewTemplates(){return `<div class="page"><section class="hero"><div class="eyebrow">Reutilizable</div><h1>Plantillas</h1><p>Creá un sábado, evento evangelístico o congreso con su estructura ya preparada.</p></section><div class="sectionHead"><h2>Plantillas</h2>${canManageTemplates()?'<button class="btn primary" data-action="new-template">+ Plantilla</button>':''}</div><div class="grid g2">${S.templates.map(t=>templateCard(t)).join('')}</div></div>`}
function templateCard(t){let items=S.templateItems.filter(i=>i.template_id===t.id).sort((a,b)=>a.sort_order-b.sort_order);return `<article class="card"><div class="quick"><div class="ico">${t.kind==='saturday'?'🗓':'▦'}</div><div class="grow"><h3>${esc(t.name)}</h3><p>${esc(t.description||'')}</p></div>${t.is_default?'<span class="chip">Predeterminada</span>':''}</div><div class="chips">${items.map(i=>`<span class="chip">${esc(i.icon||'✓')} ${esc(i.title)}</span>`).join('')}</div>${canManageTemplates()?`<div class="actions" style="margin-top:13px"><button class="btn small" data-template-edit="${t.id}">Editar</button><button class="btn small primary" data-template-start="${t.id}">Usar</button></div>`:''}</article>`}
function viewAdmin(){if(!isAdmin())return `<div class="page">${empty('Solo Admin','No tenés permiso para esta sección.')}</div>`;let accounts=S.accounts.map(a=>({a,p:pBy(a.person_id)})).filter(x=>x.p);return `<div class="page"><section class="hero"><div class="eyebrow">Sistema</div><h1>Administración</h1><p>Gestioná roles TNT, administradores, acceso a módulos y cuentas habilitadas.</p></section><div class="sectionHead"><h2>Usuarios</h2><div class="actions"><button class="btn" data-action="general-notification">Notificación general</button><button class="btn primary" data-action="new-person">+ Perfil / invitación</button></div></div><div class="list">${accounts.map(({a,p})=>adminUserRow(a,p)).join('')}</div></div>`}
function adminUserRow(a,p){return `<div class="rowCard">${avatarHtml(p.id)}<div><b>${esc(a.nickname||p.full_name)}</b><div class="meta">${esc(a.email||'Sin email')} · ${a.auth_user_id?'Cuenta vinculada':'Pendiente de ingreso'}</div><div class="chips"><span class="chip">${esc(a.ministry_role)}</span>${a.system_role==='admin'?'<span class="chip">Admin</span>':''}${!a.enabled?'<span class="status declined">Deshabilitado</span>':''}</div></div><div class="actions"><button class="btn small" data-admin-user="${p.id}">Gestionar</button></div></div>`}
