function bindViewSpecific(){
  if(S.view==='schedule')bindSchedule();if(S.view==='saturdays')bindSaturdays();if(S.view==='team'){let x=$('#teamSearch');if(x)x.oninput=e=>{window._teamSearch=e.target.value;render()}}if(S.view==='templates'){$$('[data-template-edit]').forEach(b=>b.onclick=()=>templateModal(b.dataset.templateEdit));$$('[data-template-start]').forEach(b=>b.onclick=()=>eventCreateModal(b.dataset.templateStart))}if(S.view==='admin')$$('[data-admin-user]').forEach(b=>b.onclick=()=>adminUserModal(b.dataset.adminUser));
  $$('[data-note-href]').forEach(b=>b.onclick=()=>openInternal(b.dataset.noteHref));
}
const _render=render;render=function(){_render();bindViewSpecific()}

function bindSchedule(){
  $('#eventSelect')?.addEventListener('change',e=>{S.selectedEvent=e.target.value;S.selectedDay=eventDays(S.selectedEvent)[0]?.id||null;render()});
  $$('[data-cron]').forEach(b=>b.onclick=()=>{S.cronTab=b.dataset.cron;render()});$$('[data-day]').forEach(b=>b.onclick=()=>{S.selectedDay=b.dataset.day;render()});
  $('#toggleEventMode')?.addEventListener('click',async()=>{let e=eventBy(S.selectedEvent);let {error}=await sb.from('tnt_events').update({event_mode:!e.event_mode}).eq('id',e.id);if(error)return toast(errMsg(error));await loadAll();render()});
  $('#addDay')?.addEventListener('click',()=>dayModal());$('#addScheduleItem')?.addEventListener('click',()=>scheduleItemModal());
  $$('[data-item-open]').forEach(b=>b.onclick=()=>scheduleItemDetailModal(b.dataset.itemOpen));
  $$('[data-run-next]').forEach(b=>b.onclick=()=>cycleRunStatus(b.dataset.runNext));
  $$('[data-move-person]').forEach(s=>s.onchange=()=>moveGroupMember(s.dataset.movePerson,s.dataset.fromGroup,s.value));
}
function bindSaturdays(){
  $('#satPrev')?.addEventListener('click',()=>{S.satMonth=new Date(S.satMonth.getFullYear(),S.satMonth.getMonth()-1,1);render()});$('#satNext')?.addEventListener('click',()=>{S.satMonth=new Date(S.satMonth.getFullYear(),S.satMonth.getMonth()+1,1);render()});
  $$('[data-create-sat]').forEach(b=>b.onclick=()=>createSaturday(b.dataset.createSat));
}

async function createSaturday(date){let {data,error}=await sb.rpc('tnt_create_saturday',{p_date:date,p_name:'Sábado TNT'});if(error)return toast(errMsg(error));await loadAll();toast('Sábado preparado');eventDetailModal(data)}
function saturdayCreateModal(){modal(`${sheetHead('Preparar sábado')}<form class="form" id="satForm"><div class="field"><label>Fecha</label><input type="date" name="date" required></div><div class="field"><label>Nombre</label><input name="name" value="Sábado TNT"></div><button class="btn primary">Crear desde plantilla</button></form>`);$('#satForm').onsubmit=async e=>{e.preventDefault();let f=new FormData(e.target),{data,error}=await sb.rpc('tnt_create_saturday',{p_date:f.get('date'),p_name:f.get('name')});if(error)return toast(errMsg(error));closeModal();await loadAll();toast('Sábado creado');eventDetailModal(data)}}
function eventCreateModal(templateId=''){let opts=S.templates.map(t=>`<option value="${t.id}" ${t.id===templateId?'selected':''}>${esc(t.name)}</option>`).join('');modal(`${sheetHead('Crear evento','Usá una plantilla y después modificá lo que necesites.')}<form class="form" id="eventForm"><div class="field"><label>Plantilla</label><select name="template" required>${opts}</select></div><div class="field"><label>Nombre del evento</label><input name="name" required placeholder="Congreso TNT"></div><div class="formRow"><div class="field"><label>Desde</label><input type="date" name="start" required></div><div class="field"><label>Hasta</label><input type="date" name="end"></div></div><div class="field"><label>Lugar</label><input name="location"></div><button class="btn primary">Crear evento</button></form>`);$('#eventForm').onsubmit=async e=>{e.preventDefault();let f=new FormData(e.target),tpl=S.templates.find(t=>t.id===f.get('template'));let {data,error}=await sb.rpc('tnt_create_event_from_template',{p_template:f.get('template'),p_name:f.get('name'),p_start:f.get('start'),p_end:f.get('end')||f.get('start'),p_location:f.get('location')||null,p_kind:tpl?.kind||'event'});if(error)return toast(errMsg(error));closeModal();await loadAll();toast('Evento creado');eventDetailModal(data)}}

function eventDetailModal(id){let e=eventBy(id);if(!e)return;let tasks=eventTasks(id),members=eventMembers(id),orgs=members.filter(m=>m.event_role==='organizer');let manager=canManageEvent(id);modal(`${sheetHead(e.name,`${fmtDate(e.start_date)}${e.end_date!==e.start_date?' → '+fmtDate(e.end_date):''}`)}<div class="grid g3"><div class="card"><h3>Estado</h3><div class="chips"><span class="chip">${esc(e.status)}</span>${e.event_mode?'<span class="chip">▶ Modo evento</span>':''}</div></div><div class="card"><h3>Organizadores</h3><div class="responsibles">${orgs.map(m=>`<button class="personLink" data-person-open="${m.person_id}">${esc(displayName(m.person_id))}</button>`).join('')||'<span class="tiny">Sin organizadores</span>'}</div></div><div class="card"><h3>Participantes</h3><p>${members.filter(m=>m.include_in_groups!==false).length} incluidos para grupos</p></div></div><div class="sectionHead"><h2>Tareas</h2>${manager?`<div class="actions"><button class="btn" id="manageEventMembers">Personas</button><button class="btn primary" id="newTask">+ Tarea</button></div>`:''}</div>${tasks.length?`<div class="list">${tasks.map(t=>taskRow(t,myAssignment(t))).join('')}</div>`:empty('Sin tareas','')}`,true);$$('[data-task-open]').forEach(b=>b.onclick=()=>taskDetailModal(b.dataset.taskOpen));$$('[data-person-open]').forEach(b=>b.onclick=()=>personResponsibilitiesModal(b.dataset.personOpen));$('#manageEventMembers')?.addEventListener('click',()=>eventMembersModal(id));$('#newTask')?.addEventListener('click',()=>taskEditModal(null,id))}

function dayModal(d=null){let e=eventBy(S.selectedEvent),days=eventDays(e.id);modal(`${sheetHead(d?'Editar día':'Agregar día')}<form class="form" id="dayForm"><div class="field"><label>Nombre</label><input name="label" value="${esc(d?.label||`Día ${days.length+1}`)}" placeholder="Día 1 / Viernes" required></div><div class="field"><label>Fecha</label><input type="date" name="date" value="${esc(d?.date||'')}"></div><button class="btn primary">Guardar</button></form>`);$('#dayForm').onsubmit=async ev=>{ev.preventDefault();let f=new FormData(ev.target),payload={event_id:e.id,label:f.get('label'),date:f.get('date')||null,sort_order:d?.sort_order??days.length};let q=d?sb.from('tnt_schedule_days').update(payload).eq('id',d.id):sb.from('tnt_schedule_days').insert(payload).select().single();let {data,error}=await q;if(error)return toast(errMsg(error));closeModal();await loadAll();S.selectedDay=d?.id||data?.id;render()}}
