function groupConfigModal(dayId){let d=dayBy(dayId),e=eventBy(d?.event_id);if(!d||!e)return;let cfg=S.groupConfigs.find(c=>c.event_id===e.id&&c.day_id===d.id),existing=S.groups.filter(g=>g.event_id===e.id&&g.day_id===d.id).sort((a,b)=>a.sort_order-b.sort_order),count=cfg?.group_count||Math.max(2,existing.length||2),names=existing.length?existing.map(g=>g.name).join('\n'):['Rojo','Azul'].join('\n'),colors=existing.length?existing.map(g=>g.color).join('\n'):['#e5484d','#3b82f6'].join('\n');modal(`${sheetHead('Configurar grupos',d.label)}<form class="form" id="groupForm"><div class="field"><label>Cantidad de equipos</label><input type="number" name="count" min="2" max="8" value="${count}"></div><div class="formRow"><div class="field"><label>Nombres (uno por línea)</label><textarea name="names">${esc(names)}</textarea></div><div class="field"><label>Colores HEX (uno por línea)</label><textarea name="colors">${esc(colors)}</textarea></div></div><label class="checkRow"><input type="checkbox" name="age" ${cfg?.balance_age===false?'':'checked'}><span>Equilibrar edades</span></label><label class="checkRow"><input type="checkbox" name="sex" ${cfg?.balance_sex===false?'':'checked'}><span>Equilibrar sexo confirmado</span></label><label class="checkRow"><input type="checkbox" name="rotate" ${cfg?.avoid_previous_day===false?'':'checked'}><span>Evitar repetir equipo del día anterior</span></label><div class="warning">La app nunca infiere sexo por el nombre. Si falta sexo o fecha de nacimiento, te lo va a pedir antes de generar.</div><button class="btn primary">Generar equipos</button></form>`);$('#groupForm').onsubmit=e2=>generateGroups(e2,e,d,cfg)}
async function generateGroups(ev,e,d,cfg){ev.preventDefault();let f=new FormData(ev.target),count=Math.max(2,Math.min(8,Number(f.get('count'))||2)),names=String(f.get('names')||'').split(/\n+/).map(s=>s.trim()).filter(Boolean),colors=String(f.get('colors')||'').split(/\n+/).map(s=>s.trim()).filter(Boolean),balanceAge=f.get('age')==='on',balanceSex=f.get('sex')==='on',rotate=f.get('rotate')==='on';while(names.length<count)names.push(`Equipo ${names.length+1}`);while(colors.length<count)colors.push(['#e5484d','#3b82f6','#8b5cf6','#10b981','#f59e0b','#ec4899'][colors.length%6]);let pool=eventMembers(e.id).filter(m=>m.include_in_groups!==false).map(m=>pBy(m.person_id)).filter(Boolean);let missing=[];pool.forEach(p=>{if(balanceSex&&(!p.sex||p.sex==='U'))missing.push(displayName(p.id)+' (sexo)');if(balanceAge&&!p.birthday)missing.push(displayName(p.id)+' (nacimiento)')});if(missing.length)return toast('Faltan datos: '+missing.slice(0,4).join(', ')+(missing.length>4?'…':''));
  let payload={event_id:e.id,day_id:d.id,group_count:count,balance_age:balanceAge,balance_sex:balanceSex,avoid_previous_day:rotate,updated_by:currentPersonId()};let qr=cfg?await sb.from('tnt_group_configs').update(payload).eq('id',cfg.id):await sb.from('tnt_group_configs').insert(payload);if(qr.error)return toast(errMsg(qr.error));
  let old=S.groups.filter(g=>g.event_id===e.id&&g.day_id===d.id);if(old.length){let del=await sb.from('tnt_groups').delete().in('id',old.map(g=>g.id));if(del.error)return toast(errMsg(del.error))}
  let {data:newGroups,error:ge}=await sb.from('tnt_groups').insert([...Array(count)].map((_,i)=>({event_id:e.id,day_id:d.id,name:names[i],color:colors[i],sort_order:i}))).select();if(ge)return toast(errMsg(ge));newGroups.sort((a,b)=>a.sort_order-b.sort_order);
  let days=eventDays(e.id),idx=days.findIndex(x=>x.id===d.id),prev=idx>0?days[idx-1]:null,prevMap=new Map();if(prev){let pgs=S.groups.filter(g=>g.event_id===e.id&&g.day_id===prev.id);for(let g of pgs)for(let m of S.groupMembers.filter(x=>x.group_id===g.id))prevMap.set(m.person_id,g.name)}
  let persons=pool.map(p=>({p,age:age(p.birthday,d.date?new Date(d.date+'T12:00:00'):new Date()),sex:p.sex||'U'}));persons.sort((a,b)=>(a.sex||'').localeCompare(b.sex||'')||((b.age||0)-(a.age||0)));let teams=newGroups.map(g=>({g,people:[],ageSum:0,sex:{F:0,M:0,U:0}}));let targetAvg=persons.length?persons.reduce((s,x)=>s+(x.age||0),0)/persons.length:0;
  for(let x of persons){let scored=teams.map(t=>{let size=t.people.length,score=size*100;if(balanceSex)score+=(t.sex[x.sex]||0)*35;if(balanceAge&&x.age!=null){let avg=(t.ageSum+x.age)/(size+1);score+=Math.abs(avg-targetAvg)*4}if(rotate&&prevMap.get(x.p.id)===t.g.name)score+=75;return{t,score}}).sort((a,b)=>a.score-b.score);let t=scored[0].t;t.people.push(x);t.ageSum+=x.age||0;t.sex[x.sex]=(t.sex[x.sex]||0)+1}
  let rows=[];teams.forEach(t=>t.people.forEach(x=>rows.push({group_id:t.g.id,person_id:x.p.id,age_snapshot:x.age,sex_snapshot:x.sex})));if(rows.length){let ir=await sb.from('tnt_group_members').insert(rows);if(ir.error)return toast(errMsg(ir.error))}closeModal();await loadAll();render();toast('Equipos generados')}
async function moveGroupMember(personId,fromId,toId){if(fromId===toId)return;let old=S.groupMembers.find(m=>m.group_id===fromId&&m.person_id===personId);let d=await sb.from('tnt_group_members').delete().eq('group_id',fromId).eq('person_id',personId);if(d.error)return toast(errMsg(d.error));let i=await sb.from('tnt_group_members').insert({group_id:toId,person_id:personId,age_snapshot:old?.age_snapshot,sex_snapshot:old?.sex_snapshot});if(i.error)return toast(errMsg(i.error));await loadAll();render()}

