async function assignmentResponse(id,status){let note=null;if(status==='declined')note=prompt('Si querés, contá brevemente por qué no podés:')||null;let {error}=await sb.rpc('tnt_set_assignment_response',{p_task:id,p_status:status,p_note:note});if(error)return toast(errMsg(error));await loadAll();taskDetailModal(id)}
async function setTaskStatus(id,status){let {error}=await sb.rpc('tnt_set_task_status',{p_task:id,p_status:status});if(error)return toast(errMsg(error));await loadAll();taskDetailModal(id)}
async function toggleCheck(id,done){let {error}=await sb.from('tnt_task_checklist').update({done}).eq('id',id);if(error)toast(errMsg(error))}
function addChecklistModal(taskId,order){modal(`${sheetHead('Agregar punto')}<form class="form" id="checkForm"><div class="field"><label>Texto</label><input name="text" required></div><button class="btn primary">Agregar</button></form>`);$('#checkForm').onsubmit=async ev=>{ev.preventDefault();let text=new FormData(ev.target).get('text');let {error}=await sb.from('tnt_task_checklist').insert({task_id:taskId,text,sort_order:order});if(error)return toast(errMsg(error));taskDetailModal(taskId)}}
function linkType(url){try{let h=new URL(url).hostname;if(h.includes('youtu'))return'youtube';if(h.includes('pinterest'))return'pinterest';if(h.includes('instagram'))return'instagram';if(h.includes('drive.google'))return'drive';if(h.includes('canva'))return'canva'}catch{}return'link'}
function addLinkModal(taskId,order){modal(`${sheetHead('Agregar referencia')}<form class="form" id="linkForm"><div class="field"><label>URL</label><input name="url" type="url" required></div><div class="field"><label>Etiqueta</label><input name="label" placeholder="Referencia"></div><button class="btn primary">Agregar</button></form>`);$('#linkForm').onsubmit=async ev=>{ev.preventDefault();let f=new FormData(ev.target),url=f.get('url');let {error}=await sb.from('tnt_task_links').insert({task_id:taskId,url,label:f.get('label')||null,link_type:linkType(url),sort_order:order});if(error)return toast(errMsg(error));taskDetailModal(taskId)}}
function linkCard(l){let thumb='🔗',img='';if(l.link_type==='youtube'){thumb='▶';try{let u=new URL(l.url),id=u.hostname.includes('youtu.be')?u.pathname.slice(1):u.searchParams.get('v');if(id)img=`https://i.ytimg.com/vi/${encodeURIComponent(id)}/hqdefault.jpg`}catch{}}else if(l.link_type==='pinterest')thumb='📌';else if(l.link_type==='instagram')thumb='📷';else if(l.link_type==='drive')thumb='📄';else if(l.link_type==='canva')thumb='🎨';return `<a class="linkPreview" href="${esc(l.url)}" target="_blank" rel="noopener">${img?`<img src="${img}" alt="">`:`<div class="linkThumb">${thumb}</div>`}<div><b>${esc(l.label||l.link_type)}</b><small>${esc(l.url)}</small></div><span class="arr">›</span></a>`}
async function uploadTaskFile(taskId,file){if(!file)return;let safe=file.name.replace(/[^a-zA-Z0-9._-]+/g,'_'),path=`${taskId}/${currentPersonId()}/${Date.now()}-${safe}`;let up=await sb.storage.from('tnt-files').upload(path,file,{upsert:false});if(up.error)return toast(errMsg(up.error));let r=await sb.from('tnt_task_files').insert({task_id:taskId,storage_path:path,file_name:file.name,mime_type:file.type,size_bytes:file.size,uploaded_by:currentPersonId()});if(r.error)return toast(errMsg(r.error));toast('Archivo subido');taskDetailModal(taskId)}
async function openTaskFile(path){let {data,error}=await sb.storage.from('tnt-files').createSignedUrl(path,300);if(error)return toast(errMsg(error));window.open(data.signedUrl,'_blank','noopener')}
function addPrivateNoteModal(taskId){modal(`${sheetHead('Nota privada','Solo organizadores / Pastor / Admin')}<form class="form" id="privateForm"><div class="field"><textarea name="body" required></textarea></div><button class="btn primary">Guardar</button></form>`);$('#privateForm').onsubmit=async ev=>{ev.preventDefault();let body=new FormData(ev.target).get('body');let {error}=await sb.from('tnt_task_private_notes').insert({task_id:taskId,author_person_id:currentPersonId(),body});if(error)return toast(errMsg(error));taskDetailModal(taskId)}}

async function personResponsibilitiesModal(pid){let p=pBy(pid),a=aByPid(pid);if(!p)return;let tasks=S.assignees.filter(x=>x.person_id===pid).map(x=>({a:x,t:taskBy(x.task_id)})).filter(x=>x.t),sched=S.responsibles.filter(r=>r.person_id===pid).map(r=>{let i=S.items.find(x=>x.id===r.item_id),d=dayBy(i?.day_id),e=eventBy(d?.event_id);return{i,d,e}}).filter(x=>x.i);let avail=S.availability.filter(x=>x.person_id===pid&&x.date>=today()).slice(0,6);modal(`${sheetHead(a?.nickname||p.full_name,a?.ministry_role||'')}<div class="profileHero">${avatarHtml(pid)}<div><h3 style="margin:0">${esc(p.full_name)}</h3><p class="muted" style="margin:4px 0">${p.birthday?'🎂 '+fmtDate(p.birthday):''}${p.phone?' · 📱 '+esc(p.phone):''}</p><div class="chips">${a?.service_areas?.map(x=>`<span class="chip">${esc(x)}</span>`).join('')||''}</div></div><div class="actions">${pid===currentPersonId()||isAdmin()||isPastor()?`<button class="btn small" id="editPerson">Editar perfil</button>`:''}</div></div><div class="sectionHead"><h2>Responsabilidades</h2></div>${sched.length?`<div class="list">${sched.map(x=>`<div class="rowCard"><div class="ico">◷</div><div><b>${esc(x.i.title)}</b><div class="meta">${esc(x.e?.name||'')} · ${esc(x.d?.label||'')} · ${fmtTime(x.i.starts_at)}</div></div><button class="btn small" data-item-open="${x.i.id}">Ver</button></div>`).join('')}</div>`:''}${tasks.length?`<div class="list" style="margin-top:9px">${tasks.map(({a,t})=>taskRow(t,a)).join('')}</div>`:''}${!tasks.length&&!sched.length?empty('Sin responsabilidades',''):''}<div class="sectionHead"><h2>Disponibilidad</h2>${pid===currentPersonId()?'<button class="btn small" id="addAvailability">+ Fecha</button>':''}</div>${avail.length?`<div class="chips">${avail.map(x=>`<span class="chip">${fmtShort(x.date)} · ${x.status==='available'?'Disponible':x.status==='maybe'?'Tal vez':'No puede'}</span>`).join('')}</div>`:'<div class="tiny">Sin fechas cargadas</div>'}`,true);$('#editPerson')?.addEventListener('click',()=>profileModal(pid));$('#addAvailability')?.addEventListener('click',()=>availabilityModal(pid));$$('[data-task-open]').forEach(b=>b.onclick=()=>taskDetailModal(b.dataset.taskOpen));$$('[data-item-open]').forEach(b=>b.onclick=()=>scheduleItemDetailModal(b.dataset.itemOpen))}

