-- Conversations are created when a team member explicitly opens or creates one.
-- Preserve history while clearing empty conversations generated by old triggers.
drop trigger if exists trg_tnt_task_chat on public.tnt_tasks;
drop trigger if exists trg_tnt_event_chat on public.tnt_events;

update public.tnt_chat_threads t set is_archived=true
where t.thread_type in ('task','event','efe') and not t.is_archived
and not exists(select 1 from public.tnt_chat_messages m where m.thread_id=t.id);

create or replace function public.tnt_open_activity_chat(p_task uuid default null,p_event uuid default null)
returns uuid language plpgsql set search_path to '' as $function$
declare v_id uuid; v_title text; v_event uuid;
begin
 if public.tnt_current_person_id() is null or (p_task is null)=(p_event is null) then
   raise exception 'Elegí una tarea o un evento.' using errcode='42501';
 end if;
 if p_task is not null then
   select event_id into v_event from public.tnt_tasks where id=p_task;
   if v_event is null or not (public.tnt_can_manage_event(v_event) or exists(select 1 from public.tnt_task_assignees where task_id=p_task and person_id=public.tnt_current_person_id())) then
     raise exception 'Esta conversación es para el equipo del encuentro.' using errcode='42501';
   end if;
 else
   v_event:=p_event;
   if not (public.tnt_can_manage_event(v_event) or exists(select 1 from public.tnt_event_members where event_id=v_event and person_id=public.tnt_current_person_id()) or exists(select 1 from public.tnt_tasks t join public.tnt_task_assignees a on a.task_id=t.id where t.event_id=v_event and a.person_id=public.tnt_current_person_id())) then
     raise exception 'Esta conversación es para el equipo del encuentro.' using errcode='42501';
   end if;
 end if;
 select name into v_title from public.tnt_events where id=v_event;
 if v_title is null then raise exception 'No encontramos el encuentro.' using errcode='22023'; end if;
 perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended('tnt-event-chat:'||v_event::text,0));
 select id into v_id from public.tnt_chat_threads where thread_type='event' and event_id=v_event and not is_archived order by created_at desc limit 1;
 if v_id is null then
   insert into public.tnt_chat_threads(title,thread_type,event_id,created_by) values(v_title,'event',v_event,public.tnt_current_person_id()) returning id into v_id;
 end if;
 return v_id;
end $function$;
